import { Expression } from "../../src/lib/dataset/schemas";
import { makeExpressionId, makeVerbId, makeVocabId, slugify } from "../../src/lib/dataset/ids";

export interface RawExpressionSpec {
  canonical_form: string;
  display_form?: string;
  english: string[];
  expression_type:
    | "verb_pattern"
    | "collocation"
    | "fixed_expression"
    | "idiom"
    | "sentence_starter"
    | "conversation_phrase"
    | "connector"
    | "functional_phrase"
    | "formulaic_phrase";
  base_verbs?: string[];
  related_vocab?: string[];
  pattern?: string;
  mood_governance?: { following_clause_mood?: string; notes?: string };
  chapter_number: number;
  page_printed: number;
  usage_notes?: string[];
  tags?: string[];
}

export const MASTER_EXPRESSION_SPECS: RawExpressionSpec[] = [
  // CHAPTER 1: Present of regular -er verbs & aspect
  {
    canonical_form: "être en train de + infinitif",
    display_form: "être en train de + infinitif",
    english: ["to be in the middle of doing something", "to be in the process of doing"],
    expression_type: "verb_pattern",
    base_verbs: ["être"],
    pattern: "être en train de + [infinitive]",
    chapter_number: 1,
    page_printed: 10,
    tags: ["aspect", "present", "progressive"],
  },
  {
    canonical_form: "depuis combien de temps",
    english: ["for how long", "how long have you been..."],
    expression_type: "sentence_starter",
    chapter_number: 1,
    page_printed: 11,
    tags: ["interrogative", "time", "duration"],
  },
  {
    canonical_form: "depuis quand",
    english: ["since when"],
    expression_type: "sentence_starter",
    chapter_number: 1,
    page_printed: 11,
    tags: ["interrogative", "time", "starting_point"],
  },
  {
    canonical_form: "il y a ... que",
    english: ["it has been (time) since", "... have been doing for (time)"],
    expression_type: "sentence_starter",
    chapter_number: 1,
    page_printed: 11,
    tags: ["time", "duration", "present_tense"],
  },
  {
    canonical_form: "ça fait ... que",
    english: ["it has been (time) that", "have been doing for (time)"],
    expression_type: "sentence_starter",
    chapter_number: 1,
    page_printed: 11,
    tags: ["time", "duration", "colloquial"],
  },
  {
    canonical_form: "avoir l'habitude de + infinitif",
    english: ["to be used to doing", "to have the habit of doing"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    pattern: "avoir l'habitude de + [infinitive]",
    chapter_number: 1,
    page_printed: 10,
    tags: ["habitual", "present"],
  },

  // CHAPTER 2: Interrogatives & Negation
  {
    canonical_form: "est-ce que",
    english: ["is it that (question starter)"],
    expression_type: "sentence_starter",
    chapter_number: 2,
    page_printed: 18,
    tags: ["question_formation", "standard"],
  },
  {
    canonical_form: "qu'est-ce que",
    english: ["what (direct object question)"],
    expression_type: "sentence_starter",
    chapter_number: 2,
    page_printed: 18,
    tags: ["question_formation", "direct_object"],
  },
  {
    canonical_form: "qu'est-ce qui",
    english: ["what (subject question)"],
    expression_type: "sentence_starter",
    chapter_number: 2,
    page_printed: 18,
    tags: ["question_formation", "subject"],
  },
  {
    canonical_form: "qui est-ce qui",
    english: ["who (subject question)"],
    expression_type: "sentence_starter",
    chapter_number: 2,
    page_printed: 18,
    tags: ["question_formation", "person_subject"],
  },
  {
    canonical_form: "qui est-ce que",
    english: ["whom (direct object question)"],
    expression_type: "sentence_starter",
    chapter_number: 2,
    page_printed: 18,
    tags: ["question_formation", "person_object"],
  },
  {
    canonical_form: "n'est-ce pas",
    english: ["isn't it?", "right?", "aren't you?"],
    expression_type: "formulaic_phrase",
    chapter_number: 2,
    page_printed: 19,
    tags: ["question_tag", "confirmation"],
  },
  {
    canonical_form: "ne ... pas",
    english: ["not"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "standard"],
  },
  {
    canonical_form: "ne ... jamais",
    english: ["never"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "frequency"],
  },
  {
    canonical_form: "ne ... plus",
    english: ["no longer", "no more"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "aspect"],
  },
  {
    canonical_form: "ne ... rien",
    english: ["nothing", "not anything"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "indefinite"],
  },
  {
    canonical_form: "ne ... personne",
    english: ["nobody", "no one"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "person"],
  },
  {
    canonical_form: "ne ... que",
    english: ["only", "nothing but"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["restriction", "negation"],
  },
  {
    canonical_form: "ne ... nulle part",
    english: ["nowhere"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "location"],
  },
  {
    canonical_form: "ne ... aucun",
    english: ["not any", "no ... at all", "none"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "determiner"],
  },
  {
    canonical_form: "ne ... ni ... ni",
    english: ["neither ... nor"],
    expression_type: "fixed_expression",
    chapter_number: 2,
    page_printed: 20,
    tags: ["negation", "coordination"],
  },

  // CHAPTER 3: Idiomatic expressions with Avoir & Être
  {
    canonical_form: "avoir faim",
    english: ["to be hungry"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "physiological"],
  },
  {
    canonical_form: "avoir soif",
    english: ["to be thirsty"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "physiological"],
  },
  {
    canonical_form: "avoir chaud",
    english: ["to be warm", "to be hot"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "physiological"],
  },
  {
    canonical_form: "avoir froid",
    english: ["to be cold"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "physiological"],
  },
  {
    canonical_form: "avoir sommeil",
    english: ["to be sleepy"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "physiological"],
  },
  {
    canonical_form: "avoir peur de",
    english: ["to be afraid of"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "emotion"],
  },
  {
    canonical_form: "avoir honte de",
    english: ["to be ashamed of"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "emotion"],
  },
  {
    canonical_form: "avoir besoin de",
    english: ["to need to", "to need"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "necessity"],
  },
  {
    canonical_form: "avoir envie de",
    english: ["to feel like", "to want to"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "desire"],
  },
  {
    canonical_form: "avoir hâte de",
    english: ["to look forward to", "to be eager to"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "anticipation"],
  },
  {
    canonical_form: "avoir raison",
    english: ["to be right"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "cognition"],
  },
  {
    canonical_form: "avoir tort",
    english: ["to be wrong"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "cognition"],
  },
  {
    canonical_form: "avoir l'air de",
    english: ["to seem", "to look like"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "appearance"],
  },
  {
    canonical_form: "avoir lieu",
    english: ["to take place"],
    expression_type: "idiom",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "event"],
  },
  {
    canonical_form: "avoir l'intention de",
    english: ["to intend to", "to plan to"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "intention"],
  },
  {
    canonical_form: "avoir ... ans",
    english: ["to be ... years old"],
    expression_type: "formulaic_phrase",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "age"],
  },
  {
    canonical_form: "avoir du mal à + infinitif",
    english: ["to have a hard time doing", "to struggle to"],
    expression_type: "verb_pattern",
    base_verbs: ["avoir"],
    chapter_number: 3,
    page_printed: 28,
    tags: ["idiom_with_avoir", "difficulty"],
  },
  {
    canonical_form: "être d'accord avec",
    english: ["to agree with"],
    expression_type: "verb_pattern",
    base_verbs: ["être"],
    chapter_number: 3,
    page_printed: 26,
    tags: ["idiom_with_être", "agreement"],
  },
  {
    canonical_form: "être en retard",
    english: ["to be late"],
    expression_type: "idiom",
    base_verbs: ["être"],
    chapter_number: 3,
    page_printed: 26,
    tags: ["idiom_with_être", "time"],
  },
  {
    canonical_form: "être à l'heure",
    english: ["to be on time"],
    expression_type: "idiom",
    base_verbs: ["être"],
    chapter_number: 3,
    page_printed: 26,
    tags: ["idiom_with_être", "time"],
  },
  {
    canonical_form: "être en avance",
    english: ["to be early"],
    expression_type: "idiom",
    base_verbs: ["être"],
    chapter_number: 3,
    page_printed: 26,
    tags: ["idiom_with_être", "time"],
  },
  {
    canonical_form: "être sur le point de + infinitif",
    english: ["to be about to do something"],
    expression_type: "verb_pattern",
    base_verbs: ["être"],
    chapter_number: 3,
    page_printed: 26,
    tags: ["idiom_with_être", "immediate_future"],
  },

  // CHAPTER 4: Aller, Venir, Faire expressions
  {
    canonical_form: "aller + infinitif",
    english: ["to be going to (immediate future)"],
    expression_type: "verb_pattern",
    base_verbs: ["aller"],
    chapter_number: 4,
    page_printed: 35,
    tags: ["future_proche", "verb_pattern"],
  },
  {
    canonical_form: "aller chercher",
    english: ["to go fetch", "to pick up (a person/object)"],
    expression_type: "verb_pattern",
    base_verbs: ["aller", "chercher"],
    chapter_number: 4,
    page_printed: 35,
    tags: ["collocation", "motion"],
  },
  {
    canonical_form: "s'en aller",
    english: ["to leave", "to go away"],
    expression_type: "idiom",
    base_verbs: ["aller"],
    chapter_number: 4,
    page_printed: 35,
    tags: ["pronominal", "idiom"],
  },
  {
    canonical_form: "venir de + infinitif",
    english: ["to have just done something (immediate past)"],
    expression_type: "verb_pattern",
    base_verbs: ["venir"],
    chapter_number: 4,
    page_printed: 36,
    tags: ["passe_recent", "verb_pattern"],
  },
  {
    canonical_form: "venir chercher",
    english: ["to come fetch", "to come pick up (someone/something)"],
    expression_type: "verb_pattern",
    base_verbs: ["venir", "chercher"],
    chapter_number: 4,
    page_printed: 36,
    tags: ["collocation", "motion"],
  },
  {
    canonical_form: "faire la cuisine",
    english: ["to cook", "to do the cooking"],
    expression_type: "collocation",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "household"],
  },
  {
    canonical_form: "faire la vaisselle",
    english: ["to do the dishes"],
    expression_type: "collocation",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "household"],
  },
  {
    canonical_form: "faire le ménage",
    english: ["to do the housework", "to clean up"],
    expression_type: "collocation",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "household"],
  },
  {
    canonical_form: "faire les courses",
    english: ["to go grocery shopping", "to run errands"],
    expression_type: "collocation",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "daily_life"],
  },
  {
    canonical_form: "faire du sport",
    english: ["to play sports", "to exercise"],
    expression_type: "collocation",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "sports"],
  },
  {
    canonical_form: "faire attention à",
    english: ["to pay attention to", "to watch out for"],
    expression_type: "verb_pattern",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "caution"],
  },
  {
    canonical_form: "faire semblant de + infinitif",
    english: ["to pretend to do"],
    expression_type: "verb_pattern",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "pretense"],
  },
  {
    canonical_form: "faire de son mieux",
    english: ["to do one's best"],
    expression_type: "idiom",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "effort"],
  },
  {
    canonical_form: "faire partie de",
    english: ["to belong to", "to be part of"],
    expression_type: "verb_pattern",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "membership"],
  },
  {
    canonical_form: "faire la connaissance de",
    english: ["to meet (someone for the first time)", "to make the acquaintance of"],
    expression_type: "verb_pattern",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 39,
    tags: ["idiom_with_faire", "social"],
  },
  {
    canonical_form: "faire + infinitif",
    english: ["to have something done", "to cause to do (causative)"],
    expression_type: "verb_pattern",
    base_verbs: ["faire"],
    chapter_number: 4,
    page_printed: 40,
    tags: ["causative", "grammar_structure"],
  },

  // CHAPTER 5: Devoir, Il y a, Il s'agit de
  {
    canonical_form: "il y a",
    english: ["there is", "there are", "ago (with time)"],
    expression_type: "fixed_expression",
    base_verbs: ["avoir"],
    chapter_number: 5,
    page_printed: 44,
    tags: ["impersonal", "essential"],
  },
  {
    canonical_form: "il s'agit de",
    english: ["it is a matter of", "it's about", "it concerns"],
    expression_type: "verb_pattern",
    base_verbs: ["agir"],
    chapter_number: 5,
    page_printed: 45,
    tags: ["impersonal", "topic"],
  },

  // CHAPTER 6: Pronominal expressions
  {
    canonical_form: "se dépêcher de + infinitif",
    english: ["to hurry to do"],
    expression_type: "verb_pattern",
    base_verbs: ["se dépêcher"],
    chapter_number: 6,
    page_printed: 50,
    tags: ["pronominal", "speed"],
  },
  {
    canonical_form: "se souvenir de",
    english: ["to remember", "to recall"],
    expression_type: "verb_pattern",
    base_verbs: ["se souvenir"],
    chapter_number: 6,
    page_printed: 50,
    tags: ["pronominal", "memory"],
  },
  {
    canonical_form: "se rendre compte de",
    english: ["to realize"],
    expression_type: "verb_pattern",
    base_verbs: ["se rendre"],
    chapter_number: 6,
    page_printed: 50,
    tags: ["pronominal", "cognition"],
  },
  {
    canonical_form: "s'intéresser à",
    english: ["to be interested in"],
    expression_type: "verb_pattern",
    base_verbs: ["s'intéresser"],
    chapter_number: 6,
    page_printed: 50,
    tags: ["pronominal", "interest"],
  },
  {
    canonical_form: "s'occuper de",
    english: ["to take care of", "to attend to"],
    expression_type: "verb_pattern",
    base_verbs: ["s'occuper"],
    chapter_number: 6,
    page_printed: 50,
    tags: ["pronominal", "responsibility"],
  },

  // CHAPTER 13: Subjunctive triggers
  {
    canonical_form: "il faut que + subjonctif",
    english: ["it is necessary that", "one must"],
    expression_type: "sentence_starter",
    base_verbs: ["falloir"],
    mood_governance: { following_clause_mood: "subjunctive", notes: "Requires subjunctive in subordinate clause." },
    chapter_number: 13,
    page_printed: 106,
    tags: ["subjunctive_trigger", "impersonal_necessity"],
  },
  {
    canonical_form: "vouloir que + subjonctif",
    english: ["to want that (someone does something)"],
    expression_type: "verb_pattern",
    base_verbs: ["vouloir"],
    mood_governance: { following_clause_mood: "subjunctive", notes: "Expresses volition, requiring subjunctive." },
    chapter_number: 13,
    page_printed: 106,
    tags: ["subjunctive_trigger", "volition"],
  },
  {
    canonical_form: "douter que + subjonctif",
    english: ["to doubt that"],
    expression_type: "verb_pattern",
    base_verbs: ["douter"],
    mood_governance: { following_clause_mood: "subjunctive", notes: "Expresses doubt, requiring subjunctive." },
    chapter_number: 13,
    page_printed: 107,
    tags: ["subjunctive_trigger", "doubt"],
  },
  {
    canonical_form: "bien que + subjonctif",
    english: ["although", "even though"],
    expression_type: "connector",
    mood_governance: { following_clause_mood: "subjunctive", notes: "Conjunction of concession requiring subjunctive." },
    chapter_number: 13,
    page_printed: 108,
    tags: ["subjunctive_trigger", "conjunction", "concession"],
  },
  {
    canonical_form: "pour que + subjonctif",
    english: ["so that", "in order that"],
    expression_type: "connector",
    mood_governance: { following_clause_mood: "subjunctive", notes: "Purpose conjunction requiring subjunctive." },
    chapter_number: 13,
    page_printed: 108,
    tags: ["subjunctive_trigger", "conjunction", "purpose"],
  },
  {
    canonical_form: "avant que + subjonctif",
    english: ["before (someone does something)"],
    expression_type: "connector",
    mood_governance: { following_clause_mood: "subjunctive", notes: "Temporal conjunction requiring subjunctive." },
    chapter_number: 13,
    page_printed: 108,
    tags: ["subjunctive_trigger", "conjunction", "time"],
  },
  {
    canonical_form: "sans que + subjonctif",
    english: ["without (someone doing something)"],
    expression_type: "connector",
    mood_governance: { following_clause_mood: "subjunctive", notes: "Conjunction requiring subjunctive." },
    chapter_number: 13,
    page_printed: 108,
    tags: ["subjunctive_trigger", "conjunction"],
  },
  {
    canonical_form: "à condition que + subjonctif",
    english: ["on condition that", "provided that"],
    expression_type: "connector",
    mood_governance: { following_clause_mood: "subjunctive", notes: "Conditional conjunction requiring subjunctive." },
    chapter_number: 13,
    page_printed: 108,
    tags: ["subjunctive_trigger", "conjunction", "condition"],
  },
  {
    canonical_form: "à moins que + subjonctif",
    english: ["unless"],
    expression_type: "connector",
    mood_governance: { following_clause_mood: "subjunctive", notes: "Conjunction requiring subjunctive (often with ne explétif)." },
    chapter_number: 13,
    page_printed: 108,
    tags: ["subjunctive_trigger", "conjunction", "condition"],
  },

  // CHAPTER 14: Comprehensive Verbs Followed by Prepositions (à / de / direct)
  // Verbs followed by à
  { canonical_form: "s'accoutumer à + infinitif", english: ["to get accustomed to doing"], expression_type: "verb_pattern", base_verbs: ["accoutumer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "aider à + infinitif", english: ["to help to do"], expression_type: "verb_pattern", base_verbs: ["aider"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "s'amuser à + infinitif", english: ["to enjoy doing", "to amuse oneself by doing"], expression_type: "verb_pattern", base_verbs: ["amuser"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "apprendre à + infinitif", english: ["to learn to do", "to teach how to do"], expression_type: "verb_pattern", base_verbs: ["apprendre"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "arriver à + infinitif", english: ["to manage to do", "to succeed in doing"], expression_type: "verb_pattern", base_verbs: ["arriver"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "aspirer à + infinitif", english: ["to aspire to do"], expression_type: "verb_pattern", base_verbs: ["aspirer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "s'attendre à + infinitif", english: ["to expect to do"], expression_type: "verb_pattern", base_verbs: ["attendre"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "autoriser à + infinitif", english: ["to authorize to do"], expression_type: "verb_pattern", base_verbs: ["autoriser"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "chercher à + infinitif", english: ["to try to do", "to attempt to"], expression_type: "verb_pattern", base_verbs: ["chercher"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "commencer à + infinitif", english: ["to start to do", "to begin doing"], expression_type: "verb_pattern", base_verbs: ["commencer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "consentir à + infinitif", english: ["to agree to do", "to consent to"], expression_type: "verb_pattern", base_verbs: ["consentir"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "continuer à + infinitif", english: ["to continue to do", "to keep on doing"], expression_type: "verb_pattern", base_verbs: ["continuer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "se décider à + infinitif", english: ["to make up one's mind to do"], expression_type: "verb_pattern", base_verbs: ["décider"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "encourager à + infinitif", english: ["to encourage to do"], expression_type: "verb_pattern", base_verbs: ["encourager"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "s'habituer à + infinitif", english: ["to get used to doing"], expression_type: "verb_pattern", base_verbs: ["habituer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "hésiter à + infinitif", english: ["to hesitate to do"], expression_type: "verb_pattern", base_verbs: ["hésiter"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "inviter à + infinitif", english: ["to invite to do"], expression_type: "verb_pattern", base_verbs: ["inviter"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "se mettre à + infinitif", english: ["to set about doing", "to start doing"], expression_type: "verb_pattern", base_verbs: ["mettre"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "obliger à + infinitif", english: ["to oblige to do", "to compel to do"], expression_type: "verb_pattern", base_verbs: ["obliger"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "parvenir à + infinitif", english: ["to succeed in doing", "to manage to do"], expression_type: "verb_pattern", base_verbs: ["parvenir"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "persister à + infinitif", english: ["to persist in doing"], expression_type: "verb_pattern", base_verbs: ["persister"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "renoncer à + infinitif", english: ["to give up doing"], expression_type: "verb_pattern", base_verbs: ["renoncer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "réussir à + infinitif", english: ["to succeed in doing"], expression_type: "verb_pattern", base_verbs: ["réussir"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "servir à + infinitif", english: ["to serve to do", "to be used for doing"], expression_type: "verb_pattern", base_verbs: ["servir"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "songer à + infinitif", english: ["to think of doing", "to dream of doing"], expression_type: "verb_pattern", base_verbs: ["songer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "tenir à + infinitif", english: ["to be keen on doing", "to insist on doing"], expression_type: "verb_pattern", base_verbs: ["tenir"], chapter_number: 14, page_printed: 122 },

  // Verbs followed by de
  { canonical_form: "accepter de + infinitif", english: ["to accept to do", "to agree to do"], expression_type: "verb_pattern", base_verbs: ["accepter"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "accuser de + infinitif", english: ["to accuse of doing"], expression_type: "verb_pattern", base_verbs: ["accuser"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "s'arrêter de + infinitif", english: ["to stop doing"], expression_type: "verb_pattern", base_verbs: ["arrêter"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "cesser de + infinitif", english: ["to cease doing", "to stop doing"], expression_type: "verb_pattern", base_verbs: ["cesser"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "choisir de + infinitif", english: ["to choose to do"], expression_type: "verb_pattern", base_verbs: ["choisir"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "conseiller de + infinitif", english: ["to advise to do"], expression_type: "verb_pattern", base_verbs: ["conseiller"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "se contenter de + infinitif", english: ["to content oneself with doing"], expression_type: "verb_pattern", base_verbs: ["contenter"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "convaincre de + infinitif", english: ["to convince to do"], expression_type: "verb_pattern", base_verbs: ["convaincre"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "craindre de + infinitif", english: ["to fear doing", "to be afraid to do"], expression_type: "verb_pattern", base_verbs: ["craindre"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "défendre de + infinitif", english: ["to forbid to do"], expression_type: "verb_pattern", base_verbs: ["défendre"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "demander de + infinitif", english: ["to ask to do"], expression_type: "verb_pattern", base_verbs: ["demander"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "s'efforcer de + infinitif", english: ["to try hard to do", "to strive to do"], expression_type: "verb_pattern", base_verbs: ["efforcer"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "empêcher de + infinitif", english: ["to prevent from doing"], expression_type: "verb_pattern", base_verbs: ["empêcher"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "s'empêcher de + infinitif", english: ["to refrain from doing", "to help doing"], expression_type: "verb_pattern", base_verbs: ["empêcher"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "envisager de + infinitif", english: ["to contemplate doing", "to consider doing"], expression_type: "verb_pattern", base_verbs: ["envisager"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "essayer de + infinitif", english: ["to try to do"], expression_type: "verb_pattern", base_verbs: ["essayer"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "éviter de + infinitif", english: ["to avoid doing"], expression_type: "verb_pattern", base_verbs: ["éviter"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "s'excuser de + infinitif", english: ["to apologize for doing"], expression_type: "verb_pattern", base_verbs: ["excuser"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "feindre de + infinitif", english: ["to feign doing", "to pretend to do"], expression_type: "verb_pattern", base_verbs: ["feindre"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "finir de + infinitif", english: ["to finish doing"], expression_type: "verb_pattern", base_verbs: ["finir"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "interdire de + infinitif", english: ["to forbid to do"], expression_type: "verb_pattern", base_verbs: ["interdire"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "menacer de + infinitif", english: ["to threaten to do"], expression_type: "verb_pattern", base_verbs: ["menacer"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "mériter de + infinitif", english: ["to deserve to do"], expression_type: "verb_pattern", base_verbs: ["mériter"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "négliger de + infinitif", english: ["to neglect to do"], expression_type: "verb_pattern", base_verbs: ["négliger"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "offrir de + infinitif", english: ["to offer to do"], expression_type: "verb_pattern", base_verbs: ["offrir"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "oublier de + infinitif", english: ["to forget to do"], expression_type: "verb_pattern", base_verbs: ["oublier"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "pardonner de + infinitif", english: ["to forgive for doing"], expression_type: "verb_pattern", base_verbs: ["pardonner"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "permettre de + infinitif", english: ["to allow to do"], expression_type: "verb_pattern", base_verbs: ["permettre"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "persuader de + infinitif", english: ["to persuade to do"], expression_type: "verb_pattern", base_verbs: ["persuader"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "se plaindre de + infinitif", english: ["to complain about doing"], expression_type: "verb_pattern", base_verbs: ["plaindre"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "presser de + infinitif", english: ["to urge to do"], expression_type: "verb_pattern", base_verbs: ["presser"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "promettre de + infinitif", english: ["to promise to do"], expression_type: "verb_pattern", base_verbs: ["promettre"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "proposer de + infinitif", english: ["to suggest doing", "to propose to do"], expression_type: "verb_pattern", base_verbs: ["proposer"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "refuser de + infinitif", english: ["to refuse to do"], expression_type: "verb_pattern", base_verbs: ["refuser"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "regretter de + infinitif", english: ["to regret doing"], expression_type: "verb_pattern", base_verbs: ["regretter"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "se réjouir de + infinitif", english: ["to rejoice at doing"], expression_type: "verb_pattern", base_verbs: ["réjouir"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "remercier de + infinitif", english: ["to thank for doing"], expression_type: "verb_pattern", base_verbs: ["remercier"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "reprocher de + infinitif", english: ["to reproach for doing"], expression_type: "verb_pattern", base_verbs: ["reprocher"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "risquer de + infinitif", english: ["to risk doing"], expression_type: "verb_pattern", base_verbs: ["risquer"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "supplier de + infinitif", english: ["to beg to do"], expression_type: "verb_pattern", base_verbs: ["supplier"], chapter_number: 14, page_printed: 123 },
  { canonical_form: "tenter de + infinitif", english: ["to attempt to do"], expression_type: "verb_pattern", base_verbs: ["tenter"], chapter_number: 14, page_printed: 123 },

  // Verbs + person + preposition + infinitive constructions
  { canonical_form: "demander à qqn de + infinitif", english: ["to ask someone to do something"], expression_type: "verb_pattern", base_verbs: ["demander"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "conseiller à qqn de + infinitif", english: ["to advise someone to do something"], expression_type: "verb_pattern", base_verbs: ["conseiller"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "dire à qqn de + infinitif", english: ["to tell someone to do something"], expression_type: "verb_pattern", base_verbs: ["dire"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "ordonner à qqn de + infinitif", english: ["to order someone to do something"], expression_type: "verb_pattern", base_verbs: ["ordonner"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "permettre à qqn de + infinitif", english: ["to allow someone to do something"], expression_type: "verb_pattern", base_verbs: ["permettre"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "promettre à qqn de + infinitif", english: ["to promise someone to do something"], expression_type: "verb_pattern", base_verbs: ["promettre"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "interdire à qqn de + infinitif", english: ["to forbid someone from doing something"], expression_type: "verb_pattern", base_verbs: ["interdire"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "défendre à qqn de + infinitif", english: ["to forbid someone to do something"], expression_type: "verb_pattern", base_verbs: ["défendre"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "reprocher à qqn de + infinitif", english: ["to blame someone for doing something"], expression_type: "verb_pattern", base_verbs: ["reprocher"], chapter_number: 14, page_printed: 115 },
  { canonical_form: "aider qqn à + infinitif", english: ["to help someone to do something"], expression_type: "verb_pattern", base_verbs: ["aider"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "inviter qqn à + infinitif", english: ["to invite someone to do something"], expression_type: "verb_pattern", base_verbs: ["inviter"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "encourager qqn à + infinitif", english: ["to encourage someone to do something"], expression_type: "verb_pattern", base_verbs: ["encourager"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "obliger qqn à + infinitif", english: ["to oblige someone to do something"], expression_type: "verb_pattern", base_verbs: ["obliger"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "forcer qqn à + infinitif", english: ["to force someone to do something"], expression_type: "verb_pattern", base_verbs: ["forcer"], chapter_number: 14, page_printed: 122 },
  { canonical_form: "autoriser qqn à + infinitif", english: ["to authorize someone to do something"], expression_type: "verb_pattern", base_verbs: ["autoriser"], chapter_number: 14, page_printed: 122 },

  // CHAPTER 19: Imperative formulaic expressions
  { canonical_form: "allons-y", english: ["let's go"], expression_type: "formulaic_phrase", base_verbs: ["aller"], chapter_number: 19, page_printed: 147 },
  { canonical_form: "vas-y", english: ["go ahead", "go on"], expression_type: "formulaic_phrase", base_verbs: ["aller"], chapter_number: 19, page_printed: 147 },
  { canonical_form: "faisons attention", english: ["let's be careful", "let's pay attention"], expression_type: "formulaic_phrase", base_verbs: ["faire"], chapter_number: 19, page_printed: 147 },
  { canonical_form: "prenez garde à", english: ["watch out for", "beware of"], expression_type: "formulaic_phrase", base_verbs: ["prendre"], chapter_number: 19, page_printed: 147 },

  // CHAPTER 22: Comparatives & Superlatives
  { canonical_form: "plus ... que", english: ["more ... than"], expression_type: "fixed_expression", chapter_number: 22, page_printed: 187, tags: ["comparative"] },
  { canonical_form: "moins ... que", english: ["less ... than"], expression_type: "fixed_expression", chapter_number: 22, page_printed: 187, tags: ["comparative"] },
  { canonical_form: "aussi ... que", english: ["as ... as"], expression_type: "fixed_expression", chapter_number: 22, page_printed: 187, tags: ["comparative"] },
  { canonical_form: "autant de ... que", english: ["as much ... as", "as many ... as"], expression_type: "fixed_expression", chapter_number: 22, page_printed: 187, tags: ["comparative_quantity"] },
  { canonical_form: "le plus ...", english: ["the most ..."], expression_type: "fixed_expression", chapter_number: 22, page_printed: 188, tags: ["superlative"] },
  { canonical_form: "le moins ...", english: ["the least ..."], expression_type: "fixed_expression", chapter_number: 22, page_printed: 188, tags: ["superlative"] },
  { canonical_form: "de plus en plus", english: ["more and more"], expression_type: "fixed_expression", chapter_number: 22, page_printed: 188, tags: ["degree"] },
  { canonical_form: "de moins en moins", english: ["less and less"], expression_type: "fixed_expression", chapter_number: 22, page_printed: 188, tags: ["degree"] },

  // CHAPTER 23: Prepositional locutions
  { canonical_form: "à côté de", english: ["next to", "beside"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "en face de", english: ["opposite", "across from"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "au milieu de", english: ["in the middle of"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "au bout de", english: ["at the end of"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "près de", english: ["near", "close to"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "loin de", english: ["far from"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "autour de", english: ["around"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "au-dessus de", english: ["above", "over"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "au-dessous de", english: ["below", "underneath"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "le long de", english: ["along"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "à travers", english: ["through", "across"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "location"] },
  { canonical_form: "grâce à", english: ["thanks to"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "cause"] },
  { canonical_form: "à cause de", english: ["because of", "due to"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "cause"] },
  { canonical_form: "au lieu de", english: ["instead of"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution"] },
  { canonical_form: "en dépit de", english: ["in spite of", "despite"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "concession"] },
  { canonical_form: "quant à", english: ["as for", "regarding"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "topic"] },
  { canonical_form: "en ce qui concerne", english: ["as far as ... is concerned", "regarding"], expression_type: "fixed_expression", chapter_number: 23, page_printed: 195, tags: ["prepositional_locution", "topic"] },

  // CHAPTER 24: Relatives
  { canonical_form: "ce qui", english: ["what", "which (subject)"], expression_type: "fixed_expression", chapter_number: 24, page_printed: 204, tags: ["relative_pronoun"] },
  { canonical_form: "ce que", english: ["what", "which (direct object)"], expression_type: "fixed_expression", chapter_number: 24, page_printed: 204, tags: ["relative_pronoun"] },
  { canonical_form: "ce dont", english: ["what", "of which"], expression_type: "fixed_expression", chapter_number: 24, page_printed: 204, tags: ["relative_pronoun"] },
  { canonical_form: "ce à quoi", english: ["what", "to which"], expression_type: "fixed_expression", chapter_number: 24, page_printed: 204, tags: ["relative_pronoun"] },

  // CHAPTER 25: Adverbial expressions of time, frequency, location
  { canonical_form: "tout de suite", english: ["immediately", "right away"], expression_type: "fixed_expression", chapter_number: 25, page_printed: 215, tags: ["time", "adverbial"] },
  { canonical_form: "tout à coup", english: ["all of a sudden", "suddenly"], expression_type: "fixed_expression", chapter_number: 25, page_printed: 215, tags: ["time", "adverbial"] },
  { canonical_form: "tout à l'heure", english: ["earlier today", "in a little while"], expression_type: "fixed_expression", chapter_number: 25, page_printed: 215, tags: ["time", "adverbial"] },
  { canonical_form: "de temps en temps", english: ["from time to time", "now and then"], expression_type: "fixed_expression", chapter_number: 25, page_printed: 215, tags: ["frequency", "adverbial"] },
  { canonical_form: "d'ailleurs", english: ["moreover", "besides", "by the way"], expression_type: "connector", chapter_number: 25, page_printed: 216, tags: ["connector", "transition"] },
  { canonical_form: "en fait", english: ["in fact", "actually"], expression_type: "connector", chapter_number: 25, page_printed: 216, tags: ["connector", "transition"] },
  { canonical_form: "en effet", english: ["indeed", "in fact"], expression_type: "connector", chapter_number: 25, page_printed: 216, tags: ["connector", "transition"] },

  // CHAPTER 27: Conjunctions and sentence connectors
  { canonical_form: "donc", english: ["therefore", "so"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "consequence"] },
  { canonical_form: "alors", english: ["then", "so"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "consequence"] },
  { canonical_form: "pourtant", english: ["yet", "however"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "opposition"] },
  { canonical_form: "cependant", english: ["however", "nevertheless"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "opposition"] },
  { canonical_form: "néanmoins", english: ["nevertheless", "nonetheless"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "opposition"] },
  { canonical_form: "en revanche", english: ["on the other hand", "in contrast"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "opposition"] },
  { canonical_form: "par contre", english: ["on the other hand"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "opposition"] },
  { canonical_form: "par conséquent", english: ["consequently", "as a result"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "consequence"] },
  { canonical_form: "ainsi", english: ["thus", "in this way"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "consequence"] },
  { canonical_form: "puisque", english: ["since", "as", "given that"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "cause"] },
  { canonical_form: "étant donné que", english: ["given that", "seeing that"], expression_type: "connector", chapter_number: 27, page_printed: 230, tags: ["connector", "cause"] },
  { canonical_form: "soit ... soit", english: ["either ... or"], expression_type: "connector", chapter_number: 27, page_printed: 231, tags: ["connector", "alternative"] },
];

export function buildEnrichedExpressions(): Expression[] {
  return MASTER_EXPRESSION_SPECS.map((spec) => {
    const id = makeExpressionId(spec.canonical_form);
    const baseVerbIds = (spec.base_verbs || []).map((v) => makeVerbId(v));
    const relatedVocabIds = (spec.related_vocab || []).map((v) => makeVocabId(v));

    return {
      id,
      type: "expression" as const,
      expression_type: spec.expression_type,
      canonical_form: spec.canonical_form,
      display_form: spec.display_form || spec.canonical_form,
      english: spec.english,
      base_verb_ids: baseVerbIds,
      related_vocabulary_ids: relatedVocabIds,
      productive: true,
      collocation_strength: "strong",
      pattern: spec.pattern || null,
      pattern_slots: [],
      complement_structure: null,
      mood_governance: spec.mood_governance
        ? {
            following_clause_mood: spec.mood_governance.following_clause_mood || null,
            notes: spec.mood_governance.notes || null,
          }
        : null,
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: spec.usage_notes || [],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [
        {
          source_type: "book",
          chapter_number: spec.chapter_number,
          page_printed: spec.page_printed,
          context_type: "expression_list",
        },
      ],
      relations: {
        verbs: baseVerbIds,
        vocabulary: relatedVocabIds,
      },
      tags: spec.tags || ["expression", "construction"],
    };
  });
}
