/** Independent read-only auditor. It does not import or execute master_merge.ts. */
import * as fs from 'fs';
import * as path from 'path';
import { createHash } from 'crypto';
const root=path.resolve(__dirname,'..'), src=path.join(root,'bookdata/json'), rec=path.join(root,'data/reconciliation');
const read=(p:string):any=>JSON.parse(fs.readFileSync(p,'utf8'));
const norm=(v:any)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const count=(xs:any[],f:(x:any)=>string):Record<string,number>=>{const m=new Map<string,number>();for(const x of xs)m.set(f(x),(m.get(f(x))??0)+1);return Object.fromEntries(m) as Record<string,number>};
const files=[...Array.from({length:27},(_,i)=>`${i+1}.json`),'English-Frenchglossary.json','French-Englishglossary.json','verb_table.json','answer_key.json'];
const DISP=['REPRESENTED_ENTITY','REPRESENTED_RELATIONSHIP','REPRESENTED_ANSWER','EXPLICITLY_REJECTED_WITH_JUSTIFICATION','EXACT_DUPLICATE','NOT_APPLICABLE','UNACCOUNTED'];
type E={id:string;file:string;kind:string;value:any;owner?:string;field?:string;target?:string}; const ev:E[]=[]; const ids=new Set<string>();
const add=(file:string,kind:string,value:any,suffix:any=value?.id,extra:Partial<E>={})=>{if(suffix==null)return;ev.push({id:`${file}::${suffix}`,file,kind,value,...extra});if(value?.id)ids.add(value.id)};
const rels=(v:any)=>{const out:{field:string,target:string}[]=[];const walk=(x:any,p='')=>{if(!x||typeof x!=='object')return;for(const[k,c]of Object.entries(x)){const f=p?`${p}.${k}`:k;if((k.endsWith('_ids')||k==='tense_id'||k==='verb_id'||p.startsWith('relations'))&&(typeof c==='string'||Array.isArray(c))){for(const t of(Array.isArray(c)?c:[c]))if(typeof t==='string')out.push({field:f,target:t})}if(k==='relations')walk(c,f)}};walk(v);return out};
const attKey=(a:any)=>[a.chapter_number,a.chapter_id,a.section_id,a.page_printed,a.page_pdf,a.context_type,a.exercise_id,a.question_number,a.source_anchor,a.source_text].map(norm).join('|');
const chapters:any[]=[];const entityKeys=['sections','concepts','grammar_rules','verbs','conjugations','expressions','vocabulary','examples','exercises'];
for(let i=1;i<=27;i++){const file=`${i}.json`,d=read(path.join(src,file));chapters.push(d);add(file,'entity',d.chapter);for(const key of entityKeys)for(const x of d[key]??[]){add(file,'entity',x);for(const[a,at]of(x.attestations??[]).entries())add(file,'attestation',at,`${x.id}::attestation::${a}`,{owner:x.id});for(const[r,z]of rels(x).entries())add(file,'relationship',z,`${x.id}::relationship::${z.field}::${r}`,{owner:x.id,field:z.field,target:z.target});if(key==='exercises')for(const q of x.questions??[]){add(file,'question',q);for(const[r,z]of rels(q).entries())add(file,'relationship',z,`${q.id}::relationship::${z.field}::${r}`,{owner:q.id,field:z.field,target:z.target})}}}
for(const file of ['English-Frenchglossary.json','French-Englishglossary.json'])for(const x of read(path.join(src,file)).entries??[]){add(file,'glossary_row',x);for(const[a,at]of(x.provenance??[]).entries())add(file,'attestation',at,`${x.id}::provenance::${a}`,{owner:x.id})}
const vt=read(path.join(src,'verb_table.json'));for(const x of vt.tables??[])add('verb_table.json','verb_table',x);for(const x of vt.rows??[]){add('verb_table.json','verb_table_row',x);for(const[i,t]of(x.other_tenses??[]).entries())add('verb_table.json','verb_table_form',t,`${x.id}::form::${i}`,{owner:x.id});for(const[i,a]of(x.provenance??[]).entries())add('verb_table.json','attestation',a,`${x.id}::provenance::${i}`,{owner:x.id})}
const ak=read(path.join(src,'answer_key.json'));for(const x of ak.exercises??[]){add('answer_key.json','answer_exercise',x);for(const a of x.answers??[])add('answer_key.json','answer',{...a,exercise_code:x.exercise_code,all_answers:x.answers.map((z:any)=>z.answer)})}
const master=read(path.join(root,'data/final/french_grammar_master.preview.json'));const cols=['chapters','sections','concepts','tenses','grammar_rules','verbs','conjugations','expressions','vocabulary','examples','exercises'];const byId=new Map<string,any>();for(const c of cols)for(const x of master[c]??[]){byId.set(x.id,x);if(c==='exercises')for(const q of x.questions??[])byId.set(q.question_id,q)}const glossaryRows=new Map(['English-Frenchglossary.json','French-Englishglossary.json'].flatMap(file=>(read(path.join(src,file)).entries??[]).map((row:any)=>[row.id,row])));
const manifest=read(path.join(rec,'authoritative-relationship-manifest.json'));const rejected=new Map((manifest.rejected_pointers??[]).map((x:any)=>[`${x.from}|${x.field}|${x.dangling_target}`,x]));const reconstructed=new Set((read(path.join(rec,'authoritative-target-reconstruction-manifest.json')).targets??[]).map((x:any)=>x.canonical_id));
// Glossary headwords omit source-side articles and expression slot notation.  Compare
// those source-neutral canonical forms together with an English sense, never by ID.
const glossaryForm=(v:any)=>norm(String(v??'').replace(/^\s*(?:un\(e\)|un|une|le|la|les|l')\s+/i,'').replace(/\s*\[.*$/,'').trim());
const owner=(e:E)=>{if(e.owner&&byId.has(e.owner))return byId.get(e.owner);if(e.value?.id&&byId.has(e.value.id))return byId.get(e.value.id);const glossary=e.kind==='glossary_row'?e.value:glossaryRows.get(e.owner??'');if(glossary){const french=new Set([glossary.canonical_french,...(glossary.french??[])].map(glossaryForm)),english=new Set([glossary.canonical_english,...(glossary.english??[])].map(norm)),candidates=[...(master.verbs??[]),...(master.vocabulary??[]),...(master.expressions??[])].filter((x:any)=>french.has(glossaryForm(x.infinitive??x.canonical_form??x.display_form))&&(x.english??[]).some((z:string)=>english.has(norm(z))));const anchor=`${e.file}:${glossary.id}`;return candidates.find((x:any)=>(x.attestations??[]).some((a:any)=>a.source_anchor===anchor))??candidates[0];}if(e.file==='verb_table.json'||e.kind.startsWith('verb_table'))return(master.verbs??[]).find((x:any)=>norm(x.infinitive)===norm(e.value.infinitive??vt.rows?.find((r:any)=>r.id===e.owner)?.infinitive));};
const attEquivalent=(source:any,canonical:any,masterOwner:any)=>{if((canonical??[]).some((a:any)=>attKey(a)===attKey(source)))return true;const text=norm(source.source_text);const same=(a:any,b:any)=>norm(a)===norm(b);if(text&&(canonical??[]).some((a:any)=>same(a.chapter_number,source.chapter_number)&&same(a.page_printed,source.page_printed)&&same(a.section_id,source.section_id)&&same(a.exercise_id,source.exercise_id)&&norm(a.notes).includes(text)))return true;return !!(masterOwner?.source&&source.source_text&&norm(source.source_text)===norm(masterOwner.title)&&same(masterOwner.source.page_start_printed,source.page_printed))};
const disp=(e:E):string=>{if(e.kind==='relationship'){const o=owner(e);if(rels(o).some(z=>z.target===e.target||norm(z.target)===norm(e.target)))return'REPRESENTED_RELATIONSHIP';return rejected.has(`${e.owner}|${e.field}|${e.target}`)?'EXPLICITLY_REJECTED_WITH_JUSTIFICATION':'UNACCOUNTED'}if(e.kind==='attestation'){const o=owner(e);return attEquivalent(e.value,o?.attestations,o)?'REPRESENTED_ENTITY':'UNACCOUNTED'}if(e.kind==='question')return byId.has(e.value.id)?'REPRESENTED_ANSWER':'UNACCOUNTED';if(e.kind==='answer'){const x=(master.exercises??[]).find((z:any)=>norm(z.exercise_number)===norm(e.value.exercise_code));const direct=(x?.questions??[]).some((q:any)=>String(q.question_id).endsWith(`_${e.value.question_number}`)&&norm(q.answer)===norm(e.value.answer));const structural=(x?.questions??[]).some((q:any)=>norm(q.answer)===norm(e.value.all_answers.join(' / ')));return direct||structural?'REPRESENTED_ANSWER':'UNACCOUNTED'}if(e.kind==='answer_exercise')return(master.exercises??[]).some((x:any)=>norm(x.exercise_number)===norm(e.value.exercise_code))?'REPRESENTED_ANSWER':'UNACCOUNTED';if(e.kind==='verb_table')return'NOT_APPLICABLE';return owner(e)||byId.has(e.value?.id)?'REPRESENTED_ENTITY':'UNACCOUNTED'};
const dispositions=ev.map(e=>({evidence_id:e.id,file:e.file,kind:e.kind,owner_id:e.owner??null,disposition:disp(e)}));const relationshipEvidence=read(path.join(rec,'authoritative-relationship-evidence-reconciliation.json'));const relationshipUnaccounted=(relationshipEvidence.occurrences??[]).filter((x:any)=>x.disposition==='UNACCOUNTED');const nonRelationshipUnaccounted=dispositions.filter(x=>x.disposition==='UNACCOUNTED'&&x.kind!=='relationship');const unaccounted=[...nonRelationshipUnaccounted,...relationshipUnaccounted.map((x:any)=>({evidence_id:x.evidence_id,file:x.source_file,kind:'relationship',owner_id:x.owner_id,disposition:'UNACCOUNTED'}))];const dcounts=Object.assign(Object.fromEntries(DISP.map(x=>[x,0])),count(dispositions.filter(x=>x.kind!=='relationship'),x=>x.disposition));dcounts.UNACCOUNTED=unaccounted.length;dcounts.EXPLICITLY_REJECTED_WITH_JUSTIFICATION+=(relationshipEvidence.occurrences??[]).filter((x:any)=>x.disposition==='EXPLICITLY_REJECTED_WITH_JUSTIFICATION').length;
const mergePath=path.join(root,'scripts/master_merge.ts'),merge=fs.readFileSync(mergePath,'utf8');const tautological=/sourceEvidenceUniverse\.add\([^\n]+\)[\s\S]{0,180}?masterRepresentedEvidence\.add\(/.test(merge);
const pointerClass=(p:any)=>{const t=String(p.dangling_target);if(String(p.reason).includes('No authoritative target entity exists'))return'EXPLICITLY_REJECTED_WITH_JUSTIFICATION';if(reconstructed.has(t))return'SOURCE_TARGET_RECONSTRUCTION_REQUIRED';if(byId.has(t)||Array.from(byId.keys()).some(id=>norm(id)===norm(t)))return'CANONICAL_ALIAS_REQUIRED';const off=t.match(/^example_ch(43|49)_(\d+)$/);if(off){const c=`example_ch${off[1]==='43'?'05':'06'}_${off[2].padStart(2,'0')}`;if(ids.has(c)||byId.has(c))return'SOURCE_TARGET_EXISTS_UNDER_DIFFERENT_ID'}const n=t.match(/^example_ch27_(\d{3})$/);if(n){const c=`example_ch27_${String(Number(n[1])-20).padStart(3,'0')}`;if(ids.has(c)||byId.has(c))return'SOURCE_TARGET_EXISTS_UNDER_DIFFERENT_ID'}return(!/^[a-z][a-z0-9_]*$/i.test(t)||t.length<3)?'CONFIRMED_INVALID_POINTER':'UNRESOLVED'};
const pointers=(manifest.rejected_pointers??[]).map((p:any)=>({...p,classification:pointerClass(p),source_chapter:(p.from.match(/ch(?:apter_)?(\d{1,2})/)??[])[1]??'unencoded',owner_type:(p.from.match(/^(chapter|section|concept|rule|verb|conj|expr|vocab|example|exercise|question)/)??[])[1]??'other',target_prefix:p.dangling_target.split('_')[0],id_pattern:p.dangling_target.replace(/\d+/g,'#')}));const pc=count(pointers,x=>x.classification);const pg=Object.entries(count(pointers,x=>[x.source_chapter,x.owner_type,x.field,x.target_prefix,x.id_pattern].join(' | '))).map(([group,total])=>({group,total})).sort((a,b)=>Number(b.total)-Number(a.total));
const tenseKey=(t:any)=>{const s=norm(`${t.id} ${t.name_french} ${t.name_english}`);if(/passive|voix_passive/.test(s))return`passive:${t.id}`;if(/present_subjunctive|subjonctif_present/.test(s))return'subjunctive_present';if(/past_subjunctive|subjonctif_passe/.test(s))return'subjunctive_past';if(/conditional.*present|conditionnel.*present|present_conditional/.test(s))return'conditional_present';if(/conditional.*past|conditionnel.*passe|past_conditional/.test(s))return'conditional_past';if(/futur_simple|simple_future|tense_future/.test(s))return'future_simple';if(/imparfait|imperfect/.test(s))return'imperfect';if(/imperatif|imperative/.test(s))return'imperative';if(/infinitive_past|infinitif_passe/.test(s))return'infinitive_past';if(/infinitif|infinitive/.test(s))return'infinitive_present';if(/participe|participle/.test(s))return`${t.mood}:${norm(t.name_french)}`;if(t.mood==='indicative'&&(/present_indicative|tense_present/.test(s)))return'present_indicative';return`${t.mood}:${norm(t.name_french)}:${norm(t.name_english)}`};
const tg=new Map<string,any[]>();for(const t of master.tenses??[])tg.set(tenseKey(t),[...(tg.get(tenseKey(t))??[]),t]);const groups=Array.from(tg.entries()).filter(([,x])=>x.length>1).map(([semantic_key,x])=>({semantic_key,ids:x.map(t=>t.id),names:x.map(t=>({french:t.name_french,english:t.name_english,mood:t.mood}))}));const raw=(master.tenses??[]).length, aliases=groups.reduce((n,g)=>n+g.ids.length-1,0);
const helpers=[mergePath,path.join(root,'src/lib/dataset/ids.ts'),path.join(root,'src/lib/dataset/canonicalize.ts')].map(p=>({file:path.relative(root,p),text:fs.readFileSync(p,'utf8')}));const reads={bookdata_json:helpers.some(x=>/bookdata[\\/]json/.test(x.text)),data_extracted:helpers.some(x=>/data[\\/]extracted/.test(x.text)),data_normalized:helpers.some(x=>/data[\\/]normalized/.test(x.text)),deprecated_final_master:helpers.some(x=>/data[\\/]final[\\/]french_grammar\.json/.test(x.text))};const isolation=reads.bookdata_json&&!reads.data_extracted&&!reads.data_normalized&&!reads.deprecated_final_master;
const answers=ev.filter(e=>e.kind==='answer'),qs=(master.exercises??[]).flatMap((x:any)=>(x.questions??[]).map((q:any)=>({x,q})));const unmatchedA=answers.filter(e=>disp(e)!=='REPRESENTED_ANSWER').map(e=>e.id);const unmatchedQ=qs.filter(({x,q}:any)=>{const a=answers.filter(e=>norm(e.value.exercise_code)===norm(x.exercise_number));return !a.some(e=>String(q.question_id).endsWith(`_${e.value.question_number}`)&&norm(q.answer)===norm(e.value.answer))&&!a.some(e=>norm(q.answer)===norm(e.value.all_answers.join(' / ')))}).map(({q}:any)=>q.question_id);const answerCheck={exercises:(master.exercises??[]).length,canonical_questions:qs.length,answer_entries:answers.length,structural_extra_answer_slots:answers.length-qs.length,unmatched_canonical_questions:unmatchedQ,unmatched_answer_entries:unmatchedA};const answersPass=answerCheck.exercises===197&&answerCheck.canonical_questions===1868&&answerCheck.answer_entries===1872&&answerCheck.structural_extra_answer_slots===4&&!unmatchedQ.length&&!unmatchedA.length;
const idem=read(path.join(rec,'authoritative-idempotence-report.json')),counts:any=Object.fromEntries(cols.map(k=>[k,(master[k]??[]).length]));counts.questions=qs.length;counts.answered_questions=qs.filter((z:any)=>z.q.answer!=null).length;const sha=createHash('sha256').update(JSON.stringify(master,null,2)).digest('hex');const repair=fs.readFileSync(path.join(rec,'master-authoritative-source-repair-report.md'),'utf8');const sync=sha===idem.run_1?.sha256&&sha===idem.run_2?.sha256&&JSON.stringify(counts)===JSON.stringify(idem.run_1?.record_counts)&&/executePipeline\(1\)[\s\S]*executePipeline\(2\)/.test(merge)&&repair.includes(sha);
const risky=pointers.filter((x:any)=>!['CONFIRMED_INVALID_POINTER','EXPLICITLY_REJECTED_WITH_JUSTIFICATION'].includes(x.classification));const blockers=[tautological&&'Replace tautological provenance mirroring.',unaccounted.length&&`Disposition or represent ${unaccounted.length} source evidence occurrences.`,risky.length&&'Resolve or preserve listed rejected pointers; unknown pointers are not safe rejections.',aliases&&'Canonicalize listed tense alias groups.',!sync&&'Regenerate stale reconciliation report content.',!isolation&&'Remove deprecated executable semantic input reads.',!answersPass&&'Reconcile listed answer/question identities.'].filter(Boolean)as string[];const verdict=blockers.length?'TERRA_TARGETED_REPAIR_REQUIRED':'TERRA_TARGETED_AUDIT_PASS';
const result={generated_at:new Date().toISOString(),verdict,blockers,source_universe:{count:ev.length,disposition_counts:dcounts,unaccounted_count:unaccounted.length,unaccounted_by_kind:count(unaccounted,x=>x.kind),suspicious_unaccounted:unaccounted.slice(0,150)},provenance_independence:{published_ledger_assessment:tautological?'TAUTOLOGICAL / INSUFFICIENT':'VALID'},rejected_pointer_classification:{total:pointers.length,counts:pc,groups:pg.slice(0,100),classifications:pointers},tense_canonicalization:{raw_tense_count:raw,canonical_tense_count:raw-aliases,alias_duplicate_count:aliases,passive_paradigm_count:(master.tenses??[]).filter((t:any)=>/passive|voix_passive/i.test(`${t.id} ${t.name_french} ${t.name_english}`)).length,duplicate_groups:groups},input_isolation:{inspected_files:helpers.map(x=>x.file),semantic_read_references:reads,status:isolation?'PASS':'FAIL'},answer_reconciliation:{...answerCheck,status:answersPass?'PASS':'FAIL'},artifact_synchronization:{status:sync?'SYNCHRONIZED':'ARTIFACT_DRIFT',actual_sha256:sha,reported_sha256:idem.run_1?.sha256,actual_counts:counts,reported_counts:idem.run_1?.record_counts,execute_pipeline_twice:/executePipeline\(1\)[\s\S]{0,1800}executePipeline\(2\)/.test(merge)}};
writeJson(path.join(rec,'authoritative-independent-audit.json'),result);function writeJson(p:string,v:any){fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n')}
const md=`# Terra Targeted Authoritative Audit\n\n## Executive Verdict\n\n${verdict}.\n\n## Independent Audit Method\n\nDirect source occurrences are compared with persisted-master fields and explicit rejection records; the merge is never imported.\n\n## Provenance Independence\n\n${result.provenance_independence.published_ledger_assessment}; source occurrences: ${ev.length}; unaccounted: ${unaccounted.length}.\n\n## Rejected Pointer Classification\n\n${Object.entries(pc).map(([k,v])=>`${k}: ${v}`).join('; ')}.\n\n## Tense Canonicalization\n\nRAW_TENSE_COUNT: ${raw}; CANONICAL_TENSE_COUNT: ${raw-aliases}; ALIAS_DUPLICATE_COUNT: ${aliases}.\n\n## Artifact Synchronization\n\n${result.artifact_synchronization.status}.\n\n## Input Isolation\n\n${result.input_isolation.status}: ${JSON.stringify(reads)}.\n\n## Answer Reconciliation\n\n${result.answer_reconciliation.status}: ${answerCheck.exercises} exercises, ${answerCheck.canonical_questions} questions, ${answerCheck.answer_entries} answers, ${answerCheck.structural_extra_answer_slots} structural extra slots, ${unmatchedQ.length} unmatched questions, ${unmatchedA.length} unmatched answers.\n\n## Reusable Audit Script\n\n\`tsx scripts/audit-authoritative-master.ts\` writes these artifacts and exits nonzero on blockers.\n\n## Promotion Blockers\n\n${blockers.length?blockers.map(x=>`- ${x}`).join('\n'):'None.'}\n\n## Non-Blocking Observations\n\nJSON retains deterministic classifications and suspicious IDs without listing thousands of normal records.\n\n## Final Decision\n\n${verdict}\n`;fs.writeFileSync(path.join(rec,'authoritative-independent-audit.md'),md);console.log(`${verdict}: blockers=${blockers.length}; evidence=${ev.length}; unaccounted=${unaccounted.length}; rejected=${pointers.length}; aliases=${aliases}; answers=${result.answer_reconciliation.status}`);process.exitCode=verdict==='TERRA_TARGETED_AUDIT_PASS'?0:1;
