import { ChapterExtractionBundle } from "./chapter-types";
import { RawPage } from "./extract-pages";
import { extractChapterExercises } from "./extract-chapter";
import {
  GrammarRule,
  Verb,
  Conjugation,
  Expression,
  Vocabulary,
  Example,
  Chapter,
  Section,
} from "../src/lib/dataset/schemas";
import {
  makeChapterId,
  makeSectionId,
  makeRuleId,
  makeVerbId,
  makeConjugationId,
  makeVocabId,
  makeExpressionId,
  makeExampleId,
} from "../src/lib/dataset/ids";

// =======================================================================
// CHAPTER 6: Pronominal verbs
// =======================================================================
export function buildChapter6(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 6;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 49 && (p.printed_page || 0) <= 54);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "Reflexive verbs"),
    chapter_id: chId,
    order: 1,
    title: "Reflexive verbs",
    concept_ids: ["concept_pronominal_verbs"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("reflexive_verbs_conjugation_and_pronouns")],
    verb_ids: [makeVerbId("se lever"), makeVerbId("se laver"), makeVerbId("s'habiller"), makeVerbId("se coucher"), makeVerbId("se peigner"), makeVerbId("se couper"), makeVerbId("se reposer")],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("se_lever", 1)],
    exercise_ids: [exercises[0]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 49, page_end_printed: 50, page_start_pdf: 63, page_end_pdf: 64 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "Reciprocal verbs"),
    chapter_id: chId,
    order: 2,
    title: "Reciprocal verbs",
    concept_ids: ["concept_pronominal_verbs"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("reciprocal_verbs_usage")],
    verb_ids: [makeVerbId("se parler"), makeVerbId("se voir"), makeVerbId("s'aimer"), makeVerbId("se téléphoner"), makeVerbId("s'écrire"), makeVerbId("se rencontrer"), makeVerbId("se marier"), makeVerbId("s'embrasser")],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("se_voir", 1)],
    exercise_ids: [exercises[1]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 50, page_end_printed: 51, page_start_pdf: 64, page_end_pdf: 65 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "Passive and subjective pronominals"),
    chapter_id: chId,
    order: 3,
    title: "Passive and subjective pronominals",
    concept_ids: ["concept_pronominal_verbs"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("passive_and_idiomatic_pronominals")],
    verb_ids: [makeVerbId("se souvenir"), makeVerbId("se rendre compte"), makeVerbId("se tromper"), makeVerbId("se dépêcher"), makeVerbId("s'en aller"), makeVerbId("s'attendre à"), makeVerbId("se passer")],
    expression_ids: [makeExpressionId("se rendre compte de"), makeExpressionId("se souvenir de"), makeExpressionId("s'attendre a")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("se_rendre_compte", 1)],
    exercise_ids: [exercises[2]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 51, page_end_printed: 52, page_start_pdf: 65, page_end_pdf: 66 },
  };

  const sec4 = {
    id: makeSectionId(chNum, 4, "Pronominals in imperative and infinitive"),
    chapter_id: chId,
    order: 4,
    title: "Pronominals in the imperative and the infinitive",
    concept_ids: ["concept_pronominal_verbs"],
    tense_ids: ["tense_present_indicative", "tense_imperatif", "tense_infinitif_present"],
    grammar_rule_ids: [makeRuleId("pronominals_imperative_and_infinitive_position")],
    verb_ids: [makeVerbId("se promener")],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("imperative_pronominal", 1)],
    exercise_ids: [exercises[3]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 52, page_end_printed: 54, page_start_pdf: 66, page_end_pdf: 68 },
  };

  const sections = [sec1, sec2, sec3, sec4];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("reflexive_verbs_conjugation_and_pronouns"),
      type: "grammar_rule",
      title: "Reflexive verbs and pronoun placement",
      short_label: "Reflexive pronouns",
      grammar_category: "pronominal_verbs",
      concept_ids: ["concept_pronominal_verbs"],
      tense_ids: ["tense_present_indicative"],
      summary: "Reflexive pronouns match the subject: je me, tu te, il/elle/on se, nous nous, vous vous, ils/elles se.",
      explanation: "A reflexive verb indicates that the subject performs an action on itself. Reflexive pronouns (me, te, se, nous, vous, se) precede the conjugated verb in simple tenses.",
      formation: {
        steps: ["Match reflexive pronoun to subject", "Place pronoun before conjugated verb"],
        patterns: ["[SUBJECT] + [me/te/se/nous/vous/se] + [VERBE]"],
        endings: {},
      },
      usage_conditions: ["Actions done to oneself (daily routine, grooming)"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Before a vowel or silent h, me, te, se become m', t', s'."],
      common_mistakes: [{ wrong: "Je lave moi", correct: "Je me lave", explanation: "Use reflexive pronoun 'me', not disjunctive pronoun 'moi'." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("se_lever", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 49, context_type: "grammar_explanation" }],
      tags: ["essential", "pronominal"],
    },
    {
      id: makeRuleId("reciprocal_verbs_usage"),
      type: "grammar_rule",
      title: "Reciprocal verbs: actions done to one another",
      short_label: "Reciprocal verbs",
      grammar_category: "pronominal_verbs",
      concept_ids: ["concept_pronominal_verbs"],
      tense_ids: ["tense_present_indicative"],
      summary: "Used only in the plural persons (nous, vous, ils/elles) to express 'each other' or 'one another'.",
      explanation: "Verbs like se parler (to speak to each other), se voir (to see each other), s'aimer (to love each other), se téléphoner (to call each other) express reciprocal actions.",
      formation: null,
      usage_conditions: ["Mutual interactions between two or more people"],
      trigger_words: ["l'un l'autre", "les uns les autres"],
      signal_words: [],
      exceptions: [],
      restrictions: ["Can only be used with plural subjects (nous, vous, ils, elles)."],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("reflexive_verbs_conjugation_and_pronouns")],
      example_ids: [makeExampleId("se_voir", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 50, context_type: "grammar_explanation" }],
      tags: ["essential", "pronominal"],
    },
    {
      id: makeRuleId("passive_and_idiomatic_pronominals"),
      type: "grammar_rule",
      title: "Passive and idiomatic pronominals",
      short_label: "Idiomatic pronominals",
      grammar_category: "pronominal_verbs",
      concept_ids: ["concept_pronominal_verbs"],
      tense_ids: ["tense_present_indicative"],
      summary: "Pronominal verbs with passive meanings (ça se vend bien) or unique idiomatic meanings (se souvenir, se rendre compte).",
      explanation: "1. Passive pronominal: 'Le vin français se vend partout' (French wine is sold everywhere).\n2. Idiomatic pronominal: 'se souvenir de' (to remember), 'se rendre compte de' (to realize), 'se dépêcher' (to hurry), 'se tromper' (to make a mistake).",
      formation: null,
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Je réalise que... (anglicism)", correct: "Je me rends compte que...", explanation: "Use se rendre compte de for realizing something." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("se_rendre_compte", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 51, context_type: "grammar_explanation" }],
      tags: ["essential", "pronominal", "idiomatic"],
    },
    {
      id: makeRuleId("pronominals_imperative_and_infinitive_position"),
      type: "grammar_rule",
      title: "Pronominal pronouns in imperative and with infinitives",
      short_label: "Pronominal position",
      grammar_category: "pronominal_verbs",
      concept_ids: ["concept_pronominal_verbs"],
      tense_ids: ["tense_present_indicative", "tense_imperatif"],
      summary: "In affirmative imperative, pronouns follow with hyphen and 'te' becomes 'toi' (Lève-toi!). With infinitive, pronoun precedes the infinitive (Je veux me lever).",
      explanation: "Affirmative imperative: 'Lève-toi!', 'Habillons-nous!', 'Dépêchez-vous!'.\nNegative imperative: 'Ne te lève pas!', 'Ne nous dépêchons pas!'.\nWith infinitive: Reflexive pronoun always matches the subject of the infinitive: 'Je vais me promener' (not 'Je vais se promener').",
      formation: null,
      usage_conditions: ["Commands", "Semi-auxiliary verb + infinitive constructions"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Je vais se promener", correct: "Je vais me promener", explanation: "Reflexive pronoun must agree with subject 'je'." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("imperative_pronominal", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 52, context_type: "grammar_explanation" }],
      tags: ["essential", "pronominal", "imperative"],
    },
  ];

  const verbsList6 = [
    { inf: "se lever", en: ["to get up", "to stand up"], part: "levé" },
    { inf: "se laver", en: ["to wash oneself"], part: "lavé" },
    { inf: "s'habiller", en: ["to get dressed"], part: "habillé" },
    { inf: "se coucher", en: ["to go to bed"], part: "couché" },
    { inf: "se reposer", en: ["to rest"], part: "reposé" },
    { inf: "se souvenir", en: ["to remember"], part: "souvenu" },
    { inf: "se rendre compte", en: ["to realize"], part: "rendu compte" },
    { inf: "se dépêcher", en: ["to hurry"], part: "dépêché" },
    { inf: "se tromper", en: ["to make a mistake"], part: "trompé" },
    { inf: "se marier", en: ["to get married"], part: "marié" },
    { inf: "se voir", en: ["to see each other"], part: "vu" },
    { inf: "se promener", en: ["to take a walk", "to stroll"], part: "promené" },
  ];

  const verbs: Verb[] = verbsList6.map((v) => {
    const vId = makeVerbId(v.inf);
    return {
      id: vId,
      type: "verb",
      infinitive: v.inf,
      display_form: v.inf,
      english: v.en,
      senses: [{ sense_id: `${vId}_s1`, english: v.en, usage_contexts: [], example_ids: [] }],
      verb_group: v.inf === "se souvenir" ? "3rd_group" : "1st_group",
      regularity: "regular",
      pronominal: true,
      transitivity: ["intransitive"],
      auxiliary: "etre",
      past_participle: v.part || null,
      present_participle: null,
      conjugation_ids: [makeConjugationId(vId, "tense_present_indicative")],
      expression_ids: [],
      complement_frame_ids: [],
      related_verb_ids: [],
      contrast_verb_ids: [],
      confused_with_ids: [],
      word_family_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 4 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 49, context_type: "grammar_explanation" }],
      tags: ["pronominal", "essential", "chapter_06"],
    };
  });

  const conjugations: Conjugation[] = [
    {
      id: makeConjugationId("verb_se_lever", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("se lever"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je me lève",
        tu: "tu te lèves",
        il_elle_on: "il/elle/on se lève",
        nous: "nous nous levons",
        vous: "vous vous levez",
        ils_elles: "ils/elles se lèvent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["è grave in boot forms"],
      irregularity_notes: [],
      example_ids: [makeExampleId("se_lever", 1)],
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 49, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
  ];

  const expressions: Expression[] = [
    {
      id: makeExpressionId("se rendre compte de"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "se rendre compte de",
      display_form: "se rendre compte de + nom / que + phrase",
      english: ["to realize something"],
      base_verb_ids: [makeVerbId("se rendre compte")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "se rendre compte de [NOUN] / que [CLAUSE]",
      pattern_slots: [{ name: "fact", display: "fait ou proposition", type: "clause_or_noun", required: true }],
      transformations: [],
      variants: ["se rendre compte d'"],
      function_ids: [],
      usage_notes: ["Correct French idiom for 'to realize'"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("se_rendre_compte", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["conversation", "cognition"] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 51, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("passive_and_idiomatic_pronominals")] },
      tags: ["essential", "idiom", "verb_pattern"],
    },
    {
      id: makeExpressionId("se souvenir de"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "se souvenir de",
      display_form: "se souvenir de + nom / infinitif",
      english: ["to remember something / someone"],
      base_verb_ids: [makeVerbId("se souvenir")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "se souvenir de [PERSON / NOUN / INFINITIVE]",
      pattern_slots: [{ name: "memory", display: "souvenir", type: "noun_or_infinitive", required: true }],
      transformations: [],
      variants: ["se souvenir d'"],
      function_ids: [],
      usage_notes: ["Synonym of se rappeler (which takes direct object without de)"],
      restrictions: [],
      common_mistakes: [{ wrong: "Je me souviens le film", correct: "Je me souviens du film", explanation: "Se souvenir takes 'de'." }],
      example_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 51, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("passive_and_idiomatic_pronominals")] },
      tags: ["essential", "verb_pattern"],
    },
  ];

  const vocabulary: Vocabulary[] = [];

  const examples: Example[] = [
    {
      id: makeExampleId("se_lever", 1),
      type: "example",
      french: "Je me lève tous les jours à sept heures.",
      english: "I get up every day at seven o'clock.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "me lève", role: "pronominal_verb" }] },
      relations: { verbs: [makeVerbId("se lever")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["me lève"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 49, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("se_voir", 1),
      type: "example",
      french: "Ils se voient tous les week-ends.",
      english: "They see each other every weekend.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "se voient", role: "reciprocal_verb" }] },
      relations: { verbs: [makeVerbId("se voir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["se voient"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 50, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("se_rendre_compte", 1),
      type: "example",
      french: "Elle se rend compte de son erreur.",
      english: "She realizes her mistake.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "se rend compte de", role: "expression" }] },
      relations: { verbs: [makeVerbId("se rendre compte")], expressions: [makeExpressionId("se rendre compte de")] },
      cloze_candidates: ["se rend compte de"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 51, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("imperative_pronominal", 1),
      type: "example",
      french: "Dépêchez-vous! Nous sommes en retard.",
      english: "Hurry up! We are late.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "Dépêchez-vous", role: "imperative_pronominal" }] },
      relations: { verbs: [makeVerbId("se dépêcher")], tenses: ["tense_imperatif"] },
      cloze_candidates: ["Dépêchez-vous"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 6, page_printed: 53, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "Pronominal verbs",
    section_ids: sections.map((s) => s.id),
    concept_ids: ["concept_pronominal_verbs"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 49, page_end_printed: 54, page_start_pdf: 63, page_end_pdf: 68 },
    tags: ["pronominal_verbs", "reflexive", "reciprocal"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}

// =======================================================================
// CHAPTER 7: The passé composé
// =======================================================================
export function buildChapter7(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 7;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 55 && (p.printed_page || 0) <= 64);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "The past participle of regular verbs"),
    chapter_id: chId,
    order: 1,
    title: "The past participle of regular verbs",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_passe_compose"],
    grammar_rule_ids: [makeRuleId("past_participle_regular_endings")],
    verb_ids: [],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("participle_reg", 1)],
    exercise_ids: [exercises[0]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 55, page_end_printed: 56, page_start_pdf: 69, page_end_pdf: 70 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "The passe compose with avoir"),
    chapter_id: chId,
    order: 2,
    title: "The passé composé with avoir",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_passe_compose"],
    grammar_rule_ids: [makeRuleId("passe_compose_with_avoir_formation"), makeRuleId("agreement_with_preceding_direct_object")],
    verb_ids: [],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("passe_compose_avoir", 1)],
    exercise_ids: [exercises[1]?.id, exercises[2]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 56, page_end_printed: 58, page_start_pdf: 70, page_end_pdf: 72 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "Irregular past participles"),
    chapter_id: chId,
    order: 3,
    title: "Irregular past participles",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_passe_compose"],
    grammar_rule_ids: [makeRuleId("irregular_past_participles_categories")],
    verb_ids: [
      makeVerbId("avoir"),
      makeVerbId("être"),
      makeVerbId("faire"),
      makeVerbId("dire"),
      makeVerbId("écrire"),
      makeVerbId("prendre"),
      makeVerbId("mettre"),
      makeVerbId("voir"),
      makeVerbId("boire"),
      makeVerbId("lire"),
      makeVerbId("pouvoir"),
      makeVerbId("vouloir"),
      makeVerbId("savoir"),
      makeVerbId("devoir"),
    ],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("participle_irreg", 1)],
    exercise_ids: [exercises[3]?.id, exercises[4]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 58, page_end_printed: 60, page_start_pdf: 72, page_end_pdf: 74 },
  };

  const sec4 = {
    id: makeSectionId(chNum, 4, "The passe compose with etre"),
    chapter_id: chId,
    order: 4,
    title: "The passé composé with être",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_passe_compose"],
    grammar_rule_ids: [makeRuleId("vandertramp_verbs_with_etre"), makeRuleId("etre_subject_agreement_rule")],
    verb_ids: [
      makeVerbId("aller"),
      makeVerbId("venir"),
      makeVerbId("arriver"),
      makeVerbId("partir"),
      makeVerbId("entrer"),
      makeVerbId("sortir"),
      makeVerbId("monter"),
      makeVerbId("descendre"),
      makeVerbId("naître"),
      makeVerbId("mourir"),
      makeVerbId("retourner"),
      makeVerbId("tomber"),
      makeVerbId("rester"),
    ],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("passe_compose_etre", 1)],
    exercise_ids: [exercises[5]?.id, exercises[6]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 60, page_end_printed: 62, page_start_pdf: 74, page_end_pdf: 76 },
  };

  const sec5 = {
    id: makeSectionId(chNum, 5, "Pronominal verbs and dual auxiliary verbs"),
    chapter_id: chId,
    order: 5,
    title: "Pronominal verbs in the passé composé and dual auxiliary verbs",
    concept_ids: ["concept_past_time", "concept_pronominal_verbs"],
    tense_ids: ["tense_passe_compose"],
    grammar_rule_ids: [makeRuleId("pronominal_verbs_in_passe_compose"), makeRuleId("verbs_with_both_avoir_and_etre")],
    verb_ids: [makeVerbId("passer"), makeVerbId("rentrer")],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("dual_auxiliary", 1)],
    exercise_ids: [exercises[7]?.id, exercises[8]?.id, exercises[9]?.id, exercises[10]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 62, page_end_printed: 64, page_start_pdf: 76, page_end_pdf: 78 },
  };

  const sections = [sec1, sec2, sec3, sec4, sec5];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("past_participle_regular_endings"),
      type: "grammar_rule",
      title: "Formation of regular past participles",
      short_label: "Regular past participles",
      grammar_category: "participle_formation",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_passe_compose"],
      summary: "-er verbs -> -é; -ir verbs -> -i; -re verbs -> -u.",
      explanation: "Regular verbs form the past participle by changing the infinitive ending:\n- parler -> parlé\n- finir -> fini\n- vendre -> vendu",
      formation: {
        steps: ["-er -> -é", "-ir -> -i", "-re -> -u"],
        patterns: ["-é / -i / -u"],
        endings: {},
      },
      usage_conditions: ["Compound tenses (passé composé, plus-que-parfait, etc.)"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("participle_reg", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 55, context_type: "grammar_explanation" }],
      tags: ["essential", "participle"],
    },
    {
      id: makeRuleId("passe_compose_with_avoir_formation"),
      type: "grammar_rule",
      title: "Formation of the passé composé with avoir",
      short_label: "passé composé (avoir)",
      grammar_category: "tense_formation",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_passe_compose"],
      summary: "Present of avoir + past participle. Most verbs use avoir as auxiliary.",
      explanation: "The vast majority of French verbs use avoir: 'J'ai parlé', 'Tu as fini', 'Nous avons vendu'. In standard word order, the past participle does NOT agree with the subject.",
      formation: {
        steps: ["Conjugate avoir in present", "Add past participle of action verb"],
        patterns: ["[SUBJECT] + avoir (présent) + [PARTICIPE PASSÉ]"],
        endings: {},
      },
      usage_conditions: ["Completed specific past actions and events"],
      trigger_words: ["hier", "hier soir", "la semaine dernière", "l'année passée", "soudain"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Adverbs like bien, mal, beaucoup, déjà, trop, vite usually sit between avoir and the past participle: 'J'ai bien mangé'."],
      common_mistakes: [{ wrong: "Elle a parlée", correct: "Elle a parlé", explanation: "No agreement with subject when conjugated with avoir." }],
      contrast_with_rule_ids: [makeRuleId("vandertramp_verbs_with_etre")],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("passe_compose_avoir", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 56, context_type: "grammar_explanation" }],
      tags: ["essential", "past", "passe_compose"],
    },
    {
      id: makeRuleId("agreement_with_preceding_direct_object"),
      type: "grammar_rule",
      title: "Agreement of past participle with preceding direct object (P.D.O.)",
      short_label: "Preceding direct object agreement",
      grammar_category: "agreement",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_passe_compose"],
      summary: "When a direct object precedes the verb with avoir, the past participle agrees in gender and number with that direct object.",
      explanation: "If the direct object pronoun (le, la, les), relative pronoun (que), or noun in a question with quel/combien precedes avoir, the past participle agrees:\n- 'Les fleurs que j'ai achetées' (fem. pl.)\n- 'Ces lettres? Je les ai écrites' (fem. pl.)",
      formation: null,
      usage_conditions: ["Direct object pronoun / que / quel preceding avoir"],
      trigger_words: ["que", "les", "la", "l'", "quelle", "combien de"],
      signal_words: [],
      exceptions: ["No agreement with indirect object pronouns (lui, leur) or with 'en'."],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Je leur ai téléphonés", correct: "Je leur ai téléphoné", explanation: "Leur is an indirect object; no agreement." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("passe_compose_with_avoir_formation")],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 4 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 57, context_type: "grammar_explanation" }],
      tags: ["essential", "agreement"],
    },
    {
      id: makeRuleId("vandertramp_verbs_with_etre"),
      type: "grammar_rule",
      title: "Verbs conjugated with être in the passé composé (DR & MRS VANDERTRAMP)",
      short_label: "passé composé (être)",
      grammar_category: "tense_formation",
      concept_ids: ["concept_past_time", "concept_movement"],
      tense_ids: ["tense_passe_compose"],
      summary: "Intransitive movement and state-change verbs take être; the past participle ALWAYS agrees with the subject.",
      explanation: "Key verbs taking être:\nDevenir, Revenir, Monter, Rester, Sortir, Venir, Aller, Naître, Descendre, Entrer, Rentrer, Tomber, Retourner, Arriver, Mourir, Partir.\nThe past participle agrees with the subject in gender and number: 'Elle est allée', 'Ils sont partis'.",
      formation: {
        steps: ["Conjugate être in present", "Add past participle", "Agree participle with subject (+e, +s, +es)"],
        patterns: ["[SUBJECT] + être (présent) + [PARTICIPE PASSÉ ACCORDÉ]"],
        endings: {},
      },
      usage_conditions: ["Specific intransitive movement and change of state verbs"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Pronominal verbs also always use être as auxiliary."],
      common_mistakes: [{ wrong: "Elle est allé", correct: "Elle est allée", explanation: "Participle must agree in gender and number with subject when conjugated with être." }],
      contrast_with_rule_ids: [makeRuleId("passe_compose_with_avoir_formation")],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("passe_compose_etre", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 60, context_type: "grammar_explanation" }],
      tags: ["essential", "past", "vandertramp", "agreement"],
    },
    {
      id: makeRuleId("verbs_with_both_avoir_and_etre"),
      type: "grammar_rule",
      title: "Verbs conjugated with both avoir and être depending on direct object",
      short_label: "Dual auxiliary verbs",
      grammar_category: "verb_semantics",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_passe_compose"],
      summary: "Six verbs (monter, descendre, sortir, rentrer, passer, retourner) take avoir when followed by a direct object, but être when used intransitively.",
      explanation: "- Intransitive (movement) -> être: 'Elle est sortie' (She went out).\n- Transitive (direct object) -> avoir: 'Elle a sorti la poubelle' (She took out the trash).\n- 'Je suis passé chez toi' (I stopped by) vs 'J'ai passé un examen' (I took an exam / spent time).",
      formation: null,
      usage_conditions: ["Transitive vs intransitive usage of movement verbs"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Elle est descendue ses valises", correct: "Elle a descendu ses valises", explanation: "Use avoir when a direct object follows." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("dual_auxiliary", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 63, context_type: "grammar_explanation" }],
      tags: ["essential", "past", "auxiliary_choice"],
    },
  ];

  const verbs: Verb[] = [];
  const conjugations: Conjugation[] = [];
  const expressions: Expression[] = [];
  const vocabulary: Vocabulary[] = [];

  const examples: Example[] = [
    {
      id: makeExampleId("participle_reg", 1),
      type: "example",
      french: "J'ai parlé avec mon professeur après le cours.",
      english: "I spoke with my professor after class.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "ai parlé", role: "past_verb" }] },
      relations: { verbs: [makeVerbId("parler")], tenses: ["tense_passe_compose"] },
      cloze_candidates: ["ai parlé"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 56, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("passe_compose_avoir", 1),
      type: "example",
      french: "Nous avons fini notre projet hier soir.",
      english: "We finished our project yesterday evening.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "avons fini", role: "past_verb" }] },
      relations: { verbs: [makeVerbId("finir")], tenses: ["tense_passe_compose"] },
      cloze_candidates: ["avons fini"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 56, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("participle_irreg", 1),
      type: "example",
      french: "Elle a pris le train de huit heures.",
      english: "She took the eight o'clock train.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "a pris", role: "past_verb" }] },
      relations: { verbs: [makeVerbId("prendre")], tenses: ["tense_passe_compose"] },
      cloze_candidates: ["a pris"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 58, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("passe_compose_etre", 1),
      type: "example",
      french: "Elles sont arrivées en retard à la réunion.",
      english: "They arrived late to the meeting.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "sont arrivées", role: "past_verb_etre" }] },
      relations: { verbs: [makeVerbId("arriver")], tenses: ["tense_passe_compose"] },
      cloze_candidates: ["sont arrivées"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 60, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("dual_auxiliary", 1),
      type: "example",
      french: "Elle est passée à la banque, puis elle a passé un coup de fil.",
      english: "She stopped by the bank, then she made a phone call.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "est passée", role: "intransitive" }, { text: "a passé", role: "transitive" }] },
      relations: { verbs: [makeVerbId("passer")], tenses: ["tense_passe_compose"] },
      cloze_candidates: ["est passée", "a passé"],
      study: { difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 7, page_printed: 63, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "The passé composé",
    section_ids: sections.map((s) => s.id),
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_passe_compose"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 55, page_end_printed: 64, page_start_pdf: 69, page_end_pdf: 78 },
    tags: ["passe_compose", "past_tenses", "auxiliary_avoir", "auxiliary_etre", "agreement"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}

// =======================================================================
// CHAPTER 8: The imparfait
// =======================================================================
export function buildChapter8(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 8;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 65 && (p.printed_page || 0) <= 71);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "The imparfait"),
    chapter_id: chId,
    order: 1,
    title: "The imparfait",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_imparfait"],
    grammar_rule_ids: [makeRuleId("imparfait_formation_rule")],
    verb_ids: [],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("imparfait", 1)],
    exercise_ids: [exercises[0]?.id, exercises[1]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 65, page_end_printed: 67, page_start_pdf: 79, page_end_pdf: 81 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "The imparfait versus the passe compose"),
    chapter_id: chId,
    order: 2,
    title: "The imparfait versus the passé composé",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_imparfait", "tense_passe_compose"],
    grammar_rule_ids: [makeRuleId("imparfait_vs_passe_compose_master_contrast")],
    verb_ids: [],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("pc_vs_imp", 1)],
    exercise_ids: [exercises[2]?.id, exercises[3]?.id, exercises[4]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 67, page_end_printed: 70, page_start_pdf: 81, page_end_pdf: 84 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "The imparfait with special constructions"),
    chapter_id: chId,
    order: 3,
    title: "The imparfait with special constructions",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_imparfait"],
    grammar_rule_ids: [makeRuleId("si_plus_imparfait_suggestions"), makeRuleId("imparfait_with_depuis_and_venir_de")],
    verb_ids: [],
    expression_ids: [makeExpressionId("si on + imparfait"), makeExpressionId("venait de + infinitif")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("si_imparfait", 1)],
    exercise_ids: [exercises[5]?.id, exercises[6]?.id, exercises[7]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 70, page_end_printed: 71, page_start_pdf: 84, page_end_pdf: 85 },
  };

  const sections = [sec1, sec2, sec3];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("imparfait_formation_rule"),
      type: "grammar_rule",
      title: "Formation of the imparfait",
      short_label: "imparfait formation",
      grammar_category: "tense_formation",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_imparfait"],
      summary: "Take the 'nous' present stem and add: -ais, -ais, -ait, -ions, -iez, -aient. Only one exception: être (ét-).",
      explanation: "Find the stem by dropping -ons from the present tense 'nous' form:\n- nous parlons -> parl- + ais/ais/ait/ions/iez/aient\n- nous finissons -> finiss- + ais/ais/ait/ions/iez/aient\n- nous vendons -> vend- + ais/ais/ait/ions/iez/aient\n- Exception: être uses stem 'ét-' (j'étais, tu étais, etc.).",
      formation: {
        steps: ["Conjugate verb in present with 'nous'", "Drop -ons to find the stem", "Add endings: -ais, -ais, -ait, -ions, -iez, -aient"],
        patterns: ["nous_stem + -ais/-ais/-ait/-ions/-iez/-aient"],
        endings: { je: "ais", tu: "ais", il_elle_on: "ait", nous: "ions", vous: "iez", ils_elles: "aient" },
      },
      usage_conditions: ["Past descriptions", "Habits", "Ongoing background actions"],
      trigger_words: ["autrefois", "souvent", "tous les jours", "chaque été", "pendant que"],
      signal_words: [],
      exceptions: ["être is the only irregular stem: ét-"],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "j'étais (from infinitive stem)", correct: "j'étais (ét- stem)", explanation: "Only être is irregular in the imparfait." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("imparfait", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 8, page_printed: 65, context_type: "grammar_explanation" }],
      tags: ["essential", "imparfait", "formation"],
    },
    {
      id: makeRuleId("imparfait_vs_passe_compose_master_contrast"),
      type: "grammar_rule",
      title: "Imparfait versus passé composé",
      short_label: "Imparfait vs Passé composé",
      grammar_category: "tense_contrast",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_imparfait", "tense_passe_compose"],
      summary: "Passé composé = foreground, specific completed events, interruptions. Imparfait = background, descriptions, ongoing states, habitual actions.",
      explanation: "Use Passé Composé for:\n1. Completed actions with definite beginning/end\n2. Specific number of times or time limits\n3. Chain of sequential events\n4. Interrupter action\n\nUse Imparfait for:\n1. Setting the scene / background description (weather, emotions, physical states)\n2. Repeated or habitual actions (used to / would)\n3. Ongoing action in progress when another event occurred ('was doing').",
      formation: null,
      usage_conditions: ["Past narrative storytelling"],
      trigger_words: ["quand", "pendant que", "tout à coup", "soudain", "chaque jour", "un jour"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Certain verbs shift meaning between tenses: savoir (savait = knew facts; a su = found out), connaître (connaissait = knew; a connu = met for first time), vouloir (voulait = wanted; a voulu = tried / refused)."],
      common_mistakes: [{ wrong: "Il pleuvait quand je suis parti vs Il a plu quand je suis parti", correct: "Il pleuvait (background) quand je suis parti (event)", explanation: "Background weather uses imparfait." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("pc_vs_imp", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 4 },
      attestations: [{ source_type: "book", chapter_number: 8, page_printed: 67, context_type: "grammar_explanation" }],
      tags: ["essential", "tense_contrast", "past_narrative"],
    },
    {
      id: makeRuleId("si_plus_imparfait_suggestions"),
      type: "grammar_rule",
      title: "Suggestions and wishes with Si on + imparfait",
      short_label: "Si on + imparfait",
      grammar_category: "idiomatic_construction",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_imparfait"],
      summary: "Starting a sentence with 'Si on' + imparfait expresses a friendly suggestion ('How about...? / What if we...?').",
      explanation: "'Si on allait au restaurant ce soir?' (How about going to a restaurant tonight? / What if we went to a restaurant tonight?).",
      formation: {
        steps: ["Start with 'Si on' (or 'Si nous')", "Follow with verb in imparfait", "End with question mark"],
        patterns: ["Si on + [VERBE À L'IMPARFAIT]?"],
        endings: {},
      },
      usage_conditions: ["Making suggestions", "Proposing ideas to friends"],
      trigger_words: ["si on"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("imparfait_formation_rule")],
      example_ids: [makeExampleId("si_imparfait", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 8, page_printed: 70, context_type: "grammar_explanation" }],
      tags: ["essential", "suggestions", "conversation"],
    },
  ];

  const verbs: Verb[] = [];
  const conjugations: Conjugation[] = [];
  const expressions: Expression[] = [
    {
      id: makeExpressionId("si on + imparfait"),
      type: "expression",
      expression_type: "sentence_starter",
      canonical_form: "si on + imparfait",
      display_form: "Si on + verbe à l'imparfait?",
      english: ["How about...?", "What if we...?"],
      base_verb_ids: [],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "Si on [VERB_IMPARFAIT]?",
      pattern_slots: [{ name: "action", display: "action à l'imparfait", type: "verb", required: true }],
      transformations: [],
      variants: ["Et si on...?"],
      function_ids: [],
      usage_notes: ["Conversational suggestion formula"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("si_imparfait", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "spoken", contexts: ["conversation", "suggestions"] },
      frequency: { book_occurrences: 3 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 8, page_printed: 70, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("si_plus_imparfait_suggestions")] },
      tags: ["essential", "suggestion"],
    },
  ];
  const vocabulary: Vocabulary[] = [];

  const examples: Example[] = [
    {
      id: makeExampleId("imparfait", 1),
      type: "example",
      french: "Quand nous habitions à Paris, nous allions souvent au musée.",
      english: "When we were living in Paris, we often went to the museum.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "habitions", role: "imparfait" }, { text: "allions", role: "imparfait" }] },
      relations: { verbs: [makeVerbId("habiter"), makeVerbId("aller")], tenses: ["tense_imparfait"] },
      cloze_candidates: ["habitions", "allions"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 8, page_printed: 65, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("pc_vs_imp", 1),
      type: "example",
      french: "Je lisais tranquillement quand soudain le téléphone a sonné.",
      english: "I was reading quietly when suddenly the phone rang.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "lisais", role: "ongoing_background" }, { text: "a sonné", role: "interruption" }] },
      relations: { verbs: [makeVerbId("lire")], tenses: ["tense_imparfait", "tense_passe_compose"], grammar_rules: [makeRuleId("imparfait_vs_passe_compose_master_contrast")] },
      cloze_candidates: ["lisais", "a sonné"],
      study: { difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 8, page_printed: 68, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("si_imparfait", 1),
      type: "example",
      french: "Si on dînait sur la terrasse ce soir?",
      english: "How about having dinner on the terrace tonight?",
      source_type: "book",
      annotations: { focus_spans: [{ text: "Si on dînait", role: "suggestion" }] },
      relations: { expressions: [makeExpressionId("si on + imparfait")], tenses: ["tense_imparfait"] },
      cloze_candidates: ["dînait"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 8, page_printed: 70, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "The imparfait",
    section_ids: sections.map((s) => s.id),
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_imparfait", "tense_passe_compose"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 65, page_end_printed: 71, page_start_pdf: 79, page_end_pdf: 85 },
    tags: ["imparfait", "past_tenses", "contrast_pc_imp"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}

// =======================================================================
// CHAPTER 9: The futur simple and the futur antérieur
// =======================================================================
export function buildChapter9(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 9;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 72 && (p.printed_page || 0) <= 80);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "The futur simple"),
    chapter_id: chId,
    order: 1,
    title: "The futur simple",
    concept_ids: [],
    tense_ids: ["tense_futur_simple"],
    grammar_rule_ids: [makeRuleId("futur_simple_formation_and_stems")],
    verb_ids: [],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("futur_simple", 1)],
    exercise_ids: [exercises[0]?.id, exercises[1]?.id, exercises[2]?.id, exercises[3]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 72, page_end_printed: 77, page_start_pdf: 86, page_end_pdf: 91 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "The futur anterieur"),
    chapter_id: chId,
    order: 2,
    title: "The futur antérieur",
    concept_ids: [],
    tense_ids: ["tense_futur_anterieur"],
    grammar_rule_ids: [makeRuleId("futur_anterieur_formation_and_use")],
    verb_ids: [],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("futur_anterieur", 1)],
    exercise_ids: [exercises[4]?.id, exercises[5]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 77, page_end_printed: 79, page_start_pdf: 91, page_end_pdf: 93 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "Conjunctions used with the indicative mood"),
    chapter_id: chId,
    order: 3,
    title: "Conjunctions used with the indicative mood",
    concept_ids: [],
    tense_ids: ["tense_futur_simple", "tense_futur_anterieur"],
    grammar_rule_ids: [makeRuleId("futur_after_temporal_conjunctions")],
    verb_ids: [],
    expression_ids: [makeExpressionId("des que"), makeExpressionId("aussitot que"), makeExpressionId("des que + futur")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("conjunction_futur", 1)],
    exercise_ids: [exercises[6]?.id, exercises[7]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 79, page_end_printed: 80, page_start_pdf: 93, page_end_pdf: 94 },
  };

  const sections = [sec1, sec2, sec3];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("futur_simple_formation_and_stems"),
      type: "grammar_rule",
      title: "Formation of the futur simple and irregular stems",
      short_label: "futur simple formation",
      grammar_category: "tense_formation",
      concept_ids: [],
      tense_ids: ["tense_futur_simple"],
      summary: "Infinitive (or irregular future stem) + endings: -ai, -as, -a, -ons, -ez, -ont.",
      explanation: "For regular -er and -ir verbs, use the full infinitive. For -re verbs, drop the final 'e'.\nKey irregular stems:\n- avoir -> aur-\n- être -> ser-\n- aller -> ir-\n- faire -> fer-\n- venir -> viendr-\n- pouvoir -> pourr-\n- vouloir -> voudr-\n- savoir -> saur-\n- devoir -> devr-\n- voir -> verr-\n- envoyer -> enverr-",
      formation: {
        steps: ["Take infinitive or irregular future stem", "Add endings: -ai, -as, -a, -ons, -ez, -ont"],
        patterns: ["infinitive/stem + -ai/-as/-a/-ons/-ez/-ont"],
        endings: { je: "ai", tu: "as", il_elle_on: "a", nous: "ons", vous: "ez", ils_elles: "ont" },
      },
      usage_conditions: ["Future events, predictions, intentions"],
      trigger_words: ["demain", "l'année prochaine", "bientôt", "un jour"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["The future endings are derived from the present tense of avoir (-ai, -as, -a, -ons, -ez, -ont)."],
      common_mistakes: [{ wrong: "je parlerais (conditional ending)", correct: "je parlerai (future ending -ai)", explanation: "Future 1st person singular ends in -ai, conditional ends in -ais." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("futur_simple", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 9, page_printed: 72, context_type: "grammar_explanation" }],
      tags: ["essential", "future", "formation"],
    },
    {
      id: makeRuleId("futur_anterieur_formation_and_use"),
      type: "grammar_rule",
      title: "The futur antérieur (future perfect)",
      short_label: "futur antérieur",
      grammar_category: "tense_formation",
      concept_ids: [],
      tense_ids: ["tense_futur_anterieur"],
      summary: "Future of auxiliary (aurai/serai) + past participle. Expresses an action that will be completed before another future action.",
      explanation: "'Quand j'aurai fini mes études, je trouverai un travail' (When I have finished my studies, I will find a job).",
      formation: {
        steps: ["Conjugate avoir or être in futur simple", "Add past participle"],
        patterns: ["[SUBJECT] + aurai/serai + [PARTICIPE PASSÉ]"],
        endings: {},
      },
      usage_conditions: ["Action completed before another future event"],
      trigger_words: ["quand", "dès que", "aussitôt que", "lorsque"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("futur_simple_formation_and_stems")],
      example_ids: [makeExampleId("futur_anterieur", 1)],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 4, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 9, page_printed: 77, context_type: "grammar_explanation" }],
      tags: ["future_perfect", "compound"],
    },
    {
      id: makeRuleId("futur_after_temporal_conjunctions"),
      type: "grammar_rule",
      title: "Use of future tenses after temporal conjunctions (quand, dès que, etc.)",
      short_label: "Future after quand/dès que",
      grammar_category: "syntax",
      concept_ids: [],
      tense_ids: ["tense_futur_simple", "tense_futur_anterieur"],
      summary: "French requires the FUTURE tense after quand, lorsque, dès que, aussitôt que, tant que when referring to future events, unlike English which uses present.",
      explanation: "In English: 'When I arrive, I will call you' (present arrive). In French: 'Quand j'arriverai, je t'appellerai' (future arriverai).",
      formation: null,
      usage_conditions: ["Time clauses referring to the future"],
      trigger_words: ["quand", "lorsque", "dès que", "aussitôt que", "tant que"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Quand j'arrive demain, je te verrai", correct: "Quand j'arriverai demain, je te verrai", explanation: "Use future tense after quand for future time." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("conjunction_futur", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 9, page_printed: 79, context_type: "grammar_explanation" }],
      tags: ["essential", "syntax", "conjunctions", "future"],
    },
  ];

  const verbs: Verb[] = [];
  const conjugations: Conjugation[] = [];
  const expressions: Expression[] = [
    {
      id: makeExpressionId("des que"),
      type: "expression",
      expression_type: "connector",
      canonical_form: "dès que",
      display_form: "dès que",
      english: ["as soon as"],
      base_verb_ids: [],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "dès que [CLAUSE]",
      pattern_slots: [],
      transformations: [],
      variants: ["aussitôt que"],
      function_ids: [],
      usage_notes: ["Takes indicative; requires future tense when referring to future"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("conjunction_futur", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 9, page_printed: 79, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("futur_after_temporal_conjunctions")] },
      tags: ["essential", "connector", "time"],
    },
  ];
  const vocabulary: Vocabulary[] = [];

  const examples: Example[] = [
    {
      id: makeExampleId("futur_simple", 1),
      type: "example",
      french: "Demain, je partirai pour Lyon à la première heure.",
      english: "Tomorrow, I will leave for Lyon at the earliest hour.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "partirai", role: "future_verb" }] },
      relations: { verbs: [makeVerbId("partir")], tenses: ["tense_futur_simple"] },
      cloze_candidates: ["partirai"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 9, page_printed: 72, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("futur_anterieur", 1),
      type: "example",
      french: "Quand nous aurons terminé ce travail, nous sortirons.",
      english: "When we have finished this work, we will go out.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "aurons terminé", role: "future_perfect" }, { text: "sortirons", role: "future_simple" }] },
      relations: { verbs: [makeVerbId("sortir")], tenses: ["tense_futur_anterieur", "tense_futur_simple"] },
      cloze_candidates: ["aurons terminé"],
      study: { difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 9, page_printed: 77, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("conjunction_futur", 1),
      type: "example",
      french: "Dès qu'il arrivera, nous commencerons la réunion.",
      english: "As soon as he arrives, we will start the meeting.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "arrivera", role: "future_after_conjunction" }] },
      relations: { expressions: [makeExpressionId("des que")], tenses: ["tense_futur_simple"] },
      cloze_candidates: ["arrivera", "commencerons"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 9, page_printed: 79, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "The futur simple and the futur antérieur",
    section_ids: sections.map((s) => s.id),
    concept_ids: [],
    tense_ids: ["tense_futur_simple", "tense_futur_anterieur"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 72, page_end_printed: 80, page_start_pdf: 86, page_end_pdf: 94 },
    tags: ["futur_simple", "futur_anterieur", "future_tenses", "conjunctions"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}

// =======================================================================
// CHAPTER 10: The plus-que-parfait
// =======================================================================
export function buildChapter10(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 10;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 81 && (p.printed_page || 0) <= 86);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "Formation of the plus-que-parfait"),
    chapter_id: chId,
    order: 1,
    title: "Formation of the plus-que-parfait",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_plus_que_parfait"],
    grammar_rule_ids: [makeRuleId("plus_que_parfait_formation_rule")],
    verb_ids: [],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("pqp", 1)],
    exercise_ids: [exercises[0]?.id, exercises[1]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 81, page_end_printed: 83, page_start_pdf: 95, page_end_pdf: 97 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "Use of the plus-que-parfait"),
    chapter_id: chId,
    order: 2,
    title: "Use of the plus-que-parfait",
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_plus_que_parfait"],
    grammar_rule_ids: [makeRuleId("plus_que_parfait_usage_and_si_seulement")],
    verb_ids: [],
    expression_ids: [makeExpressionId("si seulement + plus-que-parfait")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("pqp_use", 1)],
    exercise_ids: [exercises[2]?.id, exercises[3]?.id, exercises[4]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 83, page_end_printed: 86, page_start_pdf: 97, page_end_pdf: 100 },
  };

  const sections = [sec1, sec2];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("plus_que_parfait_formation_rule"),
      type: "grammar_rule",
      title: "Formation of the plus-que-parfait (pluperfect)",
      short_label: "plus-que-parfait formation",
      grammar_category: "tense_formation",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_plus_que_parfait"],
      summary: "Imparfait of auxiliary (avais/étais) + past participle.",
      explanation: "Formed with the imparfait of avoir or être followed by the past participle: 'J'avais parlé', 'Elle était partie'. Agreement rules mirror the passé composé.",
      formation: {
        steps: ["Conjugate avoir/être in imparfait (avais, avais, avait, avions, aviez, avaient / étais, étais, était, étions, étiez, étaient)", "Add past participle"],
        patterns: ["[SUBJECT] + avais/étais + [PARTICIPE PASSÉ]"],
        endings: {},
      },
      usage_conditions: ["Actions that took place prior to another past action"],
      trigger_words: ["déjà", "avant", "si seulement"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("pqp", 1)],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 4, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 10, page_printed: 81, context_type: "grammar_explanation" }],
      tags: ["pluperfect", "past", "formation"],
    },
    {
      id: makeRuleId("plus_que_parfait_usage_and_si_seulement"),
      type: "grammar_rule",
      title: "Uses of the plus-que-parfait and Si seulement",
      short_label: "plus-que-parfait uses",
      grammar_category: "tense_usage",
      concept_ids: ["concept_past_time"],
      tense_ids: ["tense_plus_que_parfait"],
      summary: "1. Prior past action. 2. Regret with 'Si seulement' (If only...). 3. Past conditional clause (Si + plus-que-parfait).",
      explanation: "- Prior past: 'Il avait déjà mangé quand je suis arrivé' (He had already eaten when I arrived).\n- Regret: 'Si seulement j'avais su!' (If only I had known!).",
      formation: null,
      usage_conditions: ["Narrating past sequences", "Expressing past regrets"],
      trigger_words: ["si seulement"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("plus_que_parfait_formation_rule")],
      example_ids: [makeExampleId("pqp_use", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 10, page_printed: 83, context_type: "grammar_explanation" }],
      tags: ["pluperfect", "past_narrative", "regrets"],
    },
  ];

  const verbs: Verb[] = [];
  const conjugations: Conjugation[] = [];
  const expressions: Expression[] = [
    {
      id: makeExpressionId("si seulement + plus-que-parfait"),
      type: "expression",
      expression_type: "sentence_starter",
      canonical_form: "si seulement + plus-que-parfait",
      display_form: "Si seulement + verbe au plus-que-parfait!",
      english: ["If only...!"],
      base_verb_ids: [],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "Si seulement [SUBJECT] [PLUS_QUE_PARFAIT]!",
      pattern_slots: [{ name: "clause", display: "action passée regrettée", type: "clause", required: true }],
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: ["Expresses regret about an unchangeable past event"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("pqp_use", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["emotions", "conversation"] },
      frequency: { book_occurrences: 2 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 10, page_printed: 83, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("plus_que_parfait_usage_and_si_seulement")] },
      tags: ["essential", "regret"],
    },
  ];
  const vocabulary: Vocabulary[] = [];

  const examples: Example[] = [
    {
      id: makeExampleId("pqp", 1),
      type: "example",
      french: "Il avait déjà fini ses devoirs quand ses amis sont arrivés.",
      english: "He had already finished his homework when his friends arrived.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "avait déjà fini", role: "pluperfect" }] },
      relations: { verbs: [makeVerbId("finir")], tenses: ["tense_plus_que_parfait"] },
      cloze_candidates: ["avait fini"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 10, page_printed: 81, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("pqp_use", 1),
      type: "example",
      french: "Si seulement nous avions écouté ses conseils!",
      english: "If only we had listened to his advice!",
      source_type: "book",
      annotations: { focus_spans: [{ text: "Si seulement nous avions écouté", role: "regret" }] },
      relations: { expressions: [makeExpressionId("si seulement + plus-que-parfait")], tenses: ["tense_plus_que_parfait"] },
      cloze_candidates: ["avions écouté"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 10, page_printed: 83, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "The plus-que-parfait",
    section_ids: sections.map((s) => s.id),
    concept_ids: ["concept_past_time"],
    tense_ids: ["tense_plus_que_parfait"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 81, page_end_printed: 86, page_start_pdf: 95, page_end_pdf: 100 },
    tags: ["plus_que_parfait", "pluperfect", "past_tenses"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}
