import { ChapterExtractionBundle } from "./chapter-types";
import { RawPage } from "./extract-pages";
import { extractChapterExercises } from "./extract-chapter";
import {
  GrammarRule,
  Verb,
  Conjugation,
  Expression,
  Vocabulary,
  Example,
  Chapter,
  Section,
} from "../src/lib/dataset/schemas";
import {
  makeChapterId,
  makeSectionId,
  makeRuleId,
  makeVerbId,
  makeConjugationId,
  makeVocabId,
  makeExpressionId,
  makeExampleId,
} from "../src/lib/dataset/ids";

// =======================================================================
// CHAPTER 2: The present tense of -ir and -re verbs
// =======================================================================
export function buildChapter2(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 2;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 13 && (p.printed_page || 0) <= 23);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "-ir verbs in the present"),
    chapter_id: chId,
    order: 1,
    title: "-ir verbs in the present",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("regular_ir_verbs_finir_present"), makeRuleId("irregular_ir_verbs_partir_present")],
    verb_ids: [
      makeVerbId("finir"),
      makeVerbId("choisir"),
      makeVerbId("remplir"),
      makeVerbId("obéir"),
      makeVerbId("réussir"),
      makeVerbId("partir"),
      makeVerbId("dormir"),
      makeVerbId("sortir"),
      makeVerbId("servir"),
      makeVerbId("sentir"),
      makeVerbId("mentir"),
      makeVerbId("ouvrir"),
      makeVerbId("offrir"),
      makeVerbId("couvrir"),
      makeVerbId("découvrir"),
      makeVerbId("souffrir"),
      makeVerbId("courir"),
      makeVerbId("mourir"),
    ],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("finir", 1), makeExampleId("partir", 1)],
    exercise_ids: [exercises[0]?.id, exercises[1]?.id, exercises[2]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 13, page_end_printed: 16, page_start_pdf: 27, page_end_pdf: 30 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "-re verbs in the present"),
    chapter_id: chId,
    order: 2,
    title: "-re verbs in the present",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("regular_re_verbs_vendre_present"), makeRuleId("prendre_group_present")],
    verb_ids: [
      makeVerbId("vendre"),
      makeVerbId("attendre"),
      makeVerbId("descendre"),
      makeVerbId("entendre"),
      makeVerbId("perdre"),
      makeVerbId("rendre"),
      makeVerbId("répondre"),
      makeVerbId("prendre"),
      makeVerbId("apprendre"),
      makeVerbId("comprendre"),
      makeVerbId("surprendre"),
      makeVerbId("entreprendre"),
    ],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("vendre", 1), makeExampleId("prendre", 1)],
    exercise_ids: [exercises[3]?.id, exercises[4]?.id, exercises[5]?.id, exercises[6]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 16, page_end_printed: 19, page_start_pdf: 30, page_end_pdf: 33 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "The interrogative form"),
    chapter_id: chId,
    order: 3,
    title: "The interrogative form",
    concept_ids: ["concept_interrogation"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("interrogative_formation_methods"), makeRuleId("interrogative_inversion_rules")],
    verb_ids: [],
    expression_ids: [makeExpressionId("est ce que")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("question", 1)],
    exercise_ids: [exercises[7]?.id, exercises[8]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 19, page_end_printed: 21, page_start_pdf: 33, page_end_pdf: 35 },
  };

  const sec4 = {
    id: makeSectionId(chNum, 4, "The negative form"),
    chapter_id: chId,
    order: 4,
    title: "The negative form",
    concept_ids: ["concept_negation"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("negative_form_ne_pas"), makeRuleId("negative_words_jamais_plus_rien_personne"), makeRuleId("ne_ni_ni_construction")],
    verb_ids: [],
    expression_ids: [
      makeExpressionId("ne ... pas"),
      makeExpressionId("ne ... jamais"),
      makeExpressionId("ne ... plus"),
      makeExpressionId("ne ... rien"),
      makeExpressionId("ne ... personne"),
      makeExpressionId("ne ... ni ... ni"),
    ],
    vocabulary_ids: [],
    example_ids: [makeExampleId("negation", 1)],
    exercise_ids: [exercises[9]?.id, exercises[10]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 21, page_end_printed: 23, page_start_pdf: 35, page_end_pdf: 37 },
  };

  const sections = [sec1, sec2, sec3, sec4];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("regular_ir_verbs_finir_present"),
      type: "grammar_rule",
      title: "Regular -ir verbs (finir type) in the present tense",
      short_label: "Regular -ir (finir)",
      grammar_category: "verb_formation",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Drop -ir and add -is, -is, -it, -issons, -issez, -issent (with -iss- infix in plural).",
      explanation: "Regular 2nd group verbs (finir, choisir, remplir, réussir, obéir) take endings -is, -is, -it in singular, and insert -iss- before plural endings: -issons, -issez, -issent.",
      formation: {
        steps: ["Drop -ir", "Singular: add -is, -is, -it", "Plural: add -issons, -issez, -issent"],
        patterns: ["stem + -is/-is/-it/-issons/-issez/-issent"],
        endings: { je: "is", tu: "is", il_elle_on: "it", nous: "issons", vous: "issez", ils_elles: "issent" },
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: ["Irregular short -ir verbs (partir, sortir) do not take -iss-"],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [makeRuleId("irregular_ir_verbs_partir_present")],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("finir", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 13, context_type: "grammar_explanation" }],
      tags: ["essential", "ir_verbs"],
    },
    {
      id: makeRuleId("irregular_ir_verbs_partir_present"),
      type: "grammar_rule",
      title: "Irregular short -ir verbs (partir, sortir, dormir type)",
      short_label: "Short -ir (partir)",
      grammar_category: "verb_formation",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Singular stem drops the final consonant: je pars, tu pars, il part; plural stem keeps it: nous partons, vous partez, ils partent.",
      explanation: "Verbs like partir (je pars, nous partons), sortir (je sors, nous sortons), dormir (je dors, nous dormons), servir (je sers, nous servons), sentir (je sens, nous sentons), mentir (je mens, nous mentons) drop the final consonant of the root in the singular and restore it in the plural.",
      formation: {
        steps: ["Singular: drop last stem consonant + -s, -s, -t", "Plural: full stem + -ons, -ez, -ent"],
        patterns: ["short_stem + -s/-s/-t, full_stem + -ons/-ez/-ent"],
        endings: { je: "s", tu: "s", il_elle_on: "t", nous: "ons", vous: "ez", ils_elles: "ent" },
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [makeRuleId("regular_ir_verbs_finir_present")],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("partir", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 14, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs", "ir_verbs"],
    },
    {
      id: makeRuleId("regular_re_verbs_vendre_present"),
      type: "grammar_rule",
      title: "Regular -re verbs (vendre type) in the present tense",
      short_label: "Regular -re (vendre)",
      grammar_category: "verb_formation",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Drop -re and add -s, -s, - (nothing / keeps d), -ons, -ez, -ent.",
      explanation: "Regular -re verbs (vendre, attendre, descendre, entendre, perdre, rendre, répondre) add -s, -s, nothing in the 3rd person singular (il vend), and -ons, -ez, -ent in plural.",
      formation: {
        steps: ["Drop -re", "Add -s, -s, (no ending), -ons, -ez, -ent"],
        patterns: ["stem + -s/-s/-/-ons/-ez/-ent"],
        endings: { je: "s", tu: "s", il_elle_on: "", nous: "ons", vous: "ez", ils_elles: "ent" },
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: ["prendre group, mettre, battre, etc. have different patterns"],
      restrictions: [],
      notes: ["Note that il/elle/on has NO ending added; it simply ends in the stem 'd' (il vend, elle attend)."],
      common_mistakes: [{ wrong: "il vendt", correct: "il vend", explanation: "No 't' is added to 3rd person singular when stem ends in d." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("vendre", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 16, context_type: "grammar_explanation" }],
      tags: ["essential", "re_verbs"],
    },
    {
      id: makeRuleId("prendre_group_present"),
      type: "grammar_rule",
      title: "Conjugation of prendre and its compounds in the present tense",
      short_label: "prendre group present",
      grammar_category: "verb_formation",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Prendre drops 'd' in nous/vous (prenons, prenez) and doubles 'n' in ils (prennent).",
      explanation: "Verbs of the prendre family (prendre, apprendre, comprendre, surprendre, entreprendre) conjugate: je prends, tu prends, il prend, nous prenons, vous prenez, ils prennent.",
      formation: {
        steps: ["Singular: prend- + -s, -s, -", "Nous/vous: pren- + -ons, -ez", "Ils/elles: prenn- + -ent"],
        patterns: ["prends, prends, prend, prenons, prenez, prennent"],
        endings: {},
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "ils prendent / ils prenent", correct: "ils prennent", explanation: "Double 'n' in ils/elles prennent." }],
      contrast_with_rule_ids: [makeRuleId("regular_re_verbs_vendre_present")],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("prendre", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 17, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs"],
    },
    {
      id: makeRuleId("interrogative_formation_methods"),
      type: "grammar_rule",
      title: "Three ways to ask a question in French",
      short_label: "Question formation",
      grammar_category: "syntax",
      concept_ids: ["concept_interrogation"],
      tense_ids: ["tense_present_indicative"],
      summary: "Questions can be formed by intonation (informal), 'est-ce que' (standard), or subject-verb inversion (formal).",
      explanation: "1. Intonation: Tu parles français? (voice rises at end)\n2. Est-ce que: Est-ce que tu parles français?\n3. Inversion: Parles-tu français?",
      formation: {
        steps: ["Intonation: statement + rising pitch + ?", "Est-ce que: Est-ce que + statement + ?", "Inversion: Verb-subject pronoun + ?"],
        patterns: ["Est-ce que [S] [V]?", "[V]-[PRONOUN]?"],
        endings: {},
      },
      usage_conditions: ["Spoken informal, standard, and formal writing"],
      trigger_words: ["est-ce que"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Add '-t-' in inversion when 3rd person singular verb ends in a vowel before il/elle/on: Parle-t-il? Aime-t-elle?"],
      common_mistakes: [{ wrong: "Parle il?", correct: "Parle-t-il?", explanation: "Insert euphonic -t- between two vowel sounds in inversion." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("question", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 19, context_type: "grammar_explanation" }],
      tags: ["essential", "questions"],
    },
    {
      id: makeRuleId("negative_form_ne_pas"),
      type: "grammar_rule",
      title: "Basic negation with ne ... pas",
      short_label: "ne ... pas",
      grammar_category: "negation",
      concept_ids: ["concept_negation"],
      tense_ids: ["tense_present_indicative"],
      summary: "Place 'ne' before the conjugated verb and 'pas' after it (n' before vowels).",
      explanation: "To make a sentence negative, place 'ne' (or 'n'') before the conjugated verb and 'pas' directly after: 'Il ne parle pas anglais'. In compound tenses, 'pas' precedes the past participle: 'Il n'a pas parlé'.",
      formation: {
        steps: ["Place ne / n' before conjugated verb", "Place pas after conjugated verb"],
        patterns: ["[SUBJECT] + ne + [VERBE] + pas"],
        endings: {},
      },
      usage_conditions: ["Negating any statement"],
      trigger_words: ["ne", "pas"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Indefinite and partitive articles (un, une, des, du, de la) change to 'de / d'' in a direct negative, except with être."],
      common_mistakes: [{ wrong: "Je ne veux pas du vin", correct: "Je ne veux pas de vin", explanation: "Partitive changes to 'de' in negation." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [makeRuleId("negative_words_jamais_plus_rien_personne")],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("negation", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 21, context_type: "grammar_explanation" }],
      tags: ["essential", "negation"],
    },
    {
      id: makeRuleId("negative_words_jamais_plus_rien_personne"),
      type: "grammar_rule",
      title: "Negative adverbs: ne... jamais, ne... plus, ne... rien, ne... personne",
      short_label: "Complex negation",
      grammar_category: "negation",
      concept_ids: ["concept_negation"],
      tense_ids: ["tense_present_indicative"],
      summary: "Replace 'pas' with 'jamais' (never), 'plus' (no more/longer), 'rien' (nothing), 'personne' (nobody).",
      explanation: "- ne... jamais: never\n- ne... plus: no longer, not anymore\n- ne... rien: nothing\n- ne... personne: nobody / no one\nNote: 'personne' follows the past participle in compound tenses (Je n'ai vu personne), whereas 'rien', 'plus', 'jamais' precede it (Je n'ai rien vu).",
      formation: {
        steps: ["Place ne before verb", "Place negative word in place of pas"],
        patterns: ["ne + [VERB] + jamais/plus/rien/personne"],
        endings: {},
      },
      usage_conditions: ["Specific negative meanings"],
      trigger_words: ["jamais", "plus", "rien", "personne"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Never combine 'pas' with 'jamais', 'plus', or 'rien' in standard French."],
      common_mistakes: [{ wrong: "Je ne sais pas rien", correct: "Je ne sais rien", explanation: "Do not use 'pas' with 'rien'." }],
      contrast_with_rule_ids: [makeRuleId("negative_form_ne_pas")],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("negative_form_ne_pas")],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 22, context_type: "grammar_explanation" }],
      tags: ["essential", "negation"],
    },
  ];

  const verbsList2 = [
    { inf: "finir", en: ["to finish", "to end"], group: "2nd_group", part: "fini" },
    { inf: "choisir", en: ["to choose"], group: "2nd_group", part: "choisi" },
    { inf: "remplir", en: ["to fill", "to fill out"], group: "2nd_group", part: "rempli" },
    { inf: "obéir", en: ["to obey"], group: "2nd_group", part: "obéi" },
    { inf: "réussir", en: ["to succeed"], group: "2nd_group", part: "réussi" },
    { inf: "partir", en: ["to leave", "to depart"], group: "3rd_group", reg: "irregular", part: "parti" },
    { inf: "dormir", en: ["to sleep"], group: "3rd_group", reg: "irregular", part: "dormi" },
    { inf: "sortir", en: ["to go out", "to exit"], group: "3rd_group", reg: "irregular", part: "sorti" },
    { inf: "servir", en: ["to serve"], group: "3rd_group", reg: "irregular", part: "servi" },
    { inf: "sentir", en: ["to feel", "to smell"], group: "3rd_group", reg: "irregular", part: "senti" },
    { inf: "mentir", en: ["to lie"], group: "3rd_group", reg: "irregular", part: "menti" },
    { inf: "ouvrir", en: ["to open"], group: "3rd_group", reg: "irregular", part: "ouvert" },
    { inf: "offrir", en: ["to offer", "to give as a gift"], group: "3rd_group", reg: "irregular", part: "offert" },
    { inf: "couvrir", en: ["to cover"], group: "3rd_group", reg: "irregular", part: "couvert" },
    { inf: "découvrir", en: ["to discover"], group: "3rd_group", reg: "irregular", part: "découvert" },
    { inf: "souffrir", en: ["to suffer"], group: "3rd_group", reg: "irregular", part: "souffert" },
    { inf: "courir", en: ["to run"], group: "3rd_group", reg: "irregular", part: "couru" },
    { inf: "mourir", en: ["to die"], group: "3rd_group", reg: "irregular", part: "mort" },
    { inf: "vendre", en: ["to sell"], group: "3rd_group", part: "vendu" },
    { inf: "attendre", en: ["to wait", "to wait for"], group: "3rd_group", part: "attendu" },
    { inf: "descendre", en: ["to go down", "to descend"], group: "3rd_group", part: "descendu" },
    { inf: "entendre", en: ["to hear"], group: "3rd_group", part: "entendu" },
    { inf: "perdre", en: ["to lose"], group: "3rd_group", part: "perdu" },
    { inf: "rendre", en: ["to give back", "to return"], group: "3rd_group", part: "rendu" },
    { inf: "répondre", en: ["to answer", "to reply"], group: "3rd_group", part: "répondu" },
    { inf: "prendre", en: ["to take"], group: "3rd_group", reg: "irregular", part: "pris" },
    { inf: "apprendre", en: ["to learn"], group: "3rd_group", reg: "irregular", part: "appris" },
    { inf: "comprendre", en: ["to understand"], group: "3rd_group", reg: "irregular", part: "compris" },
    { inf: "surprendre", en: ["to surprise"], group: "3rd_group", reg: "irregular", part: "surpris" },
    { inf: "entreprendre", en: ["to undertake"], group: "3rd_group", reg: "irregular", part: "entrepris" },
  ];

  const verbs: Verb[] = verbsList2.map((v) => {
    const vId = makeVerbId(v.inf);
    return {
      id: vId,
      type: "verb",
      infinitive: v.inf,
      display_form: v.inf,
      english: v.en,
      senses: [{ sense_id: `${vId}_s1`, english: v.en, usage_contexts: [], example_ids: [] }],
      verb_group: (v.group as any) || "3rd_group",
      regularity: (v.reg as any) || "regular",
      pronominal: false,
      transitivity: ["transitive", "intransitive"],
      auxiliary: ["partir", "sortir", "descendre", "mourir"].includes(v.inf) ? "etre" : "avoir",
      past_participle: v.part || null,
      present_participle: null,
      conjugation_ids: [makeConjugationId(vId, "tense_present_indicative")],
      expression_ids: [],
      complement_frame_ids: [],
      related_verb_ids: [],
      contrast_verb_ids: [],
      confused_with_ids: [],
      word_family_ids: [],
      study: {
        learning_priority: ["finir", "partir", "sortir", "vendre", "attendre", "prendre", "apprendre", "comprendre"].includes(v.inf) ? 5 : 4,
        usefulness: 5,
        difficulty: v.reg === "irregular" ? 3 : 2,
      },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 1 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 13, context_type: "grammar_explanation" }],
      tags: ["ir_re_verbs", "chapter_02"],
    };
  });

  const conjugations: Conjugation[] = [
    {
      id: makeConjugationId("verb_finir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("finir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je finis",
        tu: "tu finis",
        il_elle_on: "il/elle/on finit",
        nous: "nous finissons",
        vous: "vous finissez",
        ils_elles: "ils/elles finissent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: ["-iss- infix in plural forms"],
      example_ids: [makeExampleId("finir", 1)],
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 13, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_partir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("partir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je pars",
        tu: "tu pars",
        il_elle_on: "il/elle/on part",
        nous: "nous partons",
        vous: "vous partez",
        ils_elles: "ils/elles partent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("partir", 1)],
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 14, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_vendre", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("vendre"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je vends",
        tu: "tu vends",
        il_elle_on: "il/elle/on vend",
        nous: "nous vendons",
        vous: "vous vendez",
        ils_elles: "ils/elles vendent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("vendre", 1)],
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 16, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_prendre", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("prendre"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je prends",
        tu: "tu prends",
        il_elle_on: "il/elle/on prend",
        nous: "nous prenons",
        vous: "vous prenez",
        ils_elles: "ils/elles prennent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: ["drops 'd' in plural, doubles 'n' in 3rd pl."],
      example_ids: [makeExampleId("prendre", 1)],
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 17, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
  ];

  const expressions: Expression[] = [
    {
      id: makeExpressionId("est ce que"),
      type: "expression",
      expression_type: "sentence_starter",
      canonical_form: "est-ce que",
      display_form: "est-ce que",
      english: ["(question marker)", "is it that"],
      base_verb_ids: [makeVerbId("être")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "Est-ce que + [STATEMENT]?",
      pattern_slots: [{ name: "statement", display: "proposition", type: "clause", required: true }],
      transformations: [],
      variants: ["est-ce qu'"],
      function_ids: [],
      usage_notes: ["Universal standard question starter"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("question", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["conversation", "questions"] },
      frequency: { book_occurrences: 8 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 19, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("interrogative_formation_methods")] },
      tags: ["essential", "question"],
    },
    {
      id: makeExpressionId("ne ... pas"),
      type: "expression",
      expression_type: "functional_phrase",
      canonical_form: "ne ... pas",
      display_form: "ne ... pas",
      english: ["not", "do not"],
      base_verb_ids: [],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "ne + [VERB] + pas",
      pattern_slots: [{ name: "verb", display: "verbe conjugué", type: "verb", required: true }],
      transformations: [],
      variants: ["n' ... pas"],
      function_ids: [],
      usage_notes: ["Standard negation enclosing conjugated verb"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("negation", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 10 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 21, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("negative_form_ne_pas")] },
      tags: ["essential", "negation"],
    },
    {
      id: makeExpressionId("ne ... jamais"),
      type: "expression",
      expression_type: "functional_phrase",
      canonical_form: "ne ... jamais",
      display_form: "ne ... jamais",
      english: ["never"],
      base_verb_ids: [],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "ne + [VERB] + jamais",
      pattern_slots: [],
      transformations: [],
      variants: ["n' ... jamais"],
      function_ids: [],
      usage_notes: ["Opposite of toujours or déjà"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 22, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("negative_words_jamais_plus_rien_personne")] },
      tags: ["essential", "negation"],
    },
  ];

  const vocabulary: Vocabulary[] = [
    {
      id: makeVocabId("formulaire"),
      type: "vocabulary",
      canonical_form: "formulaire",
      display_form: "le formulaire",
      french: "formulaire",
      english: ["form", "application form"],
      part_of_speech: "noun",
      noun: { gender: "masculine", article: "le", plural: "formulaires" },
      senses: [{ sense_id: "vocab_formulaire_s1", english: ["form"], usage_contexts: [], example_ids: [] }],
      semantic_domains: ["administration"],
      word_family_ids: [],
      collocation_expression_ids: [],
      false_friend: false,
      cognate: true,
      study: { learning_priority: 4, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 2 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 13, context_type: "vocabulary_box" }],
      tags: ["noun", "chapter_02"],
    },
    {
      id: makeVocabId("reponse"),
      type: "vocabulary",
      canonical_form: "réponse",
      display_form: "la réponse",
      french: "réponse",
      english: ["answer", "reply", "response"],
      part_of_speech: "noun",
      noun: { gender: "feminine", article: "la", plural: "réponses" },
      senses: [{ sense_id: "vocab_reponse_s1", english: ["answer", "reply"], usage_contexts: [], example_ids: [] }],
      semantic_domains: ["communication"],
      word_family_ids: [makeVerbId("répondre")],
      collocation_expression_ids: [],
      false_friend: false,
      cognate: true,
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 2 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 16, context_type: "vocabulary_box" }],
      tags: ["essential", "noun", "chapter_02"],
    },
  ];

  const examples: Example[] = [
    {
      id: makeExampleId("finir", 1),
      type: "example",
      french: "Nous finissons notre travail à dix-huit heures.",
      english: "We finish our work at six o'clock.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "finissons", role: "verb" }] },
      relations: { verbs: [makeVerbId("finir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["finissons"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 13, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("partir", 1),
      type: "example",
      french: "Ils partent en vacances demain matin.",
      english: "They are leaving on vacation tomorrow morning.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "partent", role: "verb" }] },
      relations: { verbs: [makeVerbId("partir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["partent"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 14, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("vendre", 1),
      type: "example",
      french: "Elle vend des fleurs sur le marché.",
      english: "She sells flowers at the market.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "vend", role: "verb" }] },
      relations: { verbs: [makeVerbId("vendre")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["vend"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 16, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("prendre", 1),
      type: "example",
      french: "Elle prend le métro tous les jours.",
      english: "She takes the subway every day.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "prend", role: "verb" }] },
      relations: { verbs: [makeVerbId("prendre")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["prend"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 17, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("question", 1),
      type: "example",
      french: "Est-ce qu'elle apprend le portugais?",
      english: "Is she learning Portuguese?",
      source_type: "book",
      annotations: { focus_spans: [{ text: "Est-ce qu'", role: "question_marker" }] },
      relations: { verbs: [makeVerbId("apprendre")], expressions: [makeExpressionId("est ce que")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["Est-ce qu'"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 20, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("negation", 1),
      type: "example",
      french: "Il ne parle pas italien.",
      english: "He does not speak Italian.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "ne parle pas", role: "negation" }] },
      relations: { verbs: [makeVerbId("parler")], expressions: [makeExpressionId("ne ... pas")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["ne", "pas"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 2, page_printed: 21, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "The present tense of -ir and -re verbs",
    section_ids: sections.map((s) => s.id),
    concept_ids: ["concept_interrogation", "concept_negation"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 13, page_end_printed: 23, page_start_pdf: 27, page_end_pdf: 37 },
    tags: ["ir_verbs", "re_verbs", "negation", "questions", "present_tense"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}
