import { ChapterExtractionBundle } from "./chapter-types";
import { RawPage } from "./extract-pages";
import { extractChapterExercises } from "./extract-chapter";
import {
  GrammarRule,
  Verb,
  Conjugation,
  Expression,
  Vocabulary,
  Example,
  Chapter,
  Section,
} from "../src/lib/dataset/schemas";
import {
  makeChapterId,
  makeSectionId,
  makeRuleId,
  makeVerbId,
  makeConjugationId,
  makeVocabId,
  makeExpressionId,
  makeExampleId,
} from "../src/lib/dataset/ids";

// =======================================================================
// CHAPTER 5: Devoir and its many facets
// =======================================================================
export function buildChapter5(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 5;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 43 && (p.printed_page || 0) <= 48);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "The verb devoir (to have to, must)"),
    chapter_id: chId,
    order: 1,
    title: "The verb devoir (to have to, must)",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("verb_devoir_meanings_and_nuances")],
    verb_ids: [makeVerbId("devoir")],
    expression_ids: [makeExpressionId("devoir de l'argent"), makeExpressionId("devoir + infinitif")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("devoir", 1)],
    exercise_ids: [exercises[0]?.id, exercises[1]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 43, page_end_printed: 45, page_start_pdf: 57, page_end_pdf: 59 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "Il y a (there is, there are)"),
    chapter_id: chId,
    order: 2,
    title: "Il y a (there is, there are)",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("il_y_a_existential_and_time_uses")],
    verb_ids: [],
    expression_ids: [makeExpressionId("il y a"), makeExpressionId("il n'y a pas de"), makeExpressionId("y a-t-il")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("il_y_a", 1)],
    exercise_ids: [exercises[2]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 46, page_end_printed: 46, page_start_pdf: 60, page_end_pdf: 60 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "Il s'agit de (it is a matter of)"),
    chapter_id: chId,
    order: 3,
    title: "Il s'agit de (it is a matter of, it's about)",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("il_s_agit_de_impersonal_construction")],
    verb_ids: [makeVerbId("agir")],
    expression_ids: [makeExpressionId("il s'agit de"), makeExpressionId("de quoi s'agit-il")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("il_s_agit_de", 1)],
    exercise_ids: [],
    source: { page_start_printed: 46, page_end_printed: 46, page_start_pdf: 60, page_end_pdf: 60 },
  };

  const sec4 = {
    id: makeSectionId(chNum, 4, "Verbs ending in -eindre and -aindre"),
    chapter_id: chId,
    order: 4,
    title: "Verbs ending in -eindre and -aindre",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("eindre_aindre_verbs_conjugation")],
    verb_ids: [
      makeVerbId("peindre"),
      makeVerbId("craindre"),
      makeVerbId("plaindre"),
      makeVerbId("feindre"),
      makeVerbId("éteindre"),
      makeVerbId("atteindre"),
      makeVerbId("joindre"),
      makeVerbId("contraindre"),
      makeVerbId("teindre"),
      makeVerbId("ceindre"),
    ],
    expression_ids: [makeExpressionId("se plaindre de"), makeExpressionId("craindre le pire")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("peindre", 1), makeExampleId("craindre", 1)],
    exercise_ids: [exercises[3]?.id, exercises[4]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 46, page_end_printed: 48, page_start_pdf: 60, page_end_pdf: 62 },
  };

  const sections = [sec1, sec2, sec3, sec4];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("verb_devoir_meanings_and_nuances"),
      type: "grammar_rule",
      title: "Meanings and nuances of the verb devoir",
      short_label: "devoir nuances",
      grammar_category: "modal_verbs",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Devoir expresses obligation (must/have to), owing money/favors, probability/supposition, and should (conditionnel).",
      explanation: "1. Obligation: 'Tu dois partir' (You must leave).\n2. Owing: 'Je vous dois dix euros' (I owe you 10 euros).\n3. Probability: 'Il doit être midi' (It must be noon / It probably is noon).\n4. Advice / Should (in conditional): 'Vous devriez appeler' (You should call).",
      formation: {
        steps: ["je dois, tu dois, il doit, nous devons, vous devez, ils doivent"],
        patterns: ["irregular"],
        endings: {},
      },
      usage_conditions: ["Obligation", "Debt", "Probability", "Advice"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("devoir", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 43, context_type: "grammar_explanation" }],
      tags: ["essential", "modal_verbs"],
    },
    {
      id: makeRuleId("il_y_a_existential_and_time_uses"),
      type: "grammar_rule",
      title: "Existential and temporal uses of il y a",
      short_label: "il y a",
      grammar_category: "idiomatic_construction",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Means 'there is / there are' with nouns; in negation becomes 'il n'y a pas de'; inverted 'y a-t-il?'.",
      explanation: "Il y a is invariable regardless of whether singular or plural follows: 'Il y a un livre', 'Il y a des livres'. Negative form: 'Il n'y a pas de problème'.",
      formation: null,
      usage_conditions: ["Existence", "Presence", "Ago (time)"],
      trigger_words: ["il y a", "y a-t-il"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Partitive changes to 'de' in negative: 'Il n'y a pas d'eau'."],
      common_mistakes: [{ wrong: "Il y ont des livres", correct: "Il y a des livres", explanation: "Il y a never changes to plural." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("il_y_a", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "grammar_explanation" }],
      tags: ["essential", "impersonal"],
    },
    {
      id: makeRuleId("il_s_agit_de_impersonal_construction"),
      type: "grammar_rule",
      title: "The impersonal construction il s'agit de",
      short_label: "il s'agit de",
      grammar_category: "idiomatic_construction",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Translates to 'it is about / it is a matter of / it concerns'. Always uses impersonal subject 'il'.",
      explanation: "'Dans ce livre, il s'agit du président' (In this book, it's about the president). In question form: 'De quoi s'agit-il?' (What is it about?).",
      formation: null,
      usage_conditions: ["Identifying topics, subjects of discussion, critical matters"],
      trigger_words: ["il s'agit de", "de quoi s'agit-il"],
      signal_words: [],
      exceptions: [],
      restrictions: ["Never use personal subjects (ce livre s'agit de is incorrect; say ce livre parle de or dans ce livre il s'agit de)."],
      notes: [],
      common_mistakes: [{ wrong: "Ce film s'agit d'une histoire...", correct: "Dans ce film, il s'agit d'une histoire...", explanation: "Il s'agit de is exclusively impersonal." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("il_s_agit_de", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "grammar_explanation" }],
      tags: ["essential", "impersonal", "expression"],
    },
    {
      id: makeRuleId("eindre_aindre_verbs_conjugation"),
      type: "grammar_rule",
      title: "Conjugation of verbs ending in -eindre and -aindre",
      short_label: "-eindre / -aindre verbs",
      grammar_category: "irregular_verbs",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Singular drops 'd' and takes -s, -s, -t (je crains, il craint); plural stem has 'gn' (nous craignons, ils craignent).",
      explanation: "Verbs like peindre, craindre, plaindre, feindre, éteindre, atteindre conjugate: je peins, tu peins, il peint, nous peignons, vous peignez, ils peignent. Past participle ends in -t: peint, craint, plaint, éteint.",
      formation: {
        steps: ["Singular: -s, -s, -t on -in- stem", "Plural: -gn- + -ons, -ez, -ent"],
        patterns: ["-ns, -ns, -nt, -gnons, -gnez, -gnent"],
        endings: {},
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "nous craindons", correct: "nous craignons", explanation: "Plural stem uses 'gn'." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("peindre", 1), makeExampleId("craindre", 1)],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "grammar_explanation" }],
      tags: ["irregular_verbs", "verb_pattern"],
    },
  ];

  const verbsList5 = [
    { inf: "devoir", en: ["to have to", "must", "to owe"], part: "dû" },
    { inf: "agir", en: ["to act"], part: "agi" },
    { inf: "peindre", en: ["to paint"], part: "peint" },
    { inf: "craindre", en: ["to fear", "to dread"], part: "craint" },
    { inf: "plaindre", en: ["to pity", "to feel sorry for"], part: "plaint" },
    { inf: "feindre", en: ["to feign", "to pretend"], part: "feint" },
    { inf: "éteindre", en: ["to turn off", "to extinguish"], part: "éteint" },
    { inf: "atteindre", en: ["to reach", "to attain"], part: "atteint" },
    { inf: "joindre", en: ["to join", "to attach"], part: "joint" },
    { inf: "contraindre", en: ["to compel", "to force"], part: "contraint" },
    { inf: "teindre", en: ["to dye", "to tint"], part: "teint" },
  ];

  const verbs: Verb[] = verbsList5.map((v) => {
    const vId = makeVerbId(v.inf);
    return {
      id: vId,
      type: "verb",
      infinitive: v.inf,
      display_form: v.inf,
      english: v.en,
      senses: [{ sense_id: `${vId}_s1`, english: v.en, usage_contexts: [], example_ids: [] }],
      verb_group: v.inf === "agir" ? "2nd_group" : "3rd_group",
      regularity: v.inf === "agir" ? "regular" : "irregular",
      pronominal: false,
      transitivity: ["transitive"],
      auxiliary: "avoir",
      past_participle: v.part || null,
      present_participle: null,
      conjugation_ids: [makeConjugationId(vId, "tense_present_indicative")],
      expression_ids: [],
      complement_frame_ids: [],
      related_verb_ids: [],
      contrast_verb_ids: [],
      confused_with_ids: [],
      word_family_ids: [],
      study: { learning_priority: ["devoir", "craindre", "éteindre", "atteindre"].includes(v.inf) ? 5 : 4, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 4 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 43, context_type: "grammar_explanation" }],
      tags: ["essential", "chapter_05"],
    };
  });

  const conjugations: Conjugation[] = [
    {
      id: makeConjugationId("verb_devoir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("devoir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je dois",
        tu: "tu dois",
        il_elle_on: "il/elle/on doit",
        nous: "nous devons",
        vous: "vous devez",
        ils_elles: "ils/elles doivent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("devoir", 1)],
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 43, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_craindre", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("craindre"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je crains",
        tu: "tu crains",
        il_elle_on: "il/elle/on craint",
        nous: "nous craignons",
        vous: "vous craignez",
        ils_elles: "ils/elles craignent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: ["gn in plural stem"],
      example_ids: [makeExampleId("craindre", 1)],
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
  ];

  const expressions: Expression[] = [
    {
      id: makeExpressionId("il y a"),
      type: "expression",
      expression_type: "functional_phrase",
      canonical_form: "il y a",
      display_form: "il y a",
      english: ["there is", "there are", "ago"],
      base_verb_ids: [makeVerbId("avoir")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "il y a [NOUN]",
      pattern_slots: [{ name: "item", display: "chose ou personne", type: "noun_phrase", required: true }],
      transformations: [],
      variants: ["il n'y a pas de", "y a-t-il"],
      function_ids: [],
      usage_notes: ["Invariable expression for presence and existence"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("il_y_a", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 8 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("il_y_a_existential_and_time_uses")] },
      tags: ["essential", "impersonal"],
    },
    {
      id: makeExpressionId("il s'agit de"),
      type: "expression",
      expression_type: "functional_phrase",
      canonical_form: "il s'agit de",
      display_form: "il s'agit de + nom / infinitif",
      english: ["it is a matter of", "it is about", "it concerns"],
      base_verb_ids: [makeVerbId("agir")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "il s'agit de [NOUN / INFINITIVE]",
      pattern_slots: [{ name: "subject", display: "sujet ou action", type: "noun_or_infinitive", required: true }],
      transformations: [],
      variants: ["il s'agit d'", "de quoi s'agit-il"],
      function_ids: [],
      usage_notes: ["Impersonal expression for the main theme or critical necessity"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("il_s_agit_de", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["discussion", "analysis"] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("il_s_agit_de_impersonal_construction")] },
      tags: ["essential", "impersonal"],
    },
  ];

  const vocabulary: Vocabulary[] = [];

  const examples: Example[] = [
    {
      id: makeExampleId("devoir", 1),
      type: "example",
      french: "Vous devez faire la cuisine ce soir.",
      english: "You must cook dinner tonight.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "devez", role: "verb" }] },
      relations: { verbs: [makeVerbId("devoir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["devez"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 44, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("il_y_a", 1),
      type: "example",
      french: "Il y a des livres sur la table.",
      english: "There are books on the table.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "Il y a", role: "expression" }] },
      relations: { expressions: [makeExpressionId("il y a")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["Il y a"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("il_s_agit_de", 1),
      type: "example",
      french: "Dans ce livre, il s'agit du président français.",
      english: "In this book, it is about the French president.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "il s'agit du", role: "expression" }] },
      relations: { verbs: [makeVerbId("agir")], expressions: [makeExpressionId("il s'agit de")] },
      cloze_candidates: ["il s'agit du"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 46, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("peindre", 1),
      type: "example",
      french: "Elle peint la cuisine en bleu clair.",
      english: "She is painting the kitchen light blue.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "peint", role: "verb" }] },
      relations: { verbs: [makeVerbId("peindre")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["peint"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 47, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("craindre", 1),
      type: "example",
      french: "Il craint le pire pour les résultats.",
      english: "He fears the worst for the results.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "craint", role: "verb" }] },
      relations: { verbs: [makeVerbId("craindre")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["craint"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 5, page_printed: 47, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "Devoir and its many facets",
    section_ids: sections.map((s) => s.id),
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 43, page_end_printed: 48, page_start_pdf: 57, page_end_pdf: 62 },
    tags: ["devoir", "il_y_a", "il_s_agit_de", "eindre_verbs", "aindre_verbs"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}
