import { ChapterExtractionBundle } from "./chapter-types";
import { RawPage } from "./extract-pages";
import { extractChapterExercises } from "./extract-chapter";
import {
  GrammarRule,
  Verb,
  Conjugation,
  Expression,
  Vocabulary,
  Example,
  Chapter,
  Section,
} from "../src/lib/dataset/schemas";
import {
  makeChapterId,
  makeSectionId,
  makeRuleId,
  makeVerbId,
  makeConjugationId,
  makeVocabId,
  makeExpressionId,
  makeExampleId,
} from "../src/lib/dataset/ids";

export function buildChapter1(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 1;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 1 && (p.printed_page || 0) <= 12);
  const exercises = extractChapterExercises(chNum, chPages);

  // Sections
  const sec1 = {
    id: makeSectionId(chNum, 1, "Regular -er verbs in the present"),
    chapter_id: chId,
    order: 1,
    title: "Regular -er verbs in the present",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("regular_er_verbs_present_formation")],
    verb_ids: [
      makeVerbId("aimer"),
      makeVerbId("chanter"),
      makeVerbId("danser"),
      makeVerbId("donner"),
      makeVerbId("habiter"),
      makeVerbId("parler"),
      makeVerbId("regarder"),
      makeVerbId("travailler"),
    ],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("parler", 1), makeExampleId("regarder", 1)],
    exercise_ids: [exercises[0]?.id, exercises[1]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 1, page_end_printed: 4, page_start_pdf: 15, page_end_pdf: 18 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "-er verbs with spelling and stem changes"),
    chapter_id: chId,
    order: 2,
    title: "-er verbs with spelling and stem changes",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [
      makeRuleId("verbs_ending_in_ger_spelling_change"),
      makeRuleId("verbs_ending_in_cer_spelling_change"),
      makeRuleId("verbs_ending_in_yer_stem_change"),
      makeRuleId("verbs_with_e_consonant_er_stem_change"),
      makeRuleId("verbs_with_e_aigu_stem_change"),
      makeRuleId("verbs_ending_in_eler_eter_double_consonant"),
    ],
    verb_ids: [
      makeVerbId("manger"),
      makeVerbId("voyager"),
      makeVerbId("commencer"),
      makeVerbId("envoyer"),
      makeVerbId("nettoyer"),
      makeVerbId("payer"),
      makeVerbId("acheter"),
      makeVerbId("emmener"),
      makeVerbId("lever"),
      makeVerbId("répéter"),
      makeVerbId("préférer"),
      makeVerbId("espérer"),
      makeVerbId("appeler"),
      makeVerbId("épeler"),
      makeVerbId("jeter"),
    ],
    expression_ids: [],
    vocabulary_ids: [],
    example_ids: [makeExampleId("manger", 1), makeExampleId("acheter", 1), makeExampleId("appeler", 1)],
    exercise_ids: [exercises[2]?.id, exercises[3]?.id, exercises[4]?.id, exercises[5]?.id, exercises[6]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 4, page_end_printed: 9, page_start_pdf: 18, page_end_pdf: 23 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "When is the present tense used in French"),
    chapter_id: chId,
    order: 3,
    title: "When is the present tense used in French?",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [
      makeRuleId("present_general_and_ongoing_actions"),
      makeRuleId("present_for_near_future"),
      makeRuleId("present_for_habitual_actions"),
      makeRuleId("present_historical_and_dramatic"),
      makeRuleId("etre_en_train_de_construction"),
      makeRuleId("depuis_with_present_tense"),
    ],
    verb_ids: [makeVerbId("partir"), makeVerbId("arriver")],
    expression_ids: [
      makeExpressionId("etre en train de + infinitif"),
      makeExpressionId("depuis combien de temps"),
      makeExpressionId("depuis quand"),
      makeExpressionId("il y a ... que"),
      makeExpressionId("ca fait ... que"),
    ],
    vocabulary_ids: [makeVocabId("boucherie"), makeVocabId("etoile"), makeVocabId("ciel")],
    example_ids: [makeExampleId("etre_en_train_de", 1), makeExampleId("depuis", 1)],
    exercise_ids: [exercises[7]?.id, exercises[8]?.id, exercises[9]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 9, page_end_printed: 12, page_start_pdf: 23, page_end_pdf: 26 },
  };

  const sections = [sec1, sec2, sec3];

  // Rules
  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("regular_er_verbs_present_formation"),
      type: "grammar_rule",
      title: "Formation of regular -er verbs in the present tense",
      short_label: "Regular -er present",
      grammar_category: "verb_formation",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Drop -er from the infinitive and add endings: -e, -es, -e, -ons, -ez, -ent.",
      explanation: "To conjugate a regular -er verb in the present tense, remove the infinitive ending -er to find the stem, then add the endings corresponding to the subject pronoun.",
      formation: {
        steps: ["Drop the -er infinitive ending", "Add the personal endings: -e, -es, -e, -ons, -ez, -ent"],
        patterns: ["stem + -e/-es/-e/-ons/-ez/-ent"],
        endings: { je: "e", tu: "es", il_elle_on: "e", nous: "ons", vous: "ez", ils_elles: "ent" },
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: ["aller is irregular", "spelling/stem changing -er verbs have minor adjustments"],
      restrictions: [],
      notes: ["The endings -e, -es, and -ent are all silent in spoken French."],
      common_mistakes: [
        {
          wrong: "ils chantent (pronounced with ent)",
          correct: "ils chantent (pronounced like il chante)",
          explanation: "The 3rd person plural ending -ent is completely silent.",
        },
      ],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("parler", 1)],
      exercise_ids: [exercises[0]?.id || ""],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 1, context_type: "grammar_explanation" }],
      tags: ["essential", "formation", "er_verbs"],
    },
    {
      id: makeRuleId("verbs_ending_in_ger_spelling_change"),
      type: "grammar_rule",
      title: "Spelling change in verbs ending in -ger",
      short_label: "-ger verbs present",
      grammar_category: "spelling_change",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Keep the 'e' before -ons in the 'nous' form to preserve the soft 'g' sound (mangeons).",
      explanation: "For verbs ending in -ger (like manger, voyager, nager, partager), add an 'e' before the -ons ending of nous (nous mangeons, nous voyageons) to keep the soft 'g' sound.",
      formation: {
        steps: ["In the nous form, retain 'e' after 'g' before 'ons'"],
        patterns: ["nous stem-g + e + ons"],
        endings: { nous: "eons" },
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Only the nous form is affected in the present tense."],
      common_mistakes: [{ wrong: "nous mangons", correct: "nous mangeons", explanation: "Without 'e', 'g' would sound hard as in 'gant'." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("regular_er_verbs_present_formation")],
      example_ids: [makeExampleId("manger", 1)],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 4, context_type: "grammar_explanation" }],
      tags: ["spelling_change", "ger_verbs"],
    },
    {
      id: makeRuleId("verbs_ending_in_cer_spelling_change"),
      type: "grammar_rule",
      title: "Spelling change in verbs ending in -cer",
      short_label: "-cer verbs present",
      grammar_category: "spelling_change",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Change 'c' to 'ç' before -ons in the 'nous' form to preserve the soft 's' sound (commençons).",
      explanation: "For verbs ending in -cer (like commencer, avancer, lancer, remplacer), change 'c' to 'ç' before the 'o' in nous (nous commençons) to keep the soft 's' sound.",
      formation: {
        steps: ["In the nous form, change 'c' to 'ç' before 'ons'"],
        patterns: ["nous stem-ç + ons"],
        endings: { nous: "çons" },
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Only the nous form is affected in the present tense."],
      common_mistakes: [{ wrong: "nous commencons", correct: "nous commençons", explanation: "Without cedilla, 'c' before 'o' sounds like 'k'." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("regular_er_verbs_present_formation")],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 5, context_type: "grammar_explanation" }],
      tags: ["spelling_change", "cer_verbs"],
    },
    {
      id: makeRuleId("verbs_ending_in_yer_stem_change"),
      type: "grammar_rule",
      title: "Stem change in verbs ending in -yer",
      short_label: "-yer verbs present",
      grammar_category: "stem_change",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "The 'y' changes to 'i' in all forms except 'nous' and 'vous' (j'envoie, nous envoyons).",
      explanation: "In verbs ending in -oyer and -uyer (envoyer, nettoyer, essuyer), 'y' changes to 'i' before a silent 'e' (boot pattern: je, tu, il, ils). For -ayer verbs (payer), both 'i' and 'y' forms are accepted (je paie / je paye).",
      formation: {
        steps: ["Change 'y' to 'i' in singular and 3rd person plural forms", "Keep 'y' in nous and vous forms"],
        patterns: ["je/tu/il/ils: -i- + ending; nous/vous: -y- + ending"],
        endings: {},
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: ["payer allows both je paie and je paye"],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("regular_er_verbs_present_formation")],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 4, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 5, context_type: "grammar_explanation" }],
      tags: ["stem_change", "yer_verbs"],
    },
    {
      id: makeRuleId("verbs_with_e_consonant_er_stem_change"),
      type: "grammar_rule",
      title: "Stem change in verbs with -e- + consonant + -er",
      short_label: "-e_er stem change",
      grammar_category: "stem_change",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "The silent 'e' changes to 'è' in all forms except 'nous' and 'vous' (j'achète, nous achetons).",
      explanation: "Verbs like acheter, emmener, lever, peser add a grave accent (è) in the boot forms (je, tu, il, ils) where the ending is silent.",
      formation: {
        steps: ["Add accent grave 'è' to stem in je, tu, il, ils", "Keep unaccented 'e' in nous and vous"],
        patterns: ["stem-è + ending (boot)"],
        endings: {},
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "nous achètons", correct: "nous achetons", explanation: "Nous and vous keep the unaccented stem." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("regular_er_verbs_present_formation")],
      example_ids: [makeExampleId("acheter", 1)],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 6, context_type: "grammar_explanation" }],
      tags: ["stem_change"],
    },
    {
      id: makeRuleId("verbs_with_e_aigu_stem_change"),
      type: "grammar_rule",
      title: "Stem change in verbs with -é- + consonant + -er",
      short_label: "-é_er stem change",
      grammar_category: "stem_change",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "The 'é' changes to 'è' in all forms except 'nous' and 'vous' (je répète, nous répétons).",
      explanation: "Verbs like répéter, célébrer, espérer, préférer change the acute accent (é) to a grave accent (è) in the boot forms.",
      formation: {
        steps: ["Change 'é' to 'è' in je, tu, il, ils", "Keep 'é' in nous and vous"],
        patterns: ["stem-è + ending (boot)"],
        endings: {},
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("regular_er_verbs_present_formation")],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 7, context_type: "grammar_explanation" }],
      tags: ["stem_change"],
    },
    {
      id: makeRuleId("verbs_ending_in_eler_eter_double_consonant"),
      type: "grammar_rule",
      title: "Verbs ending in -eler and -eter doubling consonant",
      short_label: "-eler / -eter double consonant",
      grammar_category: "stem_change",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Verbs like appeler and jeter double the 'l' or 't' before silent endings (j'appelle, je jette).",
      explanation: "Verbs like appeler, rappeler, renouveler, épeler double the 'l' (ll) in boot forms. Verbs like jeter double the 't' (tt). Nous and vous keep a single consonant.",
      formation: {
        steps: ["Double 'l' or 't' in je, tu, il, ils", "Single 'l' or 't' in nous and vous"],
        patterns: ["-ll- / -tt- in boot forms"],
        endings: {},
      },
      usage_conditions: [],
      trigger_words: [],
      signal_words: [],
      exceptions: ["geler and acheter take accent grave instead of doubling consonant"],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "nous appellons", correct: "nous appelons", explanation: "Nous and vous have single 'l'." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("regular_er_verbs_present_formation")],
      example_ids: [makeExampleId("appeler", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 7, context_type: "grammar_explanation" }],
      tags: ["essential", "stem_change"],
    },
    {
      id: makeRuleId("present_general_and_ongoing_actions"),
      type: "grammar_rule",
      title: "Present tense for general statements and ongoing actions",
      short_label: "Present ongoing & statements",
      grammar_category: "tense_usage",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "French present translates simple present, present continuous, and emphatic present in English.",
      explanation: "In French, 'Valérie parle' translates to 'Valérie speaks', 'Valérie is speaking', and 'Valérie does speak'. There is no separate progressive form with 'être' unless using the construction 'être en train de'.",
      formation: null,
      usage_conditions: ["General statements", "Current ongoing actions"],
      trigger_words: ["maintenant", "en ce moment"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Do not say 'elle est parlant' for 'she is speaking'."],
      common_mistakes: [{ wrong: "Elle est parlant", correct: "Elle parle", explanation: "French does not use être + present participle for ongoing actions." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [makeRuleId("etre_en_train_de_construction")],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("parler", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "grammar_explanation" }],
      tags: ["essential", "tense_usage"],
    },
    {
      id: makeRuleId("present_for_near_future"),
      type: "grammar_rule",
      title: "Present tense expressing near future",
      short_label: "Present near future",
      grammar_category: "tense_usage",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "The present tense can express an action planned or happening in the near future.",
      explanation: "Just as in English, a present tense verb combined with a future time marker indicates planned future action: 'Il part demain soir' (He is leaving tomorrow evening).",
      formation: null,
      usage_conditions: ["Planned upcoming events with time adverbs"],
      trigger_words: ["demain", "ce soir", "la semaine prochaine", "en fin de semaine"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "grammar_explanation" }],
      tags: ["tense_usage", "future"],
    },
    {
      id: makeRuleId("present_for_habitual_actions"),
      type: "grammar_rule",
      title: "Present tense for habitual actions",
      short_label: "Present habitual",
      grammar_category: "tense_usage",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Describes habits, routines, and repeated actions in the present.",
      explanation: "Use the present tense with frequency markers like 'tous les jours', 'd'habitude', 'toujours' to describe habitual events.",
      formation: null,
      usage_conditions: ["Habitual routines", "General facts of nature"],
      trigger_words: ["tous les jours", "d'habitude", "souvent", "toujours", "chaque matin"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "grammar_explanation" }],
      tags: ["essential", "tense_usage"],
    },
    {
      id: makeRuleId("present_historical_and_dramatic"),
      type: "grammar_rule",
      title: "Historical and dramatic present",
      short_label: "Historical present",
      grammar_category: "tense_usage",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Used to recount historical facts or past events with dramatic immediacy.",
      explanation: "In narratives and history, the present tense makes past events feel vivid and immediate: 'Flaubert publie Madame Bovary et c'est le scandale!'.",
      formation: null,
      usage_conditions: ["Narratives", "Historical commentary", "Dramatic retelling"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 3, usefulness: 3, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "grammar_explanation" }],
      tags: ["tense_usage", "narrative"],
    },
    {
      id: makeRuleId("etre_en_train_de_construction"),
      type: "grammar_rule",
      title: "Continuous action with être en train de + infinitive",
      short_label: "être en train de",
      grammar_category: "idiomatic_construction",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Expresses that an action is currently in progress ('in the middle of doing something').",
      explanation: "To explicitly emphasize that an action is in progress at this exact moment, use conjugated être + en train de + infinitive: 'Je suis en train de parler' (I am in the middle of talking).",
      formation: {
        steps: ["Conjugate être in present", "Add 'en train de' (or 'en train d'' before vowel)", "Add infinitive of main verb"],
        patterns: ["[SUBJECT] + être (présent) + en train de + [INFINITIF]"],
        endings: {},
      },
      usage_conditions: ["Emphasizing ongoing process"],
      trigger_words: ["en ce moment", "un instant"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Use 'd'' before vowel or silent h (en train d'étudier)."],
      common_mistakes: [{ wrong: "Je suis parlant", correct: "Je suis en train de parler", explanation: "Use être en train de + infinitive, not present participle." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [makeRuleId("present_general_and_ongoing_actions")],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("etre_en_train_de", 1)],
      exercise_ids: [exercises[7]?.id || ""],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "grammar_explanation" }],
      tags: ["essential", "construction", "verb_pattern"],
    },
    {
      id: makeRuleId("depuis_with_present_tense"),
      type: "grammar_rule",
      title: "Action continuing into the present with depuis, il y a... que, ça fait... que",
      short_label: "depuis + present",
      grammar_category: "tense_usage",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Use the French present tense with 'depuis' for actions that began in the past and continue in the present.",
      explanation: "Unlike English which uses the present perfect ('I have been living here for three years'), French uses the PRESENT tense with 'depuis': 'J'habite à Nice depuis trois ans'. Questions use 'depuis quand' (since when) or 'depuis combien de temps' (for how long).",
      formation: {
        steps: ["Use verb in present tense", "Add 'depuis' + starting point or duration"],
        patterns: ["[VERBE AU PRÉSENT] + depuis + [DURÉE / POINT DE DÉPART]"],
        endings: {},
      },
      usage_conditions: ["Ongoing action initiated in the past"],
      trigger_words: ["depuis", "depuis quand", "depuis combien de temps", "il y a ... que", "ça fait ... que"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["If the action is completed and no longer continues, use passé composé + pendant/il y a, not depuis."],
      common_mistakes: [
        {
          wrong: "J'ai habité ici depuis trois ans (when still living there)",
          correct: "J'habite ici depuis trois ans",
          explanation: "In French, use the present tense if the action is still ongoing.",
        },
      ],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("depuis", 1)],
      exercise_ids: [exercises[8]?.id || ""],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 10, context_type: "grammar_explanation" }],
      tags: ["essential", "tense_usage", "time"],
    },
  ];

  // Verbs
  const verbsList: Array<{
    inf: string;
    en: string[];
    reg?: any;
    group?: any;
    participle?: string;
  }> = [
    { inf: "parler", en: ["to speak", "to talk"], participle: "parlé" },
    { inf: "aimer", en: ["to like", "to love"], participle: "aimé" },
    { inf: "chanter", en: ["to sing"], participle: "chanté" },
    { inf: "danser", en: ["to dance"], participle: "dansé" },
    { inf: "donner", en: ["to give"], participle: "donné" },
    { inf: "habiter", en: ["to live", "to reside"], participle: "habité" },
    { inf: "regarder", en: ["to look at", "to watch"], participle: "regardé" },
    { inf: "travailler", en: ["to work"], participle: "travaillé" },
    { inf: "manger", en: ["to eat"], reg: "spelling_changing", participle: "mangé" },
    { inf: "voyager", en: ["to travel"], reg: "spelling_changing", participle: "voyagé" },
    { inf: "commencer", en: ["to begin", "to start"], reg: "spelling_changing", participle: "commencé" },
    { inf: "envoyer", en: ["to send"], reg: "stem_changing", participle: "envoyé" },
    { inf: "nettoyer", en: ["to clean"], reg: "stem_changing", participle: "nettoyé" },
    { inf: "payer", en: ["to pay"], reg: "stem_changing", participle: "payé" },
    { inf: "acheter", en: ["to buy"], reg: "stem_changing", participle: "acheté" },
    { inf: "emmener", en: ["to take along", "to escort"], reg: "stem_changing", participle: "emmené" },
    { inf: "lever", en: ["to raise", "to lift"], reg: "stem_changing", participle: "levé" },
    { inf: "répéter", en: ["to repeat"], reg: "stem_changing", participle: "répété" },
    { inf: "préférer", en: ["to prefer"], reg: "stem_changing", participle: "préféré" },
    { inf: "espérer", en: ["to hope"], reg: "stem_changing", participle: "espéré" },
    { inf: "appeler", en: ["to call"], reg: "stem_changing", participle: "appelé" },
    { inf: "épeler", en: ["to spell"], reg: "stem_changing", participle: "épelé" },
    { inf: "jeter", en: ["to throw"], reg: "stem_changing", participle: "jeté" },
    { inf: "bavarder", en: ["to chat"], participle: "bavardé" },
    { inf: "déménager", en: ["to move (residence)"], reg: "spelling_changing", participle: "déménagé" },
    { inf: "renouveler", en: ["to renew"], reg: "stem_changing", participle: "renouvelé" },
    { inf: "étinceler", en: ["to sparkle", "to glitter"], reg: "stem_changing", participle: "étincelé" },
    { inf: "ensorceler", en: ["to bewitch"], reg: "stem_changing", participle: "ensorcelé" },
    { inf: "annuler", en: ["to cancel"], participle: "annulé" },
    { inf: "remplacer", en: ["to replace"], reg: "spelling_changing", participle: "remplacé" },
    { inf: "emprunter", en: ["to borrow"], participle: "emprunté" },
    { inf: "renoncer", en: ["to give up", "to renounce"], reg: "spelling_changing", participle: "renoncé" },
    { inf: "corriger", en: ["to correct", "to grade"], reg: "spelling_changing", participle: "corrigé" },
    { inf: "dessiner", en: ["to draw"], participle: "dessiné" },
    { inf: "effacer", en: ["to erase"], reg: "spelling_changing", participle: "effacé" },
    { inf: "étudier", en: ["to study"], participle: "étudié" },
    { inf: "laver", en: ["to wash"], participle: "lavé" },
    { inf: "ranger", en: ["to tidy", "to put away"], reg: "spelling_changing", participle: "rangé" },
    { inf: "posséder", en: ["to own", "to possess"], reg: "stem_changing", participle: "possédé" },
  ];

  const verbs: Verb[] = verbsList.map((v) => {
    const vId = makeVerbId(v.inf);
    const conjId = makeConjugationId(vId, "tense_present_indicative");
    return {
      id: vId,
      type: "verb",
      infinitive: v.inf,
      display_form: v.inf,
      english: v.en,
      senses: [
        {
          sense_id: `${vId}_s1`,
          english: v.en,
          usage_contexts: [],
          example_ids: [],
        },
      ],
      verb_group: "1st_group",
      regularity: v.reg || "regular",
      pronominal: false,
      transitivity: ["transitive", "intransitive"],
      auxiliary: "avoir",
      past_participle: v.participle || null,
      present_participle: null,
      conjugation_ids: [conjId],
      expression_ids: [],
      complement_frame_ids: [],
      related_verb_ids: [],
      contrast_verb_ids: [],
      confused_with_ids: [],
      word_family_ids: [],
      study: {
        learning_priority: ["parler", "aimer", "travailler", "manger", "acheter", "appeler", "préférer"].includes(v.inf) ? 5 : 4,
        usefulness: 5,
        difficulty: v.reg ? 2 : 1,
      },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 1 },
      attestations: [
        {
          source_type: "book",
          chapter_number: chNum,
          chapter_id: chId,
          page_printed: 1,
          context_type: "grammar_explanation",
        },
      ],
      tags: ["er_verb", "chapter_01"],
    };
  });

  // Conjugations for key verbs
  const conjugations: Conjugation[] = [
    {
      id: makeConjugationId("verb_parler", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("parler"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je parle",
        tu: "tu parles",
        il_elle_on: "il/elle/on parle",
        nous: "nous parlons",
        vous: "vous parlez",
        ils_elles: "ils/elles parlent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("parler", 1)],
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 1, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_manger", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("manger"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je mange",
        tu: "tu manges",
        il_elle_on: "il/elle/on mange",
        nous: "nous mangeons",
        vous: "vous mangez",
        ils_elles: "ils/elles mangent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["nous mangeons retains 'e'"],
      irregularity_notes: [],
      example_ids: [makeExampleId("manger", 1)],
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 4, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_commencer", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("commencer"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je commence",
        tu: "tu commences",
        il_elle_on: "il/elle/on commence",
        nous: "nous commençons",
        vous: "vous commencez",
        ils_elles: "ils/elles commencent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["nous commençons takes cedilla 'ç'"],
      irregularity_notes: [],
      example_ids: [],
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 5, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_envoyer", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("envoyer"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "j'envoie",
        tu: "tu envoies",
        il_elle_on: "il/elle/on envoie",
        nous: "nous envoyons",
        vous: "vous envoyez",
        ils_elles: "ils/elles envoient",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["y -> i in boot forms"],
      irregularity_notes: [],
      example_ids: [],
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 5, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_acheter", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("acheter"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "j'achète",
        tu: "tu achètes",
        il_elle_on: "il/elle/on achète",
        nous: "nous achetons",
        vous: "vous achetez",
        ils_elles: "ils/elles achètent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["accent grave è in boot forms"],
      irregularity_notes: [],
      example_ids: [makeExampleId("acheter", 1)],
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 6, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_repeter", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("répéter"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je répète",
        tu: "tu répètes",
        il_elle_on: "il/elle/on répète",
        nous: "nous répétons",
        vous: "vous répétez",
        ils_elles: "ils/elles répètent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["é -> è in boot forms"],
      irregularity_notes: [],
      example_ids: [],
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 7, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_appeler", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("appeler"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "j'appelle",
        tu: "tu空appelles",
        il_elle_on: "il/elle/on appelle",
        nous: "nous appelons",
        vous: "vous appelez",
        ils_elles: "ils/elles appellent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["double 'l' in boot forms"],
      irregularity_notes: [],
      example_ids: [makeExampleId("appeler", 1)],
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 7, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
  ];

  // Expressions & High-Value Patterns
  const expressions: Expression[] = [
    {
      id: makeExpressionId("etre en train de + infinitif"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "être en train de + infinitif",
      display_form: "être en train de + infinitif",
      english: ["to be in the middle of doing something", "to be doing something right now"],
      base_verb_ids: [makeVerbId("être")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "être en train de [INFINITIVE]",
      pattern_slots: [
        { name: "action", display: "infinitif", type: "verb_infinitive", required: true },
      ],
      transformations: [],
      variants: ["être en train d'"],
      function_ids: [],
      usage_notes: ["Used to emphasize ongoing actions in the present or past"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("etre_en_train_de", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["conversation", "descriptions"] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("etre_en_train_de_construction")] },
      tags: ["essential", "verb_pattern"],
    },
    {
      id: makeExpressionId("depuis combien de temps"),
      type: "expression",
      expression_type: "functional_phrase",
      canonical_form: "depuis combien de temps",
      display_form: "depuis combien de temps",
      english: ["how long", "for how long"],
      base_verb_ids: [],
      related_vocabulary_ids: [makeVocabId("temps")],
      productive: true,
      collocation_strength: "strong",
      pattern: "Depuis combien de temps + [VERB]...?",
      pattern_slots: [],
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: ["Asks for duration of an action still in progress"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("depuis", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["conversation", "questions"] },
      frequency: { book_occurrences: 5 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 10, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("depuis_with_present_tense")] },
      tags: ["essential", "question", "time"],
    },
    {
      id: makeExpressionId("depuis quand"),
      type: "expression",
      expression_type: "functional_phrase",
      canonical_form: "depuis quand",
      display_form: "depuis quand",
      english: ["since when", "how long (since what point)"],
      base_verb_ids: [],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "Depuis quand + [VERB]...?",
      pattern_slots: [],
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: ["Asks for the starting date/moment of an action still in progress"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["conversation", "questions"] },
      frequency: { book_occurrences: 3 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 10, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("depuis_with_present_tense")] },
      tags: ["essential", "question", "time"],
    },
    {
      id: makeExpressionId("il y a ... que"),
      type: "expression",
      expression_type: "sentence_starter",
      canonical_form: "il y a ... que",
      display_form: "il y a [TEMPS] que...",
      english: ["it has been [TIME] since / that..."],
      base_verb_ids: [makeVerbId("avoir")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "Il y a [TIME] que [CLAUSE]",
      pattern_slots: [
        { name: "duration", display: "durée", type: "time", required: true },
        { name: "clause", display: "phrase", type: "clause", required: true },
      ],
      transformations: [],
      variants: ["ça fait ... que"],
      function_ids: [],
      usage_notes: ["Synonym for depuis when stating ongoing duration at sentence start"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 4, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 2 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 11, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("depuis_with_present_tense")] },
      tags: ["essential", "time"],
    },
    {
      id: makeExpressionId("ca fait ... que"),
      type: "expression",
      expression_type: "sentence_starter",
      canonical_form: "ça fait ... que",
      display_form: "ça fait [TEMPS] que...",
      english: ["it's been [TIME] that...", "I've been doing something for [TIME]"],
      base_verb_ids: [makeVerbId("faire")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "Ça fait [TIME] que [CLAUSE]",
      pattern_slots: [
        { name: "duration", display: "durée", type: "time", required: true },
        { name: "clause", display: "phrase", type: "clause", required: true },
      ],
      transformations: [],
      variants: ["cela fait ... que"],
      function_ids: [],
      usage_notes: ["Very common spoken alternative to depuis"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "informal", spoken_written: "spoken", contexts: ["conversation"] },
      frequency: { book_occurrences: 2 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 11, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("depuis_with_present_tense")] },
      tags: ["essential", "conversation", "time"],
    },
  ];

  // Vocabulary
  const vocabItems: Array<{ fr: string; en: string[]; pos: any; gender?: any; art?: string }> = [
    { fr: "boucherie", en: ["butcher shop"], pos: "noun", gender: "feminine", art: "la" },
    { fr: "étoile", en: ["star"], pos: "noun", gender: "feminine", art: "l'" },
    { fr: "ciel", en: ["sky"], pos: "noun", gender: "masculine", art: "le" },
    { fr: "temps", en: ["time", "weather"], pos: "noun", gender: "masculine", art: "le" },
    { fr: "d'habitude", en: ["usually"], pos: "adverb" },
    { fr: "maintenant", en: ["now"], pos: "adverb" },
    { fr: "demain", en: ["tomorrow"], pos: "adverb" },
    { fr: "bientôt", en: ["soon"], pos: "adverb" },
    { fr: "copie", en: ["student paper", "copy"], pos: "noun", gender: "feminine", art: "la" },
    { fr: "tableau", en: ["blackboard", "painting"], pos: "noun", gender: "masculine", art: "le" },
    { fr: "chorale", en: ["choir"], pos: "noun", gender: "feminine", art: "la" },
    { fr: "piscine", en: ["swimming pool"], pos: "noun", gender: "feminine", art: "la" },
    { fr: "lunettes", en: ["glasses", "eyeglasses"], pos: "noun", gender: "feminine", art: "les" },
    { fr: "argent", en: ["money", "silver"], pos: "noun", gender: "masculine", art: "l'" },
    { fr: "banque", en: ["bank"], pos: "noun", gender: "feminine", art: "la" },
    { fr: "bateau", en: ["boat"], pos: "noun", gender: "masculine", art: "le" },
    { fr: "projet", en: ["project"], pos: "noun", gender: "masculine", art: "le" },
  ];

  const vocabulary: Vocabulary[] = vocabItems.map((v) => {
    const vId = makeVocabId(v.fr);
    return {
      id: vId,
      type: "vocabulary",
      canonical_form: v.fr,
      display_form: v.art ? `${v.art} ${v.fr}` : v.fr,
      french: v.fr,
      english: v.en,
      part_of_speech: v.pos,
      noun:
        v.pos === "noun"
          ? {
              gender: v.gender || "masculine",
              article: v.art || (v.gender === "feminine" ? "la" : "le"),
              plural: `${v.fr}s`,
            }
          : null,
      senses: [{ sense_id: `${vId}_s1`, english: v.en, usage_contexts: [], example_ids: [] }],
      semantic_domains: ["general"],
      word_family_ids: [],
      collocation_expression_ids: [],
      false_friend: false,
      cognate: ["argent", "banque", "projet"].includes(v.fr),
      study: { learning_priority: 4, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 1 },
      attestations: [
        {
          source_type: "book",
          chapter_number: chNum,
          chapter_id: chId,
          page_printed: 1,
          context_type: "vocabulary_box",
        },
      ],
      tags: [v.pos, "chapter_01"],
    };
  });

  // Examples
  const examples: Example[] = [
    {
      id: makeExampleId("parler", 1),
      type: "example",
      french: "Valérie parle à son ami Ludovic.",
      english: "Valérie is talking (talks, does talk) to her friend Ludovic.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "parle", role: "verb" }] },
      relations: {
        verbs: [makeVerbId("parler")],
        tenses: ["tense_present_indicative"],
        grammar_rules: [makeRuleId("present_general_and_ongoing_actions")],
      },
      cloze_candidates: ["parle"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("regarder", 1),
      type: "example",
      french: "Il regarde les étoiles dans le ciel.",
      english: "He is looking at the stars in the sky.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "regarde", role: "verb" }] },
      relations: {
        verbs: [makeVerbId("regarder")],
        tenses: ["tense_present_indicative"],
      },
      cloze_candidates: ["regarde"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("manger", 1),
      type: "example",
      french: "Nous mangeons dans la cuisine.",
      english: "We are eating in the kitchen.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "mangeons", role: "verb" }] },
      relations: {
        verbs: [makeVerbId("manger")],
        tenses: ["tense_present_indicative"],
        grammar_rules: [makeRuleId("verbs_ending_in_ger_spelling_change")],
      },
      cloze_candidates: ["mangeons"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 4, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("acheter", 1),
      type: "example",
      french: "D'habitude, j'achète la viande dans cette boucherie.",
      english: "Usually I buy meat in this butcher shop.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "achète", role: "verb" }] },
      relations: {
        verbs: [makeVerbId("acheter")],
        tenses: ["tense_present_indicative"],
        grammar_rules: [makeRuleId("verbs_with_e_consonant_er_stem_change")],
      },
      cloze_candidates: ["achète"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("appeler", 1),
      type: "example",
      french: "Comment s'appelle sa sœur?",
      english: "What is his sister's name?",
      source_type: "book",
      annotations: { focus_spans: [{ text: "s'appelle", role: "verb" }] },
      relations: {
        verbs: [makeVerbId("appeler")],
        tenses: ["tense_present_indicative"],
        grammar_rules: [makeRuleId("verbs_ending_in_eler_eter_double_consonant")],
      },
      cloze_candidates: ["s'appelle"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 8, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("etre_en_train_de", 1),
      type: "example",
      french: "Un instant, s'il vous plaît, je suis en train de parler à Rémi.",
      english: "One moment, please, I am talking to Rémi.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "suis en train de parler", role: "construction" }] },
      relations: {
        verbs: [makeVerbId("parler")],
        expressions: [makeExpressionId("etre en train de + infinitif")],
        tenses: ["tense_present_indicative"],
        grammar_rules: [makeRuleId("etre_en_train_de_construction")],
      },
      cloze_candidates: ["suis en train de parler"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 9, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("depuis", 1),
      type: "example",
      french: "Depuis combien de temps habites-tu à Nice? — J'habite à Nice depuis trois ans.",
      english: "How long have you been living in Nice? — I have been living in Nice for three years.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "depuis", role: "time_marker" }] },
      relations: {
        verbs: [makeVerbId("habiter")],
        expressions: [makeExpressionId("depuis combien de temps")],
        tenses: ["tense_present_indicative"],
        grammar_rules: [makeRuleId("depuis_with_present_tense")],
      },
      cloze_candidates: ["habites", "habite", "depuis"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 1, page_printed: 10, context_type: "example_sentence" }],
    },
  ];

  // Chapter object
  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "The present tense of regular -er verbs",
    section_ids: sections.map((s) => s.id),
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 1, page_end_printed: 12, page_start_pdf: 15, page_end_pdf: 26 },
    tags: ["er_verbs", "present_tense", "regular_verbs"],
  };

  return {
    chapter,
    sections,
    grammar_rules,
    verbs,
    conjugations,
    vocabulary,
    expressions,
    examples,
    exercises,
  };
}
