import { ChapterExtractionBundle } from "./chapter-types";
import { RawPage } from "./extract-pages";
import { extractChapterExercises } from "./extract-chapter";
import {
  GrammarRule,
  Verb,
  Conjugation,
  Expression,
  Vocabulary,
  Example,
  Chapter,
  Section,
} from "../src/lib/dataset/schemas";
import {
  makeChapterId,
  makeSectionId,
  makeRuleId,
  makeVerbId,
  makeConjugationId,
  makeVocabId,
  makeExpressionId,
  makeExampleId,
} from "../src/lib/dataset/ids";

// =======================================================================
// CHAPTER 4: More irregular verbs
// =======================================================================
export function buildChapter4(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 4;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 34 && (p.printed_page || 0) <= 42);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "The verb aller (to go)"),
    chapter_id: chId,
    order: 1,
    title: "The verb aller (to go)",
    concept_ids: ["concept_movement"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("verb_aller_present_conjugation"), makeRuleId("idiomatic_uses_of_aller")],
    verb_ids: [makeVerbId("aller")],
    expression_ids: [makeExpressionId("comment allez vous"), makeExpressionId("aller bien")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("aller", 1)],
    exercise_ids: [exercises[0]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 34, page_end_printed: 35, page_start_pdf: 48, page_end_pdf: 49 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "The immediate future tense"),
    chapter_id: chId,
    order: 2,
    title: "The immediate future tense",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("futur_proche_aller_infinitive")],
    verb_ids: [],
    expression_ids: [makeExpressionId("aller + infinitif")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("futur_proche", 1)],
    exercise_ids: [exercises[1]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 35, page_end_printed: 36, page_start_pdf: 49, page_end_pdf: 50 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "The verb venir (to come)"),
    chapter_id: chId,
    order: 3,
    title: "The verb venir (to come)",
    concept_ids: ["concept_movement"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("verb_venir_present_conjugation"), makeRuleId("venir_compounds_conjugation")],
    verb_ids: [
      makeVerbId("venir"),
      makeVerbId("devenir"),
      makeVerbId("revenir"),
      makeVerbId("prévenir"),
      makeVerbId("parvenir"),
      makeVerbId("convenir"),
      makeVerbId("tenir"),
      makeVerbId("maintenir"),
      makeVerbId("retenir"),
    ],
    expression_ids: [makeExpressionId("venir chercher quelqu'un"), makeExpressionId("tenir a"), makeExpressionId("tenir de")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("venir", 1), makeExampleId("venir_chercher", 1)],
    exercise_ids: [exercises[2]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 36, page_end_printed: 37, page_start_pdf: 50, page_end_pdf: 51 },
  };

  const sec4 = {
    id: makeSectionId(chNum, 4, "The immediate past"),
    chapter_id: chId,
    order: 4,
    title: "The immediate past",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("passe_recent_venir_de_infinitive")],
    verb_ids: [],
    expression_ids: [makeExpressionId("venir de + infinitif")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("venir_de", 1)],
    exercise_ids: [exercises[3]?.id, exercises[4]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 37, page_end_printed: 40, page_start_pdf: 51, page_end_pdf: 54 },
  };

  const sec5 = {
    id: makeSectionId(chNum, 5, "The verb faire (to do, to make)"),
    chapter_id: chId,
    order: 5,
    title: "The verb faire (to do, to make)",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("verb_faire_present_conjugation"), makeRuleId("idiomatic_expressions_with_faire")],
    verb_ids: [makeVerbId("faire")],
    expression_ids: [
      makeExpressionId("faire attention"),
      makeExpressionId("faire la cuisine"),
      makeExpressionId("faire la queue"),
      makeExpressionId("faire semblant de"),
      makeExpressionId("faire le ménage"),
      makeExpressionId("faire du sport"),
    ],
    vocabulary_ids: [],
    example_ids: [makeExampleId("faire", 1), makeExampleId("faire_attention", 1)],
    exercise_ids: [exercises[5]?.id, exercises[6]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 40, page_end_printed: 41, page_start_pdf: 54, page_end_pdf: 55 },
  };

  const sec6 = {
    id: makeSectionId(chNum, 6, "The causative form"),
    chapter_id: chId,
    order: 6,
    title: "The causative form",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("causative_faire_plus_infinitive")],
    verb_ids: [],
    expression_ids: [makeExpressionId("faire + infinitif")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("causative", 1)],
    exercise_ids: [exercises[7]?.id, exercises[8]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 41, page_end_printed: 42, page_start_pdf: 55, page_end_pdf: 56 },
  };

  const sections = [sec1, sec2, sec3, sec4, sec5, sec6];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("verb_aller_present_conjugation"),
      type: "grammar_rule",
      title: "Conjugation of aller (to go) in the present",
      short_label: "aller present",
      grammar_category: "irregular_verbs",
      concept_ids: ["concept_movement"],
      tense_ids: ["tense_present_indicative"],
      summary: "Irregular: je vais, tu vas, il/elle/on va, nous allons, vous allez, ils/elles vont.",
      explanation: "Aller is an irregular 3rd group verb despite its -er ending. It is used for movement and forming the immediate future (futur proche).",
      formation: {
        steps: ["je vais, tu vas, il va, nous allons, vous allez, ils vont"],
        patterns: ["irregular"],
        endings: {},
      },
      usage_conditions: ["Movement", "Health inquiries (Comment ça va?)", "Futur proche"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "ils allent", correct: "ils vont", explanation: "3rd person plural is vont." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [makeRuleId("futur_proche_aller_infinitive")],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("aller", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 34, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs", "movement"],
    },
    {
      id: makeRuleId("futur_proche_aller_infinitive"),
      type: "grammar_rule",
      title: "The immediate future (futur proche): aller + infinitive",
      short_label: "futur proche",
      grammar_category: "verb_pattern",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Conjugated aller in present + infinitive of action verb expresses 'going to do something'.",
      explanation: "Formed with the present tense of aller followed by the infinitive: 'Je vais partir' (I am going to leave). In the negative, ne... pas surrounds aller: 'Je ne vais pas partir'.",
      formation: {
        steps: ["Conjugate aller in present", "Add infinitive of main verb"],
        patterns: ["[SUBJECT] + aller (présent) + [INFINITIF]"],
        endings: {},
      },
      usage_conditions: ["Events happening soon", "Planned future intentions"],
      trigger_words: ["bientôt", "demain", "ce soir", "dans un instant"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Very frequent in spoken French."],
      common_mistakes: [],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("verb_aller_present_conjugation")],
      example_ids: [makeExampleId("futur_proche", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 35, context_type: "grammar_explanation" }],
      tags: ["essential", "future", "verb_pattern"],
    },
    {
      id: makeRuleId("verb_venir_present_conjugation"),
      type: "grammar_rule",
      title: "Conjugation of venir (to come) in the present",
      short_label: "venir present",
      grammar_category: "irregular_verbs",
      concept_ids: ["concept_movement"],
      tense_ids: ["tense_present_indicative"],
      summary: "Irregular: je viens, tu viens, il/elle/on vient, nous venons, vous venez, ils/elles viennent.",
      explanation: "Venir and tenir (and all their compounds: devenir, revenir, prévenir, maintenir, retenir) follow the same conjugation pattern.",
      formation: {
        steps: ["viens, viens, vient, venons, venez, viennent"],
        patterns: ["irregular stem change"],
        endings: {},
      },
      usage_conditions: ["Coming/arriving", "Passé récent with de + inf"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "ils venent", correct: "ils viennent", explanation: "Double 'n' and 'ie' stem in 3rd plural." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [makeRuleId("passe_recent_venir_de_infinitive")],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("venir", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 36, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs", "movement"],
    },
    {
      id: makeRuleId("passe_recent_venir_de_infinitive"),
      type: "grammar_rule",
      title: "The immediate past (passé récent): venir de + infinitive",
      short_label: "passé récent",
      grammar_category: "verb_pattern",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Conjugated venir in present + de + infinitive expresses 'having just done something'.",
      explanation: "Use venir in the present followed by 'de' (or 'd'') and the infinitive of the verb to express an action that just happened: 'Je viens de manger' (I just ate / I have just eaten).",
      formation: {
        steps: ["Conjugate venir in present", "Add 'de' (or 'd'')", "Add infinitive of main verb"],
        patterns: ["[SUBJECT] + venir (présent) + de + [INFINITIF]"],
        endings: {},
      },
      usage_conditions: ["Actions completed moments ago"],
      trigger_words: ["à l'instant", "juste"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Je viens manger (meaning I just ate)", correct: "Je viens de manger", explanation: "Without 'de', it means 'I am coming to eat'." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [makeRuleId("futur_proche_aller_infinitive")],
      prerequisite_rule_ids: [makeRuleId("verb_venir_present_conjugation")],
      example_ids: [makeExampleId("venir_de", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 37, context_type: "grammar_explanation" }],
      tags: ["essential", "past", "verb_pattern"],
    },
    {
      id: makeRuleId("verb_faire_present_conjugation"),
      type: "grammar_rule",
      title: "Conjugation of faire (to do, to make) in the present",
      short_label: "faire present",
      grammar_category: "irregular_verbs",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Irregular: je fais, tu fais, il/elle/on fait, nous faisons, vous faites, ils/elles font.",
      explanation: "Notice the irregular 2nd person plural 'vous faites' and 3rd person plural 'ils font', and the pronunciation of 'nous faisons' [nufəzõ].",
      formation: {
        steps: ["je fais, tu fais, il fait, nous faisons, vous faites, ils font"],
        patterns: ["irregular"],
        endings: {},
      },
      usage_conditions: ["Activities", "Weather (il fait beau)", "Causative"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["One of only three verbs taking -tes with vous (être -> vous êtes, faire -> vous faites, dire -> vous dites)."],
      common_mistakes: [{ wrong: "vous faisez", correct: "vous faites", explanation: "Vous form is irregular: vous faites." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [makeRuleId("causative_faire_plus_infinitive")],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("faire", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 40, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs"],
    },
    {
      id: makeRuleId("causative_faire_plus_infinitive"),
      type: "grammar_rule",
      title: "The causative construction: faire + infinitive",
      short_label: "causative faire",
      grammar_category: "verb_pattern",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Conjugated faire + infinitive means 'to have something done' or 'to cause someone to do something'.",
      explanation: "When you have someone else perform an action or cause an event, use faire + infinitive: 'Je fais réparer ma voiture' (I am having my car repaired); 'Il fait rire ses amis' (He makes his friends laugh).",
      formation: {
        steps: ["Conjugate faire in desired tense", "Follow immediately with infinitive of action verb"],
        patterns: ["[SUBJECT] + faire + [INFINITIF] + [OBJECT]"],
        endings: {},
      },
      usage_conditions: ["Having services done", "Causing effects or reactions"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Object pronouns precede faire: 'Je la fais réparer'."],
      common_mistakes: [{ wrong: "Je fais ma voiture réparer", correct: "Je fais réparer ma voiture", explanation: "The infinitive immediately follows faire." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("verb_faire_present_conjugation")],
      example_ids: [makeExampleId("causative", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 41, context_type: "grammar_explanation" }],
      tags: ["essential", "causative", "verb_pattern"],
    },
  ];

  const verbsList4 = [
    { inf: "aller", en: ["to go"], part: "allé" },
    { inf: "venir", en: ["to come"], part: "venu" },
    { inf: "devenir", en: ["to become"], part: "devenu" },
    { inf: "revenir", en: ["to come back"], part: "revenu" },
    { inf: "prévenir", en: ["to warn", "to notify"], part: "prévenu" },
    { inf: "tenir", en: ["to hold"], part: "tenu" },
    { inf: "maintenir", en: ["to maintain"], part: "maintenu" },
    { inf: "retenir", en: ["to retain", "to hold back"], part: "retenu" },
    { inf: "faire", en: ["to do", "to make"], part: "fait" },
    { inf: "chercher", en: ["to look for", "to search"], part: "cherché" },
  ];

  const verbs: Verb[] = verbsList4.map((v) => {
    const vId = makeVerbId(v.inf);
    return {
      id: vId,
      type: "verb",
      infinitive: v.inf,
      display_form: v.inf,
      english: v.en,
      senses: [{ sense_id: `${vId}_s1`, english: v.en, usage_contexts: [], example_ids: [] }],
      verb_group: v.inf === "chercher" ? "1st_group" : "3rd_group",
      regularity: v.inf === "chercher" ? "regular" : "irregular",
      pronominal: false,
      transitivity: ["transitive", "intransitive"],
      auxiliary: ["aller", "venir", "devenir", "revenir"].includes(v.inf) ? "etre" : "avoir",
      past_participle: v.part || null,
      present_participle: null,
      conjugation_ids: [makeConjugationId(vId, "tense_present_indicative")],
      expression_ids: [],
      complement_frame_ids: [],
      related_verb_ids: [],
      contrast_verb_ids: [],
      confused_with_ids: [],
      word_family_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 6 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 34, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs", "chapter_04"],
    };
  });

  const conjugations: Conjugation[] = [
    {
      id: makeConjugationId("verb_aller", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("aller"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je vais",
        tu: "tu vas",
        il_elle_on: "il/elle/on va",
        nous: "nous allons",
        vous: "vous allez",
        ils_elles: "ils/elles vont",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("aller", 1)],
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 34, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_venir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("venir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je viens",
        tu: "tu viens",
        il_elle_on: "il/elle/on vient",
        nous: "nous venons",
        vous: "vous venez",
        ils_elles: "ils/elles viennent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("venir", 1)],
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 36, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_faire", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("faire"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je fais",
        tu: "tu fais",
        il_elle_on: "il/elle/on fait",
        nous: "nous faisons",
        vous: "vous faites",
        ils_elles: "ils/elles font",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("faire", 1)],
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 40, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
  ];

  const expressions: Expression[] = [
    {
      id: makeExpressionId("venir chercher quelqu'un"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "venir chercher quelqu'un",
      display_form: "venir chercher quelqu'un",
      english: ["to come and get someone", "to come pick someone up"],
      base_verb_ids: [makeVerbId("venir"), makeVerbId("chercher")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "venir chercher [PERSON]",
      pattern_slots: [{ name: "person", display: "quelqu'un", type: "person", required: true }],
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: ["Very common multi-verb construction for picking someone up"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("venir_chercher", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["travel", "daily_life"] },
      frequency: { book_occurrences: 3 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 37, context_type: "grammar_explanation" }],
      relations: { verbs: [makeVerbId("venir"), makeVerbId("chercher")] },
      tags: ["essential", "multi_verb", "movement"],
    },
    {
      id: makeExpressionId("venir de + infinitif"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "venir de + infinitif",
      display_form: "venir de + infinitif",
      english: ["to have just done something"],
      base_verb_ids: [makeVerbId("venir")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "venir de [INFINITIVE]",
      pattern_slots: [{ name: "action", display: "infinitif", type: "verb_infinitive", required: true }],
      transformations: [],
      variants: ["venir d'"],
      function_ids: [],
      usage_notes: ["Passé récent construction"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("venir_de", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 5 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 37, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("passe_recent_venir_de_infinitive")] },
      tags: ["essential", "verb_pattern"],
    },
    {
      id: makeExpressionId("faire attention"),
      type: "expression",
      expression_type: "collocation",
      canonical_form: "faire attention",
      display_form: "faire attention à",
      english: ["to pay attention", "to be careful with"],
      base_verb_ids: [makeVerbId("faire")],
      related_vocabulary_ids: [makeVocabId("attention")],
      productive: true,
      collocation_strength: "strong",
      pattern: "faire attention à [NOUN / PERSON]",
      pattern_slots: [{ name: "target", display: "à quelque chose / quelqu'un", type: "target", required: false }],
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: [],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("faire_attention", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 40, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("idiomatic_expressions_with_faire")] },
      tags: ["essential", "collocation"],
    },
    {
      id: makeExpressionId("faire + infinitif"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "faire + infinitif",
      display_form: "faire + infinitif (causatif)",
      english: ["to have something done", "to make someone do something"],
      base_verb_ids: [makeVerbId("faire")],
      related_vocabulary_ids: [],
      productive: true,
      collocation_strength: "strong",
      pattern: "faire [INFINITIVE] [OBJECT]",
      pattern_slots: [{ name: "action", display: "infinitif", type: "verb_infinitive", required: true }],
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: ["Causative construction"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("causative", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 5 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 41, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("causative_faire_plus_infinitive")] },
      tags: ["essential", "causative", "verb_pattern"],
    },
  ];

  const vocabulary: Vocabulary[] = [
    {
      id: makeVocabId("attention"),
      type: "vocabulary",
      canonical_form: "attention",
      display_form: "l'attention",
      french: "attention",
      english: ["attention", "care"],
      part_of_speech: "noun",
      noun: { gender: "feminine", article: "l'", plural: "attentions" },
      senses: [{ sense_id: "vocab_attention_s1", english: ["attention"], usage_contexts: [], example_ids: [] }],
      semantic_domains: ["cognition"],
      word_family_ids: [],
      collocation_expression_ids: [makeExpressionId("faire attention")],
      false_friend: false,
      cognate: true,
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 2 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 40, context_type: "vocabulary_box" }],
      tags: ["essential", "noun", "chapter_04"],
    },
  ];

  const examples: Example[] = [
    {
      id: makeExampleId("aller", 1),
      type: "example",
      french: "Vas-tu au cinéma dimanche?",
      english: "Are you going to the movies on Sunday?",
      source_type: "book",
      annotations: { focus_spans: [{ text: "Vas-tu", role: "verb" }] },
      relations: { verbs: [makeVerbId("aller")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["Vas-tu"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 35, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("futur_proche", 1),
      type: "example",
      french: "Nous allons acheter une nouvelle machine à laver.",
      english: "We are going to buy a new washing machine.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "allons acheter", role: "future_construction" }] },
      relations: { verbs: [makeVerbId("aller"), makeVerbId("acheter")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["allons", "acheter"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 35, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("venir", 1),
      type: "example",
      french: "Elle vient nous voir ce soir.",
      english: "She is coming to see us tonight.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "vient", role: "verb" }] },
      relations: { verbs: [makeVerbId("venir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["vient"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 36, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("venir_chercher", 1),
      type: "example",
      french: "Je viens te chercher à la gare à dix heures.",
      english: "I am coming to pick you up at the train station at ten o'clock.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "viens te chercher", role: "expression" }] },
      relations: { verbs: [makeVerbId("venir"), makeVerbId("chercher")], expressions: [makeExpressionId("venir chercher quelqu'un")] },
      cloze_candidates: ["viens", "chercher"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 37, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("venir_de", 1),
      type: "example",
      french: "Je viens de téléphoner à Bernard.",
      english: "I have just called Bernard.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "viens de téléphoner", role: "recent_past" }] },
      relations: { verbs: [makeVerbId("venir")], expressions: [makeExpressionId("venir de + infinitif")] },
      cloze_candidates: ["viens de"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 37, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("faire", 1),
      type: "example",
      french: "Qu'est-ce que vous faites ce week-end?",
      english: "What are you doing this weekend?",
      source_type: "book",
      annotations: { focus_spans: [{ text: "faites", role: "verb" }] },
      relations: { verbs: [makeVerbId("faire")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["faites"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 40, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("faire_attention", 1),
      type: "example",
      french: "Faites attention à la marche!",
      english: "Watch your step! / Pay attention to the step!",
      source_type: "book",
      annotations: { focus_spans: [{ text: "Faites attention à", role: "expression" }] },
      relations: { verbs: [makeVerbId("faire")], expressions: [makeExpressionId("faire attention")] },
      cloze_candidates: ["Faites attention"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 40, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("causative", 1),
      type: "example",
      french: "Vous faites laver la voiture par votre fils.",
      english: "You are having the car washed by your son.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "faites laver", role: "causative" }] },
      relations: { verbs: [makeVerbId("faire"), makeVerbId("laver")], expressions: [makeExpressionId("faire + infinitif")] },
      cloze_candidates: ["faites laver"],
      study: { difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 4, page_printed: 41, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "More irregular verbs",
    section_ids: sections.map((s) => s.id),
    concept_ids: ["concept_movement"],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 34, page_end_printed: 42, page_start_pdf: 48, page_end_pdf: 56 },
    tags: ["aller", "venir", "faire", "causative", "futur_proche", "passe_recent"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}
