import { ChapterExtractionBundle } from "./chapter-types";
import { RawPage } from "./extract-pages";
import { extractChapterExercises } from "./extract-chapter";
import {
  GrammarRule,
  Verb,
  Conjugation,
  Expression,
  Vocabulary,
  Example,
  Chapter,
  Section,
} from "../src/lib/dataset/schemas";
import {
  makeChapterId,
  makeSectionId,
  makeRuleId,
  makeVerbId,
  makeConjugationId,
  makeVocabId,
  makeExpressionId,
  makeExampleId,
} from "../src/lib/dataset/ids";

// =======================================================================
// CHAPTER 3: To be and to have
// =======================================================================
export function buildChapter3(pages: RawPage[]): ChapterExtractionBundle {
  const chNum = 3;
  const chId = makeChapterId(chNum);
  const chPages = pages.filter((p) => (p.printed_page || 0) >= 24 && (p.printed_page || 0) <= 33);
  const exercises = extractChapterExercises(chNum, chPages);

  const sec1 = {
    id: makeSectionId(chNum, 1, "The verb etre (to be)"),
    chapter_id: chId,
    order: 1,
    title: "The verb être (to be)",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("verb_etre_present_conjugation"), makeRuleId("c_est_vs_il_est_rules")],
    verb_ids: [makeVerbId("être")],
    expression_ids: [makeExpressionId("etre d'accord"), makeExpressionId("c'est")],
    vocabulary_ids: [],
    example_ids: [makeExampleId("etre", 1)],
    exercise_ids: [exercises[0]?.id, exercises[1]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 24, page_end_printed: 26, page_start_pdf: 38, page_end_pdf: 40 },
  };

  const sec2 = {
    id: makeSectionId(chNum, 2, "The verb avoir (to have)"),
    chapter_id: chId,
    order: 2,
    title: "The verb avoir (to have)",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("verb_avoir_present_conjugation"), makeRuleId("idiomatic_expressions_with_avoir")],
    verb_ids: [makeVerbId("avoir")],
    expression_ids: [
      makeExpressionId("avoir faim"),
      makeExpressionId("avoir soif"),
      makeExpressionId("avoir chaud"),
      makeExpressionId("avoir froid"),
      makeExpressionId("avoir peur de"),
      makeExpressionId("avoir raison"),
      makeExpressionId("avoir tort"),
      makeExpressionId("avoir honte de"),
      makeExpressionId("avoir sommeil"),
      makeExpressionId("avoir besoin de"),
      makeExpressionId("avoir envie de"),
      makeExpressionId("avoir l'air de"),
      makeExpressionId("avoir l'habitude de"),
      makeExpressionId("avoir lieu"),
      makeExpressionId("avoir hâte de"),
    ],
    vocabulary_ids: [],
    example_ids: [makeExampleId("avoir", 1), makeExampleId("avoir_faim", 1)],
    exercise_ids: [exercises[2]?.id, exercises[3]?.id, exercises[4]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 26, page_end_printed: 28, page_start_pdf: 40, page_end_pdf: 42 },
  };

  const sec3 = {
    id: makeSectionId(chNum, 3, "The -oir verbs"),
    chapter_id: chId,
    order: 3,
    title: "The -oir verbs",
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: [makeRuleId("savoir_versus_connaitre"), makeRuleId("modal_verbs_vouloir_pouvoir_devoir"), makeRuleId("oir_verbs_conjugation_patterns")],
    verb_ids: [
      makeVerbId("savoir"),
      makeVerbId("connaître"),
      makeVerbId("vouloir"),
      makeVerbId("pouvoir"),
      makeVerbId("devoir"),
      makeVerbId("pleuvoir"),
      makeVerbId("falloir"),
      makeVerbId("apercevoir"),
      makeVerbId("recevoir"),
      makeVerbId("valoir"),
      makeVerbId("promouvoir"),
      makeVerbId("émouvoir"),
    ],
    expression_ids: [makeExpressionId("savoir faire quelque chose"), makeExpressionId("il faut + infinitif"), makeExpressionId("il pleut")],
    vocabulary_ids: [makeVocabId("par_coeur")],
    example_ids: [makeExampleId("savoir", 1), makeExampleId("connaitre", 1), makeExampleId("vouloir", 1)],
    exercise_ids: [exercises[5]?.id, exercises[6]?.id, exercises[7]?.id, exercises[8]?.id, exercises[9]?.id, exercises[10]?.id].filter(Boolean) as string[],
    source: { page_start_printed: 28, page_end_printed: 33, page_start_pdf: 42, page_end_pdf: 47 },
  };

  const sections = [sec1, sec2, sec3];

  const grammar_rules: GrammarRule[] = [
    {
      id: makeRuleId("verb_etre_present_conjugation"),
      type: "grammar_rule",
      title: "Conjugation and uses of être (to be) in the present",
      short_label: "être present",
      grammar_category: "irregular_verbs",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Irregular: je suis, tu es, il/elle/on est, nous sommes, vous êtes, ils/elles sont.",
      explanation: "Être is one of the two core auxiliary verbs in French. Used for identity, nationality, profession, adjectives, location, and passive voice.",
      formation: {
        steps: ["je suis, tu es, il est, nous sommes, vous êtes, ils sont"],
        patterns: ["irregular"],
        endings: {},
      },
      usage_conditions: ["Identity", "State", "Auxiliary"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Do not use articles with profession after être: 'Il est médecin' (not 'Il est un médecin')."],
      common_mistakes: [{ wrong: "Il est un médecin", correct: "Il est médecin", explanation: "Omit article with unmodified professions after être." }],
      contrast_with_rule_ids: [makeRuleId("verb_avoir_present_conjugation")],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("etre", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 24, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs", "auxiliary"],
    },
    {
      id: makeRuleId("c_est_vs_il_est_rules"),
      type: "grammar_rule",
      title: "Distinction between c'est and il est",
      short_label: "c'est vs il est",
      grammar_category: "syntax",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Use 'c'est' before modified nouns, proper names, pronouns, and general superlative comments; use 'il/elle est' before bare adjectives, professions, and nationalities.",
      explanation: "Use c'est + noun phrase (C'est un bon médecin), c'est + pronoun (C'est moi), c'est + proper noun (C'est Marie).\nUse il/elle est + adjective alone (Il est intelligent), il/elle est + bare profession (Il est médecin).",
      formation: null,
      usage_conditions: ["Identifying persons or things vs describing specific qualities"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Il est un médecin", correct: "C'est un médecin", explanation: "Use c'est when the noun is modified by an article." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 3 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 25, context_type: "grammar_explanation" }],
      tags: ["essential", "syntax"],
    },
    {
      id: makeRuleId("verb_avoir_present_conjugation"),
      type: "grammar_rule",
      title: "Conjugation of avoir (to have) in the present",
      short_label: "avoir present",
      grammar_category: "irregular_verbs",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Irregular: j'ai, tu as, il/elle/on a, nous avons, vous avez, ils/elles ont.",
      explanation: "Avoir is used to express possession, age, and forms many essential idiomatic physical/mental states where English uses 'to be'.",
      formation: {
        steps: ["j'ai, tu as, il a, nous avons, vous avez, ils ont"],
        patterns: ["irregular"],
        endings: {},
      },
      usage_conditions: ["Possession", "Age", "Auxiliary"],
      trigger_words: [],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: ["Notice liaison in nous avons [nuzavõ], vous avez [vuzave], ils ont [ilzõ]."],
      common_mistakes: [{ wrong: "Je suis 20 ans", correct: "J'ai 20 ans", explanation: "French uses avoir for age." }],
      contrast_with_rule_ids: [makeRuleId("verb_etre_present_conjugation")],
      related_rule_ids: [makeRuleId("idiomatic_expressions_with_avoir")],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("avoir", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "grammar_explanation" }],
      tags: ["essential", "irregular_verbs", "auxiliary"],
    },
    {
      id: makeRuleId("idiomatic_expressions_with_avoir"),
      type: "grammar_rule",
      title: "Idiomatic expressions with avoir",
      short_label: "avoir expressions",
      grammar_category: "idiomatic_construction",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "French uses avoir + noun where English uses to be + adjective (avoir faim, avoir peur, avoir raison, etc.).",
      explanation: "Essential expressions:\n- avoir faim (to be hungry)\n- avoir soif (to be thirsty)\n- avoir chaud / froid (to be hot / cold)\n- avoir peur de (to be afraid of)\n- avoir raison / tort (to be right / wrong)\n- avoir honte de (to be ashamed of)\n- avoir sommeil (to be sleepy)\n- avoir besoin de (to need)\n- avoir envie de (to feel like / desire)\n- avoir l'air (to look / seem)\n- avoir l'habitude de (to be used to)",
      formation: null,
      usage_conditions: ["Describing physical states, emotions, needs"],
      trigger_words: ["faim", "soif", "peur", "raison", "tort", "besoin", "envie"],
      signal_words: [],
      exceptions: [],
      restrictions: [],
      notes: [],
      common_mistakes: [{ wrong: "Je suis faim", correct: "J'ai faim", explanation: "Use avoir for hungry/thirsty/hot/cold." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [makeRuleId("verb_avoir_present_conjugation")],
      example_ids: [makeExampleId("avoir_faim", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "grammar_explanation" }],
      tags: ["essential", "collocations", "expressions"],
    },
    {
      id: makeRuleId("savoir_versus_connaitre"),
      type: "grammar_rule",
      title: "Difference between savoir and connaître (to know)",
      short_label: "savoir vs connaître",
      grammar_category: "verb_semantics",
      concept_ids: [],
      tense_ids: ["tense_present_indicative"],
      summary: "Savoir = to know facts, information, or how to do something (+ infinitive/clause); Connaître = to be acquainted with people, places, or things (+ direct object).",
      explanation: "- Savoir (je sais, tu sais, il sait, nous savons, vous savez, ils savent): followed by a clause (que, où, quand, pourquoi) or an infinitive (savoir nager).\n- Connaître (je connais, tu connais, il connaît, nous connaissons, vous connaissez, ils connaissent): followed directly by a noun (connaître Paris, connaître quelqu'un). Never followed by a verb or que clause.",
      formation: null,
      usage_conditions: ["Knowing facts/skills vs familiarity with persons/places"],
      trigger_words: ["que", "où", "comment", "pourquoi"],
      signal_words: [],
      exceptions: [],
      restrictions: ["Connaître is never followed by an infinitive or que clause."],
      notes: [],
      common_mistakes: [{ wrong: "Je connais nager", correct: "Je sais nager", explanation: "Use savoir before infinitive for knowing how to do something." }],
      contrast_with_rule_ids: [],
      related_rule_ids: [],
      prerequisite_rule_ids: [],
      example_ids: [makeExampleId("savoir", 1), makeExampleId("connaitre", 1)],
      exercise_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 28, context_type: "grammar_explanation" }],
      tags: ["essential", "verb_contrast"],
    },
  ];

  const verbsList3 = [
    { inf: "être", en: ["to be"], group: "irregular", reg: "irregular", part: "été" },
    { inf: "avoir", en: ["to have"], group: "irregular", reg: "irregular", part: "eu" },
    { inf: "savoir", en: ["to know (facts, how to)"], group: "3rd_group", reg: "irregular", part: "su" },
    { inf: "connaître", en: ["to know (be familiar with)"], group: "3rd_group", reg: "irregular", part: "connu" },
    { inf: "vouloir", en: ["to want", "to wish"], group: "3rd_group", reg: "irregular", part: "voulu" },
    { inf: "pouvoir", en: ["to be able to", "can"], group: "3rd_group", reg: "irregular", part: "pu" },
    { inf: "devoir", en: ["to have to", "must", "to owe"], group: "3rd_group", reg: "irregular", part: "dû" },
    { inf: "pleuvoir", en: ["to rain"], group: "impersonal", reg: "irregular", part: "plu" },
    { inf: "falloir", en: ["to be necessary", "must"], group: "impersonal", reg: "irregular", part: "fallu" },
    { inf: "apercevoir", en: ["to catch sight of", "to perceive"], group: "3rd_group", reg: "irregular", part: "aperçu" },
    { inf: "recevoir", en: ["to receive"], group: "3rd_group", reg: "irregular", part: "reçu" },
    { inf: "valoir", en: ["to be worth"], group: "3rd_group", reg: "irregular", part: "valu" },
    { inf: "promouvoir", en: ["to promote"], group: "3rd_group", reg: "irregular", part: "promu" },
    { inf: "émouvoir", en: ["to move emotionally"], group: "3rd_group", reg: "irregular", part: "ému" },
    { inf: "décevoir", en: ["to disappoint"], group: "3rd_group", reg: "irregular", part: "déçu" },
    { inf: "prévoir", en: ["to foresee", "to plan"], group: "3rd_group", reg: "irregular", part: "prévu" },
    { inf: "voir", en: ["to see"], group: "3rd_group", reg: "irregular", part: "vu" },
  ];

  const verbs: Verb[] = verbsList3.map((v) => {
    const vId = makeVerbId(v.inf);
    return {
      id: vId,
      type: "verb",
      infinitive: v.inf,
      display_form: v.inf,
      english: v.en,
      senses: [{ sense_id: `${vId}_s1`, english: v.en, usage_contexts: [], example_ids: [] }],
      verb_group: (v.group as any) || "3rd_group",
      regularity: (v.reg as any) || "irregular",
      pronominal: false,
      transitivity: ["transitive", "intransitive"],
      auxiliary: "avoir",
      past_participle: v.part || null,
      present_participle: null,
      conjugation_ids: [makeConjugationId(vId, "tense_present_indicative")],
      expression_ids: [],
      complement_frame_ids: [],
      related_verb_ids: [],
      contrast_verb_ids: v.inf === "savoir" ? [makeVerbId("connaître")] : v.inf === "connaître" ? [makeVerbId("savoir")] : [],
      confused_with_ids: v.inf === "savoir" ? [makeVerbId("connaître")] : v.inf === "connaître" ? [makeVerbId("savoir")] : [],
      word_family_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 2 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 5 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 24, context_type: "grammar_explanation" }],
      tags: ["oir_verbs", "essential", "chapter_03"],
    };
  });

  const conjugations: Conjugation[] = [
    {
      id: makeConjugationId("verb_etre", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("être"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je suis",
        tu: "tu es",
        il_elle_on: "il/elle/on est",
        nous: "nous sommes",
        vous: "vous êtes",
        ils_elles: "ils/elles sont",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: ["irregular across all persons"],
      example_ids: [makeExampleId("etre", 1)],
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 24, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_avoir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("avoir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "j'ai",
        tu: "tu as",
        il_elle_on: "il/elle/on a",
        nous: "nous avons",
        vous: "vous avez",
        ils_elles: "ils/elles ont",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: ["irregular across all persons"],
      example_ids: [makeExampleId("avoir", 1)],
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_savoir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("savoir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je sais",
        tu: "tu sais",
        il_elle_on: "il/elle/on sait",
        nous: "nous savons",
        vous: "vous savez",
        ils_elles: "ils/elles savent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("savoir", 1)],
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 28, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_connaitre", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("connaître"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je connais",
        tu: "tu connais",
        il_elle_on: "il/elle/on connaît",
        nous: "nous connaissons",
        vous: "vous connaissez",
        ils_elles: "ils/elles connaissent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: ["circumflex on î in il/elle connaît"],
      irregularity_notes: [],
      example_ids: [makeExampleId("connaitre", 1)],
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 28, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_vouloir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("vouloir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je veux",
        tu: "tu veux",
        il_elle_on: "il/elle/on veut",
        nous: "nous voulons",
        vous: "vous voulez",
        ils_elles: "ils/elles veulent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: [],
      example_ids: [makeExampleId("vouloir", 1)],
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 29, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
    {
      id: makeConjugationId("verb_pouvoir", "tense_present_indicative"),
      type: "conjugation",
      verb_id: makeVerbId("pouvoir"),
      tense_id: "tense_present_indicative",
      forms: {
        je: "je peux",
        tu: "tu peux",
        il_elle_on: "il/elle/on peut",
        nous: "nous pouvons",
        vous: "vous pouvez",
        ils_elles: "ils/elles peuvent",
      },
      compound: false,
      components: {},
      agreement_notes: [],
      spelling_change_notes: [],
      irregularity_notes: ["formal 1st person inverted form is 'puis-je'"],
      example_ids: [],
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 29, context_type: "conjugation_table" }],
      editorial: { extraction_confidence: "high", verification_status: "machine_checked" },
    },
  ];

  const expressions: Expression[] = [
    {
      id: makeExpressionId("avoir besoin de"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "avoir besoin de",
      display_form: "avoir besoin de + nom / infinitif",
      english: ["to need something", "to have need of doing something"],
      base_verb_ids: [makeVerbId("avoir")],
      related_vocabulary_ids: [makeVocabId("besoin")],
      productive: true,
      collocation_strength: "strong",
      pattern: "avoir besoin de [NOUN / INFINITIVE]",
      pattern_slots: [{ name: "target", display: "nom ou infinitif", type: "noun_or_infinitive", required: true }],
      transformations: [],
      variants: ["avoir besoin d'"],
      function_ids: [],
      usage_notes: ["Use 'de' before nouns and infinitives"],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: ["communication", "needs"] },
      frequency: { book_occurrences: 4 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("idiomatic_expressions_with_avoir")] },
      tags: ["essential", "collocation", "verb_pattern"],
    },
    {
      id: makeExpressionId("avoir envie de"),
      type: "expression",
      expression_type: "verb_pattern",
      canonical_form: "avoir envie de",
      display_form: "avoir envie de + nom / infinitif",
      english: ["to feel like (doing) something", "to want / crave something"],
      base_verb_ids: [makeVerbId("avoir")],
      related_vocabulary_ids: [makeVocabId("envie")],
      productive: true,
      collocation_strength: "strong",
      pattern: "avoir envie de [NOUN / INFINITIVE]",
      pattern_slots: [{ name: "target", display: "nom ou infinitif", type: "noun_or_infinitive", required: true }],
      transformations: [],
      variants: ["avoir envie d'"],
      function_ids: [],
      usage_notes: [],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 3 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("idiomatic_expressions_with_avoir")] },
      tags: ["essential", "collocation", "verb_pattern"],
    },
    {
      id: makeExpressionId("avoir faim"),
      type: "expression",
      expression_type: "collocation",
      canonical_form: "avoir faim",
      display_form: "avoir faim",
      english: ["to be hungry"],
      base_verb_ids: [makeVerbId("avoir")],
      related_vocabulary_ids: [makeVocabId("faim")],
      productive: false,
      collocation_strength: "strong",
      pattern: "avoir faim",
      pattern_slots: [],
      transformations: [],
      variants: ["avoir très faim"],
      function_ids: [],
      usage_notes: [],
      restrictions: [],
      common_mistakes: [],
      example_ids: [makeExampleId("avoir_faim", 1)],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 3 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("idiomatic_expressions_with_avoir")] },
      tags: ["essential", "collocation"],
    },
    {
      id: makeExpressionId("avoir raison"),
      type: "expression",
      expression_type: "collocation",
      canonical_form: "avoir raison",
      display_form: "avoir raison",
      english: ["to be right", "to be correct"],
      base_verb_ids: [makeVerbId("avoir")],
      related_vocabulary_ids: [makeVocabId("raison")],
      productive: false,
      collocation_strength: "strong",
      pattern: "avoir raison",
      pattern_slots: [],
      transformations: [],
      variants: [],
      function_ids: [],
      usage_notes: [],
      restrictions: [],
      common_mistakes: [],
      example_ids: [],
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 3 },
      origin: { source_type: "book", created_by: "extraction", derived_from_ids: [] },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "grammar_explanation" }],
      relations: { grammar_rules: [makeRuleId("idiomatic_expressions_with_avoir")] },
      tags: ["essential", "collocation"],
    },
  ];

  const vocabulary: Vocabulary[] = [
    {
      id: makeVocabId("faim"),
      type: "vocabulary",
      canonical_form: "faim",
      display_form: "la faim",
      french: "faim",
      english: ["hunger"],
      part_of_speech: "noun",
      noun: { gender: "feminine", article: "la", plural: "faims" },
      senses: [{ sense_id: "vocab_faim_s1", english: ["hunger"], usage_contexts: [], example_ids: [] }],
      semantic_domains: ["physical_state"],
      word_family_ids: [],
      collocation_expression_ids: [makeExpressionId("avoir faim")],
      false_friend: false,
      cognate: false,
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 2 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 26, context_type: "vocabulary_box" }],
      tags: ["essential", "noun", "chapter_03"],
    },
    {
      id: makeVocabId("raison"),
      type: "vocabulary",
      canonical_form: "raison",
      display_form: "la raison",
      french: "raison",
      english: ["reason", "rightness"],
      part_of_speech: "noun",
      noun: { gender: "feminine", article: "la", plural: "raisons" },
      senses: [{ sense_id: "vocab_raison_s1", english: ["reason"], usage_contexts: [], example_ids: [] }],
      semantic_domains: ["cognition"],
      word_family_ids: [],
      collocation_expression_ids: [makeExpressionId("avoir raison")],
      false_friend: false,
      cognate: true,
      study: { learning_priority: 5, usefulness: 5, difficulty: 1 },
      usage: { register: "neutral", spoken_written: "both", contexts: [] },
      frequency: { book_occurrences: 2 },
      attestations: [{ source_type: "book", chapter_number: chNum, chapter_id: chId, page_printed: 26, context_type: "vocabulary_box" }],
      tags: ["essential", "noun", "chapter_03"],
    },
  ];

  const examples: Example[] = [
    {
      id: makeExampleId("etre", 1),
      type: "example",
      french: "Nous sommes heureux de vous voir.",
      english: "We are happy to see you.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "sommes", role: "verb" }] },
      relations: { verbs: [makeVerbId("être")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["sommes"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 24, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("avoir", 1),
      type: "example",
      french: "Ils ont un chien et deux chats.",
      english: "They have a dog and two cats.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "ont", role: "verb" }] },
      relations: { verbs: [makeVerbId("avoir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["ont"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 26, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("avoir_faim", 1),
      type: "example",
      french: "Il a très faim après le voyage.",
      english: "He is very hungry after the trip.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "a très faim", role: "expression" }] },
      relations: { verbs: [makeVerbId("avoir")], expressions: [makeExpressionId("avoir faim")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["a", "faim"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 27, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("savoir", 1),
      type: "example",
      french: "Est-ce que tu sais cette chanson française par cœur?",
      english: "Do you know this French song by heart?",
      source_type: "book",
      annotations: { focus_spans: [{ text: "sais", role: "verb" }] },
      relations: { verbs: [makeVerbId("savoir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["sais"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 32, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("connaitre", 1),
      type: "example",
      french: "Elle connaît Caroline depuis l'université.",
      english: "She has known Caroline since college.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "connaît", role: "verb" }] },
      relations: { verbs: [makeVerbId("connaître")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["connaît"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 32, context_type: "example_sentence" }],
    },
    {
      id: makeExampleId("vouloir", 1),
      type: "example",
      french: "Nous voulons réserver une table pour ce soir.",
      english: "We want to reserve a table for tonight.",
      source_type: "book",
      annotations: { focus_spans: [{ text: "voulons", role: "verb" }] },
      relations: { verbs: [makeVerbId("vouloir")], tenses: ["tense_present_indicative"] },
      cloze_candidates: ["voulons"],
      study: { difficulty: 1 },
      attestations: [{ source_type: "book", chapter_number: 3, page_printed: 30, context_type: "example_sentence" }],
    },
  ];

  const chapter: Chapter = {
    id: chId,
    chapter_number: chNum,
    title: "To be and to have",
    section_ids: sections.map((s) => s.id),
    concept_ids: [],
    tense_ids: ["tense_present_indicative"],
    grammar_rule_ids: grammar_rules.map((r) => r.id),
    verb_ids: verbs.map((v) => v.id),
    conjugation_ids: conjugations.map((c) => c.id),
    expression_ids: expressions.map((e) => e.id),
    vocabulary_ids: vocabulary.map((v) => v.id),
    example_ids: examples.map((e) => e.id),
    exercise_ids: exercises.map((e) => e.id),
    source: { page_start_printed: 24, page_end_printed: 33, page_start_pdf: 38, page_end_pdf: 47 },
    tags: ["etre", "avoir", "oir_verbs", "modal_verbs", "present_tense"],
  };

  return { chapter, sections, grammar_rules, verbs, conjugations, vocabulary, expressions, examples, exercises };
}
